### PR TITLE
Update network graph

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

documentation

### Related issue(s)

Update network graph, fix fetchmail when PROXY_PROTOCOL_25 is set

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
@fastlorenzo have another look, let me know

It looks like generated that way the image is too big

**Comment by fastlorenzo** [comment]
Changed the code to this to make the graph more readable:

```
digraph mailu {
    label = "Mailu network flows";
    fontname = "arial";
    
    node [shape = record; fontname = "arial"; fontsize = 8; style = filled; color = "#d3edea";];
    splines = "compound";
    // node [shape = "box"; fontsize = "10";];
    edge [fontsize = 8; arrowsize = 0.5;];
    
    # Components
    internet [label = "Internet"; color = "red";];
    proxy [label = "Proxy (optional)"; color = "darkorange";];
    front [label="Front"; color="skyblue";];
    admin [label="Admin"; color="green"; fontcolor="white";];
    smtp [label="SMTP"; color="orchid";];
    redis [label="Redis"; color="turquoise";];
    antispam [label="Antispam"; color="magenta";];
    antivirus [label="Antivirus"; color="purple"; fontcolor="white";];
    imap [label="IMAP"; color="cyan";];
    webdav [label="WebDAV"; color="yellow";];
    webmail [label="Webmail"; color="darkgoldenrod";];
    fetchmail [label="Fetchmail"; color="chocolate";];
    oletools [label="Oletools"; color="limegreen";];
    fts_attachments [label="Tika"; color="sienna";];

    rankdir=LR;
    {rank=min; internet};
    // {rank=3; proxy};
    // {rank=4; front};
    // {rank=same; admin smtp redis antispam antivirus imap};
    {rank=max; fetchmail};

    # Proxy from internet

    internet -> proxy [
        color="red";
        fontcolor="red";
        label = <
        <TABLE BORDER="0" CELLBORDER="1" CELLPADDING="1">
            <TR>
                <TD>80/tcp</TD>
                <TD>443/tcp</TD>
            </TR>
            <TR>
                <TD>25/tcp</TD>
                <TD>465/tcp</TD>
            </TR>
            <TR>
                <TD>587/tcp</TD>
                <TD>110/tcp</TD>
            </TR>
            <TR>
                <TD>995/tcp</TD>
                <TD>143/tcp</TD>
            </TR>
            <TR>
                <TD>993/tcp</TD>
                <TD>4190/tcp</TD>
            </TR>
        </TABLE>
        >;
    ];

    # Front from proxy
    proxy -> front [
        color="darkorange";
        fontcolor="darkorange";
        label = <
        <TABLE BORDER="0" CELLBORDER="1" CELLPADDING="1">
            <TR>
                <TD>80/tcp</TD>
                <TD>443/tcp</TD>
            </TR>
            <TR>
                <TD>25/tcp</TD>
                <TD>465/tcp</TD>
            </TR>
            <TR>
                <TD>587/tcp</TD>
                <TD>110/tcp</TD>
            </TR>
            <TR>
                <TD>995/tcp</TD>
                <TD>143/tcp</TD>
            </TR>
            <TR>
                <TD>993/tcp</TD>
                <TD>4190/tcp</TD>
            </TR>
        </TABLE>
        >;
    ];
    
    front -> front [label = "8008/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> front [label = "8000/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> admin [label = "8080/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> imap [label = "4190/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> imap [label = "143/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> imap [label = "110/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> smtp [label = "25/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> smtp [label = "10025/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> webmail [label = "80/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> antispam [label = "11334/tcp"; color="skyblue"; fontcolor="skyblue";];
    front -> webdav [label = "5232/tcp"; color="skyblue"; fontcolor="skyblue";];
    
    smtp -> admin [label = "8080/tcp"; color="orchid"; fontcolor="orchid";];
    smtp -> front [label = "2525/tcp"; color="orchid"; fontcolor="orchid";];
    smtp -> antispam [label = "11332/tcp"; color="orchid"; fontcolor="orchid";];
    
    imap -> admin [label = "8080/tcp"; color="cyan"; fontcolor="cyan";];
    imap -> antispam [label = "11334/tcp"; color="cyan"; fontcolor="cyan";];
    imap -> proxy [label = "25/tcp"; color="cyan"; fontcolor="cyan";];
    imap -> fts_attachments [label = "9998/tcp"; color="cyan"; fontcolor="cyan";];
    
    webmail -> front [label = "14190/tcp"; color="darkgoldenrod"; fontcolor="darkgoldenrod";];
    webmail -> front [label = "10025/tcp"; color="darkgoldenrod"; fontcolor="darkgoldenrod";];
    webmail -> front [label = "10143/tcp"; color="darkgoldenrod"; fontcolor="darkgoldenrod";];
    # carddav
    webmail -> proxy [label = "443/tcp"; color="darkgoldenrod"; fontcolor="darkgoldenrod";];
    
    admin -> redis [label = "6379/tcp"; color="green"; fontcolor="green";];
    admin -> front [label = "2525/tcp"; color="green"; fontcolor="green";];
    
    antispam -> redis [label = "6379/tcp"; color="magenta"; fontcolor="magenta";];
    antispam -> admin [label = "8080/tcp"; color="magenta"; fontcolor="magenta";];
    antispam -> oletools [label = "11343/tcp"; color="magenta"; fontcolor="magenta";];
    antispam -> antivirus [label = "3310/tcp"; color="magenta"; fontcolor="magenta";];
    
    fetchmail -> admin [label = "8080/tcp"; color="chocolate"; fontcolor="chocolate";];
    fetchmail -> proxy [label = "25/tcp"; color="chocolate"; fontcolor="chocolate";];
    fetchmail -> front [label = "2525/tcp"; color="chocolate"; fontcolor="chocolate";];
    #
    # those don't need internet:
    # oletools
    # fts_attachments
    # redis
}
```

To generate the PNG, use: `dot -Tpng mailu-network-diagram.dot -o mailu-network-diagram.png`

**Comment by fastlorenzo** [comment]
mailu-network-diagram

**Comment by nextgens** [comment]
Sphinx is still mangling the SVG files and creating something that just does not look right. Any idea?

image
test

**Review by ghostwheel42 — APPROVED** [review]

**Pull request merged**
