### PR TITLE
Fix resolving alias addresses for postfix when target is a punycode domain

### LINKED ISSUE #2393: Alternative domain of unicode domain results in "Bad adress syntax"
### Environment
 - [x] docker-compose
 - ~~[ ] kubernetes~~
 - ~~[ ] docker swarm~~

### Versions
Version 1.9

## Description
My setup includes a domain that has Unicode characters (i.e. German umlauts), e.g. `exämple.com`. There is an alternative domain that provides a 'fallback' so users can also send emails to `example.com`. The domain has an account `mail@exämple.com` which is able to receive emails as expected. When sending an email to `mail@example.com`, the sender receives an error message provided with the Postfix error message:

```
<mail@ex??mple.com> (expanded from <mail@example.com>): bad address syntax
```

I suspect the cause might be that when looking up the alternative domain, the unicode version is provided to Postfix instead of the IDNA code (`xn--exmple-cua.com`).

It should be noted that my setup doesn't have a top-level domain with an umlaut but instead a subdomain with an umlaut (e.g. `ümlaut.example.com`). I didn't have a way to test it using a domain that contains any unicode characters itself.

## Replication Steps
1. Create a new mail domain containing an umlaut (e.g. `exämple.com`)
2. Add an account to this domain
3. Create an alternative for this domain that doesn't contain any umlaut (e.g. `example.com`)
4. Send an email to the account using the alternative domain

## Expected behaviour
The email sent to the alternative domain should be received without any error and should appear in the account's inbox (which has a primary domain with an umlaut).

## Logs

Postfix logs:

````markdown
smtp_1       | INFO:root:Connect
smtp_1       | DEBUG:root:Received bytearray(b'sendermap sender@email.com')
smtp_1       | DEBUG:root:Request sendermap/sender@email.com
smtp_1       | DEBUG:root:Table get sender@email.com
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'recipientmap recipient@no-umlaut-alternative.example.com')
smtp_1       | DEBUG:root:Request recipientmap/recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Table get recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'alias recipient@no-umlaut-alternative.example.com')
smtp_1       | DEBUG:root:Request alias/recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Table get recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Table get recipient@no-umlaut-alternative.example.com is recipient@umläut.example.com
smtp_1       | DEBUG:root:Replying b'OK recipient@uml\xc3\xa4ut.example.com'
smtp_1       | DEBUG:root:Received bytearray(b'alias recipient@uml\xc3\xa4ut.example.com')
smtp_1       | DEBUG:root:Request alias/recipient@umläut.example.com
smtp_1       | DEBUG:root:Table get recipient@umläut.example.com
smtp_1       | DEBUG:root:Table get recipient@umläut.example.com is recipient@umläut.example.com
smtp_1       | DEBUG:root:Replying b'OK recipient@uml\xc3\xa4ut.example.com'
smtp_1       | 2022-07-26T16:25:19.988453+00:00 dc2c0dc34192 postfix/cleanup[3824]: E3B23192FB03: message-id=<####@example.com>
smtp_1       | 2022-07-26T16:25:20.081615+00:00 dc2c0dc34192 postfix/qmgr[339]: E3B23192FB03: from=<sender@email.com>, size=281, nrcpt=1 (queue active)
smtp_1       | 2022-07-26T16:25:20.083187+00:00 dc2c0dc34192 postfix/smtpd[3821]: disconnect from mailu_webmail_1.mailu_default[192.168.203.7] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
smtp_1       | 2022-07-26T16:25:20.103349+00:00 dc2c0dc34192 postfix/error[3825]: E3B23192FB03: to=<recipient@uml??ut.example.com>, orig_to=<recipient@no-umlaut-alternative.example.com>, relay=none, delay=0.36, delays=0.34/0.01/0/0.01, dsn=5.1.3, status=bounced (bad address syntax)
````

Error message provided by Postfix:

```
This is the mail system at host mail.example.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@uml??ut.example.com> (expanded from
    <[recipient@no-umlaut-alternative.example.com](mailto:recipient@no-umlaut-alternative.example.com)>): bad address syntax
Reporting-MTA: dns; mail.example.com
X-Postfix-Queue-ID: E3B23192FB03
X-Postfix-Sender: rfc822; [sender@email.com](mailto:sender@email.com)
Arrival-Date: Tue, 26 Jul 2022 16:25:19 +0000 (UTC)

Final-Recipient: rfc822; recipient@uml??ut.example.com
Original-Recipient: rfc822;[recipient@umlaut.example.com](mailto:recipient@umlaut.example.com)
Action: failed
Status: 5.1.3
Diagnostic-Code: X-Postfix; bad address syntax
```

### PR DESCRIPTION
**Pull request by ghostwheel42**
## What type of PR?

bug-fix

## What does this PR do?

- fix splitting of localpart in resolve_destination
- idna-enode domain-part of email addresses before returning to postfix

### Related issue(s)
- closes #2393

### CODE REVIEW

**Comment by ghostwheel42** [comment]
I'm not 100% sure if postfix_sender_login() should also idna-encode its results.

**Comment by Diman0** [comment]
sender_login() is used when you send email isn't it? 

I will simply include that in my tests and check if sending still works with a normal email address and an email address with an umlaut.

**Comment by ghostwheel42** [comment]
> sender_login() is used when you send email isn't it?

it is used here: https://github.com/Mailu/Mailu/blob/d0a5ea6427ebbaf05c0a59992e4cb6eb44db801f/core/postfix/conf/main.cf#L103

smtpd_sender_login_maps maps the sender (mail from) to the allowed SASL login names.
So my change will change how a login using a punycode address is handled.
Maybe users are currently able to log in via foo@exämple.com and now need to login as xn--exmple-cua.com?
I don't know if an umlaut login has ever worked though.

**Comment by Diman0** [comment]
1. Created domain example.com and added exämple.com as alternative for this domain. 
2. Created user test@exämple.com
3. Logged in webmail (with a different user), send an email to test@example.com and test@exämple.com.
4. Logged in webmail for user test@example.com It shows 2 emails :+1: 
5. Deleted the domains.

1. Created domain exämple.com and user test@exämple.com.
2. Checked if I can login via webmail using test@exämple.com. SUCCESS. I can login.
3. Checked if I can login via webmail using test@xn--exmple-cua.com. ERROR. I can login.
4. Via webmail, send an email to test@exämple.com. It arrived.

@ghostwheel42 I think this confirms your fixes work as intended. Domain alternative works. Logging in works. Do you agree?

**Comment by ghostwheel42** [comment]
Yes, I think now it works as intended.

**Review by Diman0 — APPROVED** [review]
LGTM

**Pull request merged**
