### PR TITLE
Docs to avoid Update of letsencrypt certificates not possible

### LINKED ISSUE #1164: Update of letsencrypt certificates not possible
I cannot update the mailserver's letsencrypt certificates. The following error message is shown in the logs:
```
front_1      | Failed authorization procedure. webmail.myhost.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https://127.0.0.1/.well-known/acme-challenge/<the-challenge>: Invalid host in redirect target "127.0.0.1". Only domain names are supported, not IP addresses
```

I don't know where this comes from as in the .env file host names and urls seem to be set correctly. 127.0.0.1 is not part of any configuration parameter.

Mailu-Version: 1.7 (actually the docker image is still listed as 1.6 when executing `docker container ls`, so I am not 100% sure. I did a `docker-compose pull` and `docker-compose up -d` after the 1.7 release.

### PR DESCRIPTION
**Pull request by oli-ver**
Documentation update to avoid problem described in #1164

## What type of PR?

documentation

### Related issue(s)
closes #1164

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [X] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by kaiyou** [comment]
As commented in your issue, I am really surprised about this behavior. Are you sure that after changing the variable you recreated the containers properly ? (`up` should recreate them automatically)

**Comment by kaiyou** [comment]
After checking the code, I confirm my suspicion about containers not being properly recreated.

**Comment by oli-ver** [comment]
I am pretty sure I tried both restarting and recreating the containers. I will try to reproduce it in a separate VM.

**Comment by muhlemmer** [comment]
in this aspect `docker-compose stop` is not the same as `docker-compose down`. Doing `up` after a `stop` restarts the same containers, no reloading of environment is done. Only a `down` and `up` recreates the containers.

**Comment by kaiyou** [comment]
Damn. Wrong pr. I hope bors will not roll..

**Pull request closed without merging**
