### PR TITLE
Alpine 3.20

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

Switch to alpine 3.20. We still need edge for hardened-malloc.

Ensure we use 'normalize-icu' when indexing keywords in mails.

### Related issue(s)
- #2977

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors retry

**Comment by nextgens** [comment]
bors retry

**Comment by nextgens** [comment]
bors retry

**Review by ghostwheel42 — APPROVED** [review]
Let's test this

**Pull request merged**
