### PR TITLE
Add in antispam option in online setup wizard

### PR DESCRIPTION
**Pull request by bladeswords**
## What type of PR?

bug-fix

## What does this PR do?
My attempt at fixing a bug - may not be complete
### Related issue(s)
- Issue raised is #858 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ X ] In case of feature or enhancement: documentation updated accordingly
- [ X ] Unless it's docs or a minor change: place entry in the [changelog](CHANGELOG.md), under the latest un-released version.

### CODE REVIEW

**Comment by muhlemmer** [comment]
Anti-spam can't be optional. Postfix will fail when it can't connect to rspamd... (Or have you made it run successfully somehow?)

**Comment by bladeswords** [comment]
Hmmm, I think my description was incomplete.  Also, perhaps it would be better to change the generated mailu.env file then what is proposed in this patch.

My issue was with the setup wizard, for example - http://setup.mailu.io/1.6/file/867459ae-365a-4830-9c0d-2e007db01997/mailu.env

Then under 'Optional features' anti-spam is listed with the value of 'none'.  This gives the impression that it is in fact optional, and that the feature has been disabled.  But you rightfully state @muhlemmer , it can't be optional.

image

So this could be better addressed by changing the mailu.env template to reflect that this isn't optional and that setting it to 'none' will still result in a anti-spam feature being installed?

**Comment by Nebukadneza** [comment]
Sorry to come with a discussion so late to the game, but … do I see it correctly that the `ANTISPAM` environment-variable is neither checked nor used anywhere anymore? Rather than setting it to a lighthouse-value just to be seen, should we maybe remove it?

**Comment by bladeswords** [comment]
I was actually thinking that myself - maybe there are plans in the future to allow it to be customised, but if it isn't optional...just remove it

**Comment by muhlemmer** [comment]
We chose to let commented-out values in the `mailu.env` file, so that people with past experience of Mailu are informed what the value is set to in `docker-compose.yml`. And yet, they would see that changing it in `mailu.env` is pointless, as it is commented out.

The fact that `antispam` is set to `none` is a remainder from a very early  and experimental version of setup (we forgot to take it out).

Perhaps its indeed better to take out all the commented fields, as it already starts to lead to confusion.

**Comment by muhlemmer** [comment]
I've created a general issue to cleanup `mailu.env`, as a reminder. This PR can now be closed.

**Pull request closed without merging**
