### PR TITLE
Integrate webdav with rainloop

### PR DESCRIPTION
**Pull request by benyanke**
WIP, don't merge yet. Trying to integrate RainLoop's CardDav functionality to radicale.

Implements #589

### CODE REVIEW

**Comment by muhlemmer** [comment]
@benyanke: Just adding the blocked status, to keep a better overview in the PR qeue on what to focus. I'll remove as soon you're ready for review.

**Comment by benyanke** [comment]
Thanks - I haven't had as much time as I'd like to work on Mailu, but hopefully will have some free time soon,

**Comment by kaiyou** [comment]
@benyanke do you think you will keep working on this PR?

**Comment by muhlemmer** [comment]
> @benyanke do you think you will keep working on this PR?

I think it is save to say we can close this. The current PR caries a single line addition, which is already conflicting. I guess if anybody would implement this, they might as well open a new PR.

**Comment by benyanke** [comment]
Sorry for the delay. I can rebase this on the current one.

**Comment by benyanke** [comment]
Just resolved the conflict - does that look better now?

**Comment by muhlemmer** [comment]
@benyanke, you removed WIP, but I have the feeling this is not yet done, right?

**Comment by micw** [comment]
> Showing 378 changed files with 12,056 additions and 5,516 deletions.

@benyanke The correct way to catch up with master is to rebase. I suggest that you create a new branch on master, cherry-pick your changes and create a new PR. Alternatively do the same and force-push over the old PR.

**Comment by Nebukadneza** [comment]
As muhlemmer already stated, there’s currently one a small addition in here.

I hope you don’t take an offense in me closing it — feel free to re-open, and thanks for your effort nonetheless!

**Comment by benyanke** [comment]
None taken! When I have a chance to come back to this I'll check it out!

**Pull request closed without merging**
