### PR TITLE
Upgrade rspamd

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

Upgrade rspamd to a version that hopefully won't segfault on arm

### Related issue(s)
- #1200

### CODE REVIEW

**Comment by Diman0** [comment]
@nextgens 
When testing receiving emails I see that RCVD_NO_TLS_LAST still has score 0.1. 
Can you check if you observe the same?

No matter what I try in settings.conf, it appears to be ignored :(
I have tried so far
```
disable_symbol {
	priority = high;
	apply {
		RCVD_NO_TLS_LAST = 0;
	}
}
``` 
and
```
disable_symbol {
	priority = high;
	rcpt = "*" ;
	apply {
		RCVD_NO_TLS_LAST = 0;
	}
}
``` 

I must confess I don't remember checking this thoroughly when you applied PR #2033. I assumed you tested this yourself and it looked sound to me.

**Review by Diman0 — CHANGES_REQUESTED** [review]
Ok. I found the correct setting and config file. Pff. I always have the feeling they make the rspamd documentation as incomprehensible as possible. They do everything in their power to make you not understand the documentation.

Remove the file /conf/settings.conf
Create the file /conf/headers_group.conf with contents
```
symbols = {
    "RCVD_NO_TLS_LAST" {
        weight = 0.0;
        description = "Last hop did not use encrypted transports";
    }
}
```
With this I see that the symbol RCVD_NO_TLS_LAST now has score 0

**Comment by nextgens** [comment]
Yeah, it's everything but clear :/

**Review by Diman0 — APPROVED** [review]
Looks good to me.

**Comment by kirbylink** [comment]
Will this changes also merged into the 1.8 branch?

**Comment by nextgens** [comment]
@kirbylink no. ARM isn't supported so there is no reason to backport it.

1.9 will be released soon and while we do expect ARM to work it won't be supported on that version either.

**Comment by kirbylink** [comment]
@nextgens 
Thanks for the update/information. :)
Only one last question: Is there a release plan for 1.9?

**Pull request merged**
