### PR TITLE
Mailulogo

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by reallinfo** [comment]
I wanted to contribute to Mailu and I designed a logo for Mailu. If you like it, you can use it.

**Comment by reallinfo** [comment]
Hey, Are you there? :)

**Comment by kaiyou** [comment]
Well, you closed the pull request and emailed me that you had a better version to come up with. Where are you on this?

**Comment by reallinfo** [comment]
https://github.com/Mailu/Mailu/pull/509 There were logoda technical mistakes and I fixed this. I thought I sent you the logo.. sorry for the late message. I sent a pr. Please check it.

**Pull request closed without merging**
