### PR TITLE
Add support for custom NGINX config

### PR DESCRIPTION
**Pull request by easybe**
## What type of PR?

enhancement

## What does this PR do?

Add support for custom NGINX config. Including *.conf files in /etc/nginx/conf.d same as the default NGINX configuration gives the user more flexibility.

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
What are you trying to solve?
We already have https://github.com/Mailu/Mailu/blob/e48e2cdc1ae827f6e048f972f823d863d7a57ef9/core/nginx/conf/nginx.conf#L135 as documented here https://mailu.io/1.9/faq.html#how-can-i-override-settings

**Comment by easybe** [comment]
> What are you trying to solve? We already have
> 
> https://github.com/Mailu/Mailu/blob/e48e2cdc1ae827f6e048f972f823d863d7a57ef9/core/nginx/conf/nginx.conf#L135
> 
> as documented here https://mailu.io/1.9/faq.html#how-can-i-override-settings

The problem with
https://github.com/Mailu/Mailu/blob/e48e2cdc1ae827f6e048f972f823d863d7a57ef9/core/nginx/conf/nginx.conf#L135
it that it is within a `server` block. I am seeking the possibility to provide my own `server` blocks.

**Comment by ghostwheel42** [comment]
Sorry for the delay. 
Could you give an example why you would like to add your own server blocks?
Do you want to use the front container as reverse proxy for other services?

**Comment by easybe** [comment]
> Do you want to use the front container as reverse proxy for other services?

Yes, exactly.

**Comment by heshiming** [comment]
I second this. Basically what I want is another override inclusion under the "http{}" block so that I can run other services on the same server.

**Review by Diman0 — APPROVED** [review]
lgtm

**Review by nextgens — APPROVED** [review]
LGTM

**Pull request merged**
