### PR TITLE
Add Persian (aka Farsi) Translation

### PR DESCRIPTION
**Pull request by hosni**
Hello,
First of anything, thanks for this project that make setup email server easier that ever.
In this pull request, I added Persian (aka Farsi) translation to Mailu project.
I hope it's being useful for community.

### CODE REVIEW

**Review by ghostwheel42 — DISMISSED** [review]
Thanks. LGTM

**Comment by ghostwheel42** [comment]
I'm not sure if all text needs to be "mirrored", as the word inside are written left-to-right instead of right-to-left.
We'll see how the web-interface presents it.

**Review by ghostwheel42 — DISMISSED** [review]

**Review by nextgens — DISMISSED** [review]
This needs a towncrier entry but looks otherwise ready.

Thank you for your contribution!

**Review by hosni — COMMENTED** [review]
I reviewed, but there is not change request.

**Review by nextgens — APPROVED** [review]
LGTM

**Review by ghostwheel42 — APPROVED** [review]

**Pull request merged**
