### PR TITLE
fix 2147: MESSAGE_SIZE_LIMIT wasn't working

### LINKED ISSUE #2147: MESSAGE_SIZE_LIMIT not enforced by nginx
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose

### Versions
1.9

## Description
Using default MESSAGE_SIZE_LIMIT in mailu.env (50MB). But unable to upload attachment higher than 1MB. By reading the nginx documentation http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size, 1MB is the default value if nothing is specified.

I tried to edit nginx.conf file in front container and applying 50MB with `client_max_body_size 50M` instead of `client_max_body_size 58388608` and restart nginx with `nginx -s reload`

```
location /webmail {

        rewrite ^(/webmail)$ $1/ permanent;
        rewrite ^/webmail/(.*) /$1 break;

        include /etc/nginx/proxy.conf;
        client_max_body_size 50M;
        auth_request /internal/auth/user;
        error_page 403 @webmail_login;
        proxy_pass http://$webmail;
      }
```
But it also fails with error 413 (Request Entity Too Large)

Next, i moved the `client_max_body_size` to the server block instead of location block, then it works.
 

## Replication Steps
Spawn mailu instance with default values
try to upload an attachment in roundcube greater than 1MB

## Expected behaviour
I should be able to upload attachment greater than 1MB

## Logs

````markdown
```
front_1      | 2022/01/06 16:09:08 [error] 9#9: *1 client intended to send too large body: 2549636 bytes, client: 82.66.114.154, server: , request: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=181297800361d70f8da9368&_uploadid=upload1641485348314&_action=upload HTTP/2.0", subrequest: "/internal/auth/user", host: "xxxx.xxxx.xx", referrer: "https://xxxx.xxxx.xx/webmail/?_task=mail&_action=compose&_id=181297800361d70f8da9368"

front_1      | 2022/01/06 16:09:08 [error] 9#9: *1 auth request unexpected status: 413, client: 82.66.114.154, server: , request: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=181297800361d70f8da9368&_uploadid=upload1641485348314&_action=upload HTTP/2.0", host: "xxx.xxxx.xx", referrer: "https://xxx.xxx.xx/webmail/?_task=mail&_action=compose&_id=181297800361d70f8da9368"

```
````

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

bug-fix

## What does this PR do?

Set client_max_body_size in the server's scope.

I haven't tested it but it makes sense regardless.

### Related issue(s)
- closes #2147

### CODE REVIEW

**Comment by willofr** [comment]
As peer NGINX documentation (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size), client_max_body_size is usable in location context.

I haven't proposed this kind of PR because i think it's the easy way without understanding the root cause. 

Here is may bethe beginning of an answer:

nginx-debug  logs when trying to add an attachment higher than 1MB:

````markdown
```
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http2 request line: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload HTTP/2.0"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 generic phase: 0
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 rewrite phase: 1
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.9"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $admin
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.7:11334"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $antispam
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.10"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $webmail
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.2:5232"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $webdav
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script var
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http map started
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script var: "https"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http map: "" "https"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script var: "https"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "http"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script equal
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script equal: no
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script if
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script if: false
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: "/"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: "internal"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: "webmail"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: "/sso.php"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: ~ "^/(sso|static)/"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: ~ "^/.well-known/(carddav|caldav)"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 using configuration "/webmail"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http cl:5929784 max:58388608
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 rewrite phase: 3
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script regex: "^(/webmail)$"
front_1      | 2022/01/07 09:24:58 [notice] 10#10: *3 "^(/webmail)$" does not match "/webmail/", client: 82.66.114.154, server: , request: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload HTTP/2.0", host: "bhs.willo.fr", referrer: "https://bhs.willo.fr/webmail/?_task=mail&_action=compose&_id=108306885061d806d8291b1"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script regex: "^/webmail/(.*)"
front_1      | 2022/01/07 09:24:58 [notice] 10#10: *3 "^/webmail/(.*)" matches "/webmail/", client: 82.66.114.154, server: , request: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload HTTP/2.0", host: "bhs.willo.fr", referrer: "https://bhs.willo.fr/webmail/?_task=mail&_action=compose&_id=108306885061d806d8291b1"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script copy: "/"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script capture: ""
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script regex end
front_1      | 2022/01/07 09:24:58 [notice] 10#10: *3 rewritten data: "/", args: "_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload", client: 82.66.114.154, server: , request: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload HTTP/2.0", host: "bhs.willo.fr", referrer: "https://bhs.willo.fr/webmail/?_task=mail&_action=compose&_id=108306885061d806d8291b1"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 post rewrite phase: 4
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 generic phase: 5
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 generic phase: 6
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 generic phase: 7
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 generic phase: 8
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 access phase: 9
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 access phase: 10
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 access phase: 11
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 auth request handler
front_1      | 82.66.114.154 - - [07/Jan/2022:09:24:58 +0000] "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload HTTP/2.0" 500 170 "https://bhs.willo.fr/webmail/?_task=mail&_action=compose&_id=108306885061d806d8291b1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 posix_memalign: 00007FF1DBC235F0:4096 @16
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http subrequest "/internal/auth/user?"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http posted request: "/internal/auth/user?"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 rewrite phase: 1
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.9"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $admin
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.7:11334"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $antispam
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.10"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $webmail
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "192.168.203.2:5232"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script set $webdav
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script var
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script var: "https"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script value: "http"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script equal
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script equal: no
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script if
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http script if: false
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: "/"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: "internal"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: ~ "^/(sso|static)/"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 test location: ~ "^/.well-known/(carddav|caldav)"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 using configuration "/internal"
front_1      | 2022/01/07 09:24:58 [debug] 10#10: *3 http cl:5929784 max:1048576
front_1      | 2022/01/07 09:24:58 [error] 10#10: *3 client intended to send too large body: 5929784 bytes, client: 82.66.114.154, server: , request: "POST /webmail/?_task=mail&_remote=1&_from=compose&_id=108306885061d806d8291b1&_uploadid=upload1641547497671&_action=upload HTTP/2.0", subrequest: "/internal/auth/user", host: "bhs.willo.fr", referrer: "https://bhs.willo.fr/webmail/?_task=mail&_action=compose&_id=108306885061d806d8291b1"
```
````

We can see the different steps:

1. first POST trigger /webmail configuration where rewrite takes place and client_max_body_size is set to 58388608
2. second POST match /internal configuration because of http subrequest "/internal/auth/user?" where client_max_body_size is set to 1048576 (1MB) 
3. Then fail because of step 2

Any idea how to address this ?

**Review by ghostwheel42 — APPROVED** [review]
lgtm

**Comment by marioja** [comment]
I just did docker-compose pull && docker-compose up -d and checked the ngins.conf in the front container and it contained the change around line 87 to set the client max size limit.  After I restart the container I still get the error (I truncated the message at the end and replaced with 3 dots):

`webmail_1    | 2022/01/25 21:45:44 [error] 14#14: *62 client intended to send too large body: 5459886 bytes, client: 192.168.203.2, server: , request: "POST /?/Upload/&q[]=/_MF2G49DIEBeacMe...`

What is happening?

**Comment by marioja** [comment]
I figured out what is happening.  The error occurs in the webmail container which uses the default client_max_body_size of 1m in the /etc/nginx/nginx.conf.  I do not know how to modify /webmails/rainloop/config/nginx-rainloop.conf to override client_max_body_size to use the MESSAGE_SIZE_LIMIT variable.

As a quick test, I changed the client_max_body_size value to 50m, did a docker-compose restart webmail and tested and it works.

**Comment by marioja** [comment]
@ghostwheel42 @nextgens Are my comments on this pull request sufficient to get this fixed by someone more knowledgeable than me or do I need to create a new issue?  I would do a pull request but as I mentioned:

1. I have know idea who the substitution works in front's nginx.conf file.  I looked at nginx doc and google and could not figure it out.
2. I don't know how to replicate this in nginx-rainloop.conf because I don't know if the same substitution takes place (given that I do not see any in the file) and I do not know if adding it in the file would override the value in /etc/nginx/nginx.conf.

**Comment by audioscavenger** [comment]
> I figured out what is happening. The error occurs in the webmail container which uses the default client_max_body_size of 1m in the /etc/nginx/nginx.conf. I do not know how to modify /webmails/rainloop/config/nginx-rainloop.conf to override client_max_body_size to use the MESSAGE_SIZE_LIMIT variable.
> 
> As a quick test, I changed the client_max_body_size value to 50m, did a docker-compose restart webmail and tested and it works.

this is fixed here https://github.com/Mailu/Mailu/pull/2187
just need to attach the 287.bugfix to the request which i don't know how to do
do not add MESSAGE_SIZE_LIMIT in webmail container, this limit is handled by the front

**Comment by marioja** [comment]
> > I figured out what is happening. The error occurs in the webmail container which uses the default client_max_body_size of 1m in the /etc/nginx/nginx.conf. I do not know how to modify /webmails/rainloop/config/nginx-rainloop.conf to override client_max_body_size to use the MESSAGE_SIZE_LIMIT variable.
> > As a quick test, I changed the client_max_body_size value to 50m, did a docker-compose restart webmail and tested and it works.
> 
> this is fixed here #2187 just need to attach the 287.bugfix to the request which i don't know how to do do not add MESSAGE_SIZE_LIMIT in webmail container, this limit is handled by the front

@audioscavenger I will look at the pull request for #2187.  However, if the pull request only modifies the front container nginx configuration, this will not be fixed as the /etc/nginx/nginx.conf in the webmail container will take effect when the front sends it to the webmail container.

**Comment by audioscavenger** [comment]
> > > I figured out what is happening. The error occurs in the webmail container which uses the default client_max_body_size of 1m in the /etc/nginx/nginx.conf. I do not know how to modify /webmails/rainloop/config/nginx-rainloop.conf to override client_max_body_size to use the MESSAGE_SIZE_LIMIT variable.
> > > As a quick test, I changed the client_max_body_size value to 50m, did a docker-compose restart webmail and tested and it works.
> > 
> > 
> > this is fixed here #2187 just need to attach the 287.bugfix to the request which i don't know how to do do not add MESSAGE_SIZE_LIMIT in webmail container, this limit is handled by the front
> 
> @audioscavenger I will look at the pull request for #2187. However, if the pull request only modifies the front container nginx configuration, this will not be fixed as the /etc/nginx/nginx.conf in the webmail container will take effect when the front sends it to the webmail container.

#2187 has been updated with 
- bugfix for both rainloop and nginx front
- documentation update for configuration.rst stating that MESSAGE_SIZE_LIMIT=0 is now possible albeit discouraged

**Pull request merged**
