### PR TITLE
Use MySQL DB

### PR DESCRIPTION
**Pull request by adi90x**
Hello, 

I am not really good in python, but I successfully setup everything to work with a MariaDB container ! 
Everything default to sqlite as it is now , so no incompatibility !
Add a little documentation and may do more if interested !
Last point I will work out is to create a SQL dump from the admin interface ( need to figure out how Flask work ! )

Do not hesitate if you have any problem with this to be merge !

Regards

### CODE REVIEW

**Comment by kaiyou** [comment]
I am really not comfortable with merging this in master as I know I might use it as an excuse to not implement anything more flexible.

I might however, agree to maintain it as an officiallish separated branch that we would keep up to date with master. What do you think?

**Comment by adi90x** [comment]
Could make sense ! 
Tbh , this can be use as a base for other DB , I can even do something for Postgres DB if anyone interested ... However, it would be really complicated to implement something incompatible with postfix & dovecot for user request !
Btw , do you have a quick sheets of how to add a new page to the admin interface ? Would love to be able to create a SQL dump from the admin page , and I am struggling to understand how it work ( python if definitely not for me :)

**Comment by adi90x** [comment]
Ok , I have look a little bit more into the postfix/dovecot auth against the admin container.
One possible way could be : 
Postfix auth against Imap server ( Dovecot ) and Dovecot against a LUA script 
[This is part of the idea (in french sorry)](https://wiki.auf.org/wikiteki/Postfix/Authentification)

**Comment by kaiyou** [comment]
Authentication is not the issue really, it is performed by the frontend and shall remain that way (for later TLS based authentication among other reasons).

What's more tricky is maps and dictionaries, as stated in the issue.

**Comment by kaiyou** [comment]
The best way to help with this currently would be to help solving #420, which tackles down the dependency to any database in postfix or dovecot and rely on api calls instead.

Branch feat-abstract-db is doing just that and needs lots of testing. Currently IMAP should be working fine but anyone trying it out and reporting bugs would be more than welcome. I will try and publish the SMTP part next week.

**Comment by rakshith-ravi** [comment]
I can get you a VPS hosted with AWS or DigitalOcean from my company for free, and give you the credentials to it. Would something like that help you?

**Comment by kaiyou** [comment]
Not really, but thanks a lot :) the tedious part is actually running the tests, starting said branch and finding corner cases.

**Comment by rakshith-ravi** [comment]
Alright then. I'll set something up tomorrow (it's late in the night for me here), try sending out some emails, run it across mail-tester.com and let you know how it goes. My only question now is, say something went wrong: what log files should I provide you with in order to give you a good idea of what went wrong?

**Comment by kaiyou** [comment]
For now, sending messages will not work, maybe try accessing mailboxes, save drafts, move them around, play with quota, etc. Logs from the IMAP and front container should be helpful.

**Comment by kaiyou** [comment]
Good news, based on #612 I was just able to run a working Mailu instance backed by MySQL. Once it is merged, I hope I will be able to publish this in a couple days.

**Pull request closed without merging**
