### PR TITLE
Feature: switch CI/CD from build to buildx

### LINKED ISSUE #1200: Arm32v6/7 or Arm64v8 for docker?
Is it possible to use an arm machine for mailu?  I've looked through the tags and there doesn't seem to be a specific arm tag, and I can't see if a manifest has been made.

If not, are there build docker instructions so I could build the images myself?

### LINKED ISSUE #1830: Increasing the speed of our CI/CD setup
To break off one part of https://github.com/Mailu/Mailu/issues/1828 into a separate ticket:

> 2: Future topics for CI/CD
> Last project meeting someone mentioned these topics. I think these should be discussed and tackled once we have switched to a new CI/CD provider. Possibly we could already do this when switching, but I think it takes time to make a proper decision.
> 
> 2.1: Testing, can this be reduced? Solve long build times.
> Currently a build takes takes ~30 minutes on travis. The main reason is that there are many tests. We need to thoroughly check if we really want to perform all the tests that are done currently. For this we must document what component/functionality each test tests. After that we can make an informed decision if and what can be changed. Of course it is vital that all components are still tested.
> 
> Personally I think we should first check how long a build takes on the new CI/CD pipeline and then decide if this is too long. For me 20-30 minutes is already acceptable. What max build time acceptable for you?

I think a good step forward would be for us to try and run these steps locally and understand what is taking a long time. We can use this ticket to gather our tips & tricks for what could be done to speed things up. Typically this is some parts what you are trying to achieve and other parts knowing how to hack your CI system to cache/reduce build time/etc. So, we still need to crack https://github.com/Mailu/Mailu/issues/1828.

### LINKED ISSUE #2383: Proposal for simplifying CI file
Hi
Looking at the CI file, I'm a bit puzzled of all these repetitions for building all the environment.
Why not using the much more easy way of jobs output as described here: https://www.macstadium.com/blog/sharing-variables-between-jobs-in-github-actions
This would save hundreds of lines in the CI file, make it much more maintainable and understandable.
If you're interested in that, I can try to do a PR...

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?

Feature and enhancement

## What does this PR do?

Switch from docker build to buildx for CI/CD.
    - The main workflow file has been optimised and simplified.
    - Images are built in parallel when building locally resulting in much faster build times.
    - The github action workflow is about 50% faster.
    - Arm images are built as well. These images are not tested due to restrictions of github actions (no arm runners). The tags of the images have -arm appended to it. The arm images are built on merge on master and release branch (x.y). They do not influence the normal CI/CD workflow used for bors (for PR) and real releases (merge on master and branch x.y for x86_64). 
    - Arm images (and normal x86_64 images) can also be built locally.
    - Reusable workflow is introduced for building, testing and deploying the images. This allows the workflow to be reused for other purposes in the future.
    - Workflow can be manually triggered. This allows forked Mailu projects to also use the workflow for building images.

The main workflow makes use of github actions cache to store the cache layer. This layer is used to quickly rebuilt the images in the testing step and deploy step.

Unfortunately the building the arm images fails sometimes due to timeouts. Sometimes the connection to github actions cache is very slow. Restarting the workflow from the last failed step resolves this. I have not observed this with the normal build.

Just as previous time, you can use a forked project for testing the changes (https://github.com/Diman0/Mailu_Fork). You should still have owner access. I have created branch 1.11 for testing. You can see I already push 4 times to branch 1.11 (current version is 1.11.3).

### Related issue(s)
- Mention an issue like: #001
- closes #2383 
- closes #1830
- closes #1200

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
Just as previous time, you can use a forked project for testing the changes (https://github.com/Diman0/Mailu_Fork). You should still have owner access. I have created branch 1.11 for testing. You can see I already push 4 times to branch 1.11 (current version is 1.11.3).

**Comment by Diman0** [comment]
I forgot to whitelist the newly introduced actions. All actions must be whitelisted in the settings of the Mailu project. I bet bors must timeout before I can try again.

bors try

**Comment by Diman0** [comment]
bors cancel

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
bors try-

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
Bors try

**Review by nextgens — APPROVED** [review]
LGTM

**Pull request merged**
