### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

documentation

## What does this PR do?

- Run aspell
- Commit an updated network diagram

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
bors try-

**Comment by nextgens** [comment]
I don't get it, it's missing a commit that's on the branch:

```
commit 6f969fd53979546f54a1a58161c297453376a467 (HEAD -> doc, origin/doc)
Author: Florent Daigniere <nextgens@freenetproject.org>
Date:   Fri Oct 20 09:58:22 2023 +0200

    Fix CI

diff --git a/docs/faq.rst b/docs/faq.rst
index cca0b6b6..fabf11aa 100644
--- a/docs/faq.rst
+++ b/docs/faq.rst
@@ -193,7 +193,7 @@ This means it can be scaled horizontally. For more information, refer to :ref:`k
 *Issue reference:* `165`_, `520`_.
 
 How to achieve HA / fail-over?
-`````````````````````````````
+``````````````````````````````
 
 The mailboxes and databases for Mailu are kept on the host filesystem under ``$ROOT/``.
 For making the **storage** highly available, all sorts of techniques can be used:
@@ -474,7 +474,7 @@ Re-starting the smtp container will be required for changes to take effect.
 .. _`2213`: https://github.com/Mailu/Mailu/issues/2213
 
 My emails are getting deferred, what can I do?
-`````````````````````````````````````````````
+``````````````````````````````````````````````
 
 Emails are asynchronous and it's not abnormal for them to be defered sometimes. That being said, Mailu enforces secure connections where possible using DANE and MTA-STS, both of which have the potential to delay indefinitely delivery if something is misconfigured.
 
```

**Comment by nextgens** [comment]
@mergify rebase

**Comment by nextgens** [comment]
I'll close/reopen this

**Pull request closed without merging**
