### PR TITLE
Added SOLR support

### PR DESCRIPTION
**Pull request by ajgon**
## What type of PR?

Feature

## What does this PR do?
Adds support for full text search via SOLR to dovecot (imap).

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

PS. changelog guide is 404 😏

### CODE REVIEW

**Comment by ajgon** [comment]
bors retry

**Comment by der-eismann** [comment]
Can you also run this with solr 8?

**Comment by kaiyou** [comment]
We decided in #1176 that we were going to go with ES instead, and not have too many options to maintain until one of them is mastered.

**Comment by muhlemmer** [comment]
@kaiyou should this be closed?

**Comment by Nebukadneza** [comment]
As we took in xapian recently, and this is quite stale / would need a batch of rebasing, i’m with @muhlemmer for closing.

@ajgon — sorry for that, and thank you a lot for your contribution, which served well as a discussion-base to bring any FTS into mailu again!

**Comment by ajgon** [comment]
@Nebukadneza No worries, actually it's for the best. I used this setup successfully, for the past 8 months, but eventually have to kill it recently - because JAVA was unsatisfied daemon eating my CPU cycles like crazy (and keeping rig temperatures high). So double thumbs up for xapian, can't wait to see it in action!

**Pull request closed without merging**
