### PR TITLE
Create README.md for kubernetes

### PR DESCRIPTION
**Pull request by briantopping**
I spent a lot of time working on `stable` before realizing it's, well, not stable...

### CODE REVIEW

**Comment by briantopping** [comment]
I think it would be better to just delete the folder called `stable` and move the contents of the `1.6` folder to that root. It already has a very good `README.md`. WDYT?

**Comment by muhlemmer** [comment]
Putting @hacor and @consideRatio I'm CC. They are involved in Kubernetes. It is probably better to discuss with them.

I just did the review of this PR ;)

**Comment by briantopping** [comment]
Great, thanks! I'm not partial to a solution or doing the commit, just trying to reflect back with what I see and how I can help the next person be delighted with the experience!

**Comment by hacor** [comment]
@briantopping Indeed the current `stable` version of kubernetes is not yet useable for production. I think it's better to wait for PR #576 to finish before using Mailu on Kubernetes.
Currently we're all reviewing/testing the current PR to be as stable as possible before publishing

**Comment by briantopping** [comment]
Thank you @hacor, I will join you on #576!

**Pull request closed without merging**
