### PR TITLE
Upgrade to alpine 3.16.2

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

bug-fix

## What does this PR do?

This may fix the build issues on arm (troubles building cryptography)

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Review by Diman0 — DISMISSED** [review]
lgtm. This also fixed the issue when building locally.

**Comment by nextgens** [comment]
bors try

**Review by ghostwheel42 — DISMISSED** [review]

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
The last run has passed after getting it to retry

**Review by Diman0 — APPROVED** [review]

**Pull request merged**
