### PR TITLE
Handle IPv6 resolvers correctly

### PR DESCRIPTION
**Pull request by TheEnbyperor**
## What type of PR?
Bug fix

## What does this PR do?
NGINX front container currently does not handle IPv6 resolver addresses correctly, this PR fixes this.

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
Can you provide an example of resolv.conf that the current code fails to parse please? I don't understand what the proposed change does.

**Comment by TheEnbyperor** [comment]
With a `resolv.conf` such as
```
nameserver 2a0d:1a40:7900::1
```
which results in the following in the `nginx.conf` file
```
resolver 2a0d:1a40:7900::1 valid=30s;
```

NGINX tries to parse this as a hostname an port, the correct syntax is as follows
```
resolver [2a0d:1a40:7900::1] valid=30s;
```

**Comment by nextgens** [comment]
Okay now I understand what this does. Let's try to do with without any additional module; what about something like this instead?

```
resolver = content[content.index("nameserver") + 1]
args['RESOLVER'] = '[{}]'.format(resolver) if ':' in resolver else resolver
```

Can you please create a towncrier/newsfragment entry to describe the change too?

**Comment by ghostwheel42** [comment]
Will be fixed via  #2421

**Pull request closed without merging**
