### PR TITLE
Added carddav-plugin for roundcube webmail

### LINKED ISSUE #1230: CardDAV/CalDAV intergration with Roundcube
I've noticed that Mailu 1.7 has radicale and roundcube intergrated, and I know thers is a plugin is quite popular in roundcube offcial plugin repository call "roundcube/carddav".
It will be very good to see them works together so the webmail and the mail client will be able to have the same address book.

### PR DESCRIPTION
**Pull request by sholl**
## Feature

This PR enables the carddav contacts plugin for integration remote contact-repositories based on CardDAV.

## What does this PR do?

This PR enables the carddav contacts plugin for integration remote contact-repositories based on CardDAV.

### Related issue(s)
- Related #1230, at least for CardDAV.

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly (not needed since the plugins of webmail is not mentioned in the docs.)
- [x] Changelog-entry added

### CODE REVIEW

**Comment by sholl** [comment]
@kaiyou, are you expecting a rework of the PR based on your suggestions or are you going to merge it into master as is?

**Comment by kaiyou** [comment]
My comment was about ideas for further work, but I approve this PR as is. I was expecting someone else to review, @Nebukadneza or @hoellen maybe?

**Comment by sholl** [comment]
any news on merging this PR in master? I would love to include the adressbooks in roundcube for my users in the near future. TIA.

**Comment by JulesTriomphe** [comment]
Any news on when this PR might be merged into master ? I would love to use the carddav plugin too

**Comment by muhlemmer** [comment]
Looks good to me. I will do a test this days.

I've reworded the text of your PR comment @sholl, as the original string of "partial resolves #xxx" would actually close the issue on merge.

**Comment by sholl** [comment]
> Looks good to me. I will do a test this days.
> 
> I've reworded the text of your PR comment @sholl, as the original string of "partial resolves #xxx" would actually close the issue on merge.

@muhlemmer, I am perfectly fine with your rewording.

**Pull request merged**
