### PR TITLE
Implement a start date filter for autoreply, fixes #362

### LINKED ISSUE #362: Vocation: fields start
I have requests from customers who would like to put their vocations in advance. In fact, can we put a start field in vocation ?

### PR DESCRIPTION
**Pull request by kaiyou**
This replaces #613

### CODE REVIEW

**Comment by hoellen** [comment]
After merging #667 there is a merge conflict which has to be resolved first.

**Comment by kaiyou** [comment]
Quick question: how did you push commits that got included in this PR?

**Comment by muhlemmer** [comment]
I know there is an option when opening a PR to allow people with write access to do edits. But this only works directly from the web interface.

There is this pen icon in the top right corner of every diff. Also, if there is a merge conflict GitHub shows a "solve merge conflict" button and allows you to do in the web editor.

On October 20, 2018 11:15:40 AM GMT+03:00, kaiyou <notifications@github.com> wrote:
>Quick question: how did you push commits that got included in this PR?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/pull/665#issuecomment-431559835

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hoellen** [comment]
Hopefully it was OK, that I pushed that commit to your PR. You can do it also with the command line (not only web interface). If there is a merge conflict, GitHub gives you a small hint how to do it.

**Comment by HorayNarea** [comment]
> I know there is an option when opening a PR to allow people with write access to do edits. But this only works directly from the web interface. There is this pen icon in the top right corner of every diff. Also, if there is a merge conflict GitHub shows a "solve merge conflict" button and allows you to do in the web editor.

You can also checkout the PR locally and simply commit/push to it like any other branch: https://help.github.com/articles/checking-out-pull-requests-locally/

**Pull request merged**
