### PR TITLE
Update start.py to fix the resolver test

### PR DESCRIPTION
**Pull request by shing6326**
Use method resolve instead of query to fix the resolver test

## What type of PR?

bug-fix

### Related issue(s)
- Mention an issue like: #001
- Auto close an issue like: closes #001

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
I don't understand why this would be required... We actually want the resolver to go through the full search expansion to ensure that the records returned are consistent.

We don't care about performance since this is run only once at startup.

**Comment by shing6326** [comment]
Hi,
I am using the latest mailu helm charts and found that the mailadmin cannot start because the service tries to test the A records of example.org.<mydomain.com> and it is not resolvable. I have to write the example.org.<mydomain.com> to workaround the problem, so the pull request fixes this problem.
Thanks

**Comment by nextgens** [comment]
If you change resolver.query() to resolver.resolve(), does it fix it?

**Comment by nextgens** [comment]
Please try something like the following:

```
docker exec -ti emails_admin_1 /usr/bin/env python3
import dns.resolver
resolver = dns.resolver.Resolver()
resolver.use_edns(0, 0, 1232)
resolver.flags = dns.flags.AD | dns.flags.RD
resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10, search=True, raise_on_no_answer=False)
resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
```

I have tested it here and do **not** get any exception (even when I have a domain or search directive in /etc/resolv.conf)

**Comment by shing6326** [comment]
I just tried to enter the pod, copy and modify the start.py and the problem is reproduced.
BTW I have replaced my domain name into `abc.com`

```
$ k exec -it mailu-admin-7c7b46b64-4d57c -- bash
bash-5.1# cat /tmp/start.py
#!/usr/bin/python3

import os
import logging as log
import sys

log.basicConfig(stream=sys.stderr, level=os.environ.get("LOG_LEVEL", "INFO"))

#os.system("flask mailu advertise")
#os.system("flask db upgrade")

account = os.environ.get("INITIAL_ADMIN_ACCOUNT")
domain = os.environ.get("INITIAL_ADMIN_DOMAIN")
password = os.environ.get("INITIAL_ADMIN_PW")

#if account is not None and domain is not None and password is not None:
#    mode = os.environ.get("INITIAL_ADMIN_MODE", default="ifmissing")
#    log.info("Creating initial admin accout %s@%s with mode %s",account,domain,mode)
#    os.system("flask mailu admin %s %s '%s' --mode %s" % (account, domain, password, mode))

def test_DNS():
    import dns.resolver
    import dns.exception
    import dns.flags
    import dns.rdtypes
    import dns.rdatatype
    import dns.rdataclass
    import time
    # DNS stub configured to do DNSSEC enabled queries
    resolver = dns.resolver.Resolver()
    resolver.use_edns(0, 0, 1232)
    resolver.flags = dns.flags.AD | dns.flags.RD
    nameservers = resolver.nameservers
    for ns in nameservers:
        resolver.nameservers=[ns]
        while True:
            try:
                result = resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
            except Exception as e:
                log.critical("Your DNS resolver at %s is not working (%s). Please use another resolver or enable unbound via https://setup.mailu.io.", ns, e);
            else:
                if result.response.flags & dns.flags.AD:
                    break
                log.critical("Your DNS resolver at %s isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.", ns)
            time.sleep(5)

test_DNS()

start_command="".join([
    "gunicorn --threads ", str(os.cpu_count()),
    " -b :80 ",
    "--access-logfile - " if (log.root.level<=log.INFO) else "",
    "--error-logfile - ",
    "--preload ",
    "'mailu:create_app()'"])

#os.system(start_command)
bash-5.1# /tmp/start.py
/tmp/start.py:38: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  result = resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
CRITICAL:root:Your DNS resolver at 10.43.0.10 is not working (The DNS response does not contain an answer to the question: example.org.abc.com. IN A). Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 10.43.0.10 is not working (The DNS response does not contain an answer to the question: example.org.abc.com. IN A). Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 10.43.0.10 is not working (The DNS response does not contain an answer to the question: example.org.abc.com. IN A). Please use another resolver or enable unbound via https://setup.mailu.io.
^CTraceback (most recent call last):
  File "/tmp/start.py", line 47, in <module>
    test_DNS()
  File "/tmp/start.py", line 45, in test_DNS
    time.sleep(5)
KeyboardInterrupt
```

**Comment by shing6326** [comment]
btw your sample code also not work in my kubernetes env
```
bash-5.1# cat > /tmp/2.py
import dns.resolver
resolver = dns.resolver.Resolver()
resolver.use_edns(0, 0, 1232)
resolver.flags = dns.flags.AD | dns.flags.RD
resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10, search=True, raise_on_no_answer=False)
resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
^C
bash-5.1# python3 /tmp/2.py
/tmp/2.py:7: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
Traceback (most recent call last):
  File "/tmp/2.py", line 7, in <module>
    resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
  File "/usr/lib/python3.9/site-packages/dns/resolver.py", line 1222, in query
    return self.resolve(qname, rdtype, rdclass, tcp, source,
  File "/usr/lib/python3.9/site-packages/dns/resolver.py", line 1202, in resolve
    (answer, done) = resolution.query_result(response, None)
  File "/usr/lib/python3.9/site-packages/dns/resolver.py", line 674, in query_result
    raise NoAnswer(response=answer.response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: example.org.abc.com. IN A
```

**Comment by nextgens** [comment]
Can you try running it interractively please? Just invoke python3 instead of bash and paste the lines one by one (so that we can see which exceptions are thrown for the last three lines)

**Comment by shing6326** [comment]
it should be the last line
```
bash-5.1# python3
Python 3.9.5 (default, Nov 24 2021, 21:19:13)
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dns.resolver
lver = dns.resolver.Resolver()
resolver.use_edns(0, 0, 1232)
resolver.flags = dns.flags.AD | dns.flags.RD
resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10, search=True, raise_on_no_answer=False)
>>> resolver = dns.resolver.Resolver()
>>> resolver.use_edns(0, 0, 1232)
>>> resolver.flags = dns.flags.AD | dns.flags.RD
>>> resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10, search=True, raise_on_no_answer=False)
<dns.resolver.Answer object at 0x7f4b9c57c880>
>>> resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
<dns.resolver.Answer object at 0x7f4b9c57c6a0>
>>> resolver.query('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
<stdin>:1: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/dns/resolver.py", line 1222, in query
    return self.resolve(qname, rdtype, rdclass, tcp, source,
  File "/usr/lib/python3.9/site-packages/dns/resolver.py", line 1202, in resolve
    (answer, done) = resolution.query_result(response, None)
  File "/usr/lib/python3.9/site-packages/dns/resolver.py", line 674, in query_result
    raise NoAnswer(response=answer.response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: example.org.abc.com. IN A
```

**Comment by nextgens** [comment]
Okay so switching to the newer API solves the problem; Are you happy to revise your PR?

```
resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
```

Is probably what we want

**Comment by shing6326** [comment]
I am more than happy to revise the PR. The code also works in my environment. Thanks a lot

**Review by nextgens — APPROVED** [review]
LGTM

**Review by ghostwheel42 — APPROVED** [review]
Lgtm

**Pull request merged**
