### PR TITLE
Add kubernetes NGINX ingress and Mailu resource config

### PR DESCRIPTION
**Pull request by t3hmrman**
Hey all,

Really late, but I finally got around to making a PR for the Kubernetes configuration that's been working for me. 

I wasn't able to get the Services Status page working, but everything else works great.

### CODE REVIEW

**Comment by kaiyou** [comment]
Well, this is amazing :) we could add a `docs` directory to the project to migrate the markdown documentation, and mostly integration with multiple environments.

How well do you think this will hold if we replace the current frontend with a more complete `nginx`, in charge of updating certificates and terminating all TLS, including STARTTLS for emails?

**Comment by kaiyou** [comment]
My general understanding if you look at branch `refactor-nginx`, is that we could simply use `cert` and drop the certificate in the `nginx` container :)

**Comment by t3hmrman** [comment]
Hey @kaiyou sure I can definitely add a `docs` directory. I'm sorry I can't say I'm too familiar with the Mailu codebase so I'm not sure what else should go in with that directory... Should I just put these two files there only?

Oh, that would be even better -- so I'll do two things:
1. Add a `docs` directory (I'd love some guidance on the structure for this, should I add a `docs/kubernetes` folder, and a `README.md` inside there?

2. Use the `cert` image currently being worked on in `refactor-nginx` -- I could rebase to `refactor-nginx` if this will depend on that work

**Comment by kaiyou** [comment]
I was actually just writing some ideas about a `docs` directory for documentation. But sure, point (1) is exactly how I woudl have structured it. It would be perfect and I could then include most of the adminstration docs from the wiki there.

I did not understand point (2), do you currently work based on `refactor-nginx`? If so, I find it weird that your postfix and Dovecot container still have direct port attachments. If not, it is just find, we shall update these later of course, but one step at a time :)

**Comment by t3hmrman** [comment]
OK, I will go ahead and do (1)!

For (2), I was thinking I'd change my work to match the stuff in `refactor-nginx`, but maybe I'll just do this first, and update later.

**Comment by t3hmrman** [comment]
hey @kaiyou , what do you think? Is there a way to get wiki's to go off files in the repo? All I can see is [the .wiki.git](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/) repo that gets created by Github...

**Comment by kaiyou** [comment]
This looks just perfect :) regarding the wiki, I will spend sometime this week-end to integrate user documentations in there.

Thank you!

**Comment by t3hmrman** [comment]
No problem, thank YOU for maintaining this awesome project! :D

**Comment by pesimon** [comment]
Really cool. Thanks @t3hmrman . With those k8s ressources in place we could think about creating and adding a helm chart to https://github.com/kubernetes/charts . I'm happy to help, if time permits.

**Comment by tsutsarin** [comment]
I'm very excited about helm chart idea!
I could also help with packaging into helm chart (again, if time permits)

**Comment by t3hmrman** [comment]
hey @pesimon / @tsutsarin ,

I actually haven't used Helm at all yet, I'll have to lean on your knowledge for that! I've been justing just vanilla Kubernetes for the last few months trying to make sure I understood it a reasonable amount. Starting to read up on helm now though.

**Pull request merged**
