### PR TITLE
This sets the max attachment size in roundcube

### PR DESCRIPTION
**Pull request by gregf**
I used the php.ini from the rainloop folder, so they are both set to
25MB.

### CODE REVIEW

**Comment by kaiyou** [comment]
This looks good, except the file name once copied :)

**Comment by HorayNarea** [comment]
Shouldn't the roundcube upload size be linked to the postfix maximum mail size?

**Comment by kaiyou** [comment]
Not necessarily, it should not be any higher, but a lower limit does not bother me.

**Comment by gregf** [comment]
Should be sorted now, sorry for the delay

**Comment by kaiyou** [comment]
Perfect, no worries about the delay and thank you! Feel free to add your name to the AUTHORS file anytime.

**Pull request merged**
