### PR TITLE
Update fetchmail.py

### PR DESCRIPTION
**Pull request by rueckix**
## What type of PR?
Typo in fetchmail configuration flag sslproto

## What does this PR do?
Change sslproto=AUTO to sslproto=auto 

### Related issue(s)
#808 

## Prerequistes
None

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: place entry in the [changelog](CHANGELOG.md), under the latest un-released version.

### CODE REVIEW

**Comment by Nebukadneza** [comment]
Sorry for the late reaction! Does this indeed fix the problem for you? In my test, and apparently also others in the matrix chat, `fetchmail` whines about `auto` as well as `AUTO`, which is kind of a bummer. The underlying problem is also that fetchmail hasn’t gotten a release in ~5 years(?) …

**Comment by rueckix** [comment]
Apparently, it does not solve the issue.  Never trust the man page.. it seems. I looked into the fetchmail code and indeed, this does not appear to make a difference on the latest official release. Glad to see that newer releases are in the works. 

Checking this switch again, I am wondering if "AUTO" is a safe default choice. It makes fetchmail fall back to SSL23, which uses deprecated SSLv23 methods in OpenSSL.
(see https://gitlab.com/fetchmail/fetchmail/blob/RELEASE_6-3-26/socket.c#L928)

Same issue for 'ssl2' and `ssl3`.

The only safe option, from a security point of view, is `sslproto 'tls1'`

Opinions?

**Comment by muhlemmer** [comment]
TLS 1.0 is deprecated from June 30, 2018: https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.0.

Although, some "mayor" providers will still support it until march 2020. Mailu doesn't:
https://github.com/Mailu/Mailu/blob/effaaa90621b79ee3fd2c4c47ec4393ea381e66b/core/nginx/conf/tls.conf#L1

So setting `sslproto 'tls1'` might work in the cases of some of the "mayor" service providers like Google and some other non-security aware mail servers. But it won't work against Mailu or any other up-to-date server.

The opposite argument would be that currently Fetchmail doesn't work at all, and this setting would at least make it work in some cases. So to conclude, I'm indifferent in this matter. Maybe some other opinions from @Nebukadneza, @kaiyou or @HorayNarea?

**Comment by muhlemmer** [comment]
Fetchmail has our full attention and we'll try to fix it as soon as fetchmail allows us. For now this PR will be closed.

**Pull request closed without merging**
