### PR TITLE
Use redis 5 on k8s & add selector

### PR DESCRIPTION
**Pull request by der-eismann**
## What type of PR?
Enhancement

## What does this PR do?
This PR is updating Redis to version 5 in the kubernetes manifests. It is already used in the compose and swarm files, so I don't expect any incompatibilities. There is no necessary migration, you just can't go back.
In addition I added a selector to the manifest and applied a consistent formatting.

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by kaiyou** [comment]
Please, please do not reindent every line if it is unrelated to your change, as it makes the reviewing process harder. Looks good however :)

**Comment by der-eismann** [comment]
Sorry for the indent, I wanted to keep the format consistent. I'll remember this for the future!

**Comment by der-eismann** [comment]
Is there any other reviewer available?

**Comment by micw** [comment]
I tested the  redis 5 change this in my helm chart, works as expected. Selector is required for newer k8s, so that's good too.

**Comment by der-eismann** [comment]
Thanks for merging!

**Pull request merged**
