### PR TITLE
Build wheels only if we have to.

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

This massively speeds the CI up; We don't need to install a compiler and rebuild when we have wheels available... with this admin builds 4 times faster.

### Related issue(s)
- #1830

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by Diman0** [comment]
Wow. It builds really fast now!

**Comment by nextgens** [comment]
Yup. I think this is merge-able now. If we want to make it faster we'll have to look into why the tests are so slow :)

**Review by Diman0 — APPROVED** [review]
lgtm!

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors ping

**Comment by nextgens** [comment]
bors retry

**Review by Diman0 — APPROVED** [review]

**Comment by Diman0** [comment]
I dont get it. The test fails with the error
```
     deadline=datetime.now()+datetime.timedelta(minutes=timeout)
AttributeError: module 'datetime' has no attribute 'now'
```
It states that datetime has no attribute now, but you clearly specify that it is a method.

**Comment by Diman0** [comment]
Nvm. module datetime has the class datetime with the method now. Very confusing.

bors try

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
bors retry

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
If GHA cache does not act up, then it takes only ~7-8 minutes now. That is almost 3x faster than the old situation with CI.yml.
Let's do the other improvements (for dovecot and possible roundcube) in another PR.

**Review by Diman0 — APPROVED** [review]
lgtm

**Comment by Diman0** [comment]
bors retry

**Pull request merged**
