### PR TITLE
Preparations for 1.9 release

### LINKED ISSUE #1930: Discussion of 1.9 roadmap
As proposed in the last project meeting (#1582 (comment)), we are experimenting with a discussion driven model for determining the roadmap of the next release. This follows the existing practice of the succesful community run project Gitea (e.g go-gitea/gitea#14477).

During last meeting someone made the remark that with everything in the pipeline we already have sufficient work for a 1.9 release. I agree. We have this special situation due to the 1.8rc where we had a release candidate for over 7 months. This caused many PRs to be merged, but not included in 1.8. These are now waiting to be made available via a 1.9 release. This also caused a lot of already submitted PRs not be reviewed yet. We wanted to focus on getting 1.8 out of the door.

There are new PRs waiting for review for
- Updating the interface to AdminLTE3 #1800. This is not only a security update, but also adds a lot of functionality such as
  - a language selector
  - more modern look&feel of interface elements
  - filtering and column ordering for tables.
- Multiple PRs for increasing the overall security of mailu #1922, #1916, #1902. 
  - For these PRs we (I?) will also introduce a brand new security documentation page where you can find all documentation on what security measures are in place, how it works and how it can be tweaked. 
- updated polish translations #1751 and completely new Hebrew translation #1873.

We have already merged PRs on master for
- Completely new CLI configuration import/export which really exports/imports the complete mailu configuration database. With this it is possible to migrate the mailu config to another mailu instance. You can also use it to easily add new configuration (e.g. import users with specific settings) https://mailu.io/master/cli.html#config-export
- single sign on for webmail. Webmail uses the admin web interface for authenticating users
- various security related enhancements
- All other already merged PRs which were not included in 1.8. See all newsfragments for the details https://github.com/Mailu/Mailu/tree/master/towncrier/newsfragments

IMHO All those features together are sufficient to release a new version.

I suggest we review all open PRs and then check what issues really need to be included as well for 1.9 and include these on the roadmap. Examples are:
- I think a good example is the new SSO #1929. When you are redirected to the login page, it does not show that the login is for the webmail. You have the feeling that you are redirected to the wrong page. See the demo site for an example (https://test.mailu.io/webmail/). Of course this is not production worthy. 
- Incorrect documentation
  - E.g.the documentation on translations #1869. We have no weblate instance anymore for web-based translations. The documentation must be updated as it is incorrect now. You can only do translations manually with a tool such as poedit and send a PR for getting your new translation files merged .
  - documentation on development environment for the admin interface #1577. The faulty documentation should be removed or directly updated with the correct steps.

For small non-critical issues/features I suggest we do not put it on the roadmap, but simply offer anyone the chance to pick these up and submit a PR if they want it included. 

What are your thoughts? Please share your feedback.
Regardless the above wall of text, feel free to mention any feature/issue you would like included in 1.9.

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?

Preparations for 1.9 release.

## What does this PR do?
All changes required for the 1.9 release. This PR does not trigger the 1.9 release yet. For that we only have to create a 1.9 branch after this PR has been merged.

Please double check all the documentation. Feel free to directly commit to this branch any spelling errors you see.

After this is merged, I only have to create the 1.9 branch and update the infra project to release 1.9.

### Related issue(s)
- closes #1930

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
In docs/releases.rst (line 7) I do not have a lengthy explanation on what we did the last release. 
So `Mailu 1.9 is available now.` is sufficient for me. I'm not really good at writing lengthy stories. If you have any ideas to write more about the last period, feel free to extend it.

**Comment by Diman0** [comment]
bors try

**Comment by Erriez** [comment]
Note: The admin page generates error 404 after upgrade from `1.8` to `master` as the `admin/ui` URL has been changed. The old URL is cached by the browser, issue: https://github.com/Mailu/Mailu/issues/2114.

**Review by nextgens — APPROVED** [review]

**Review by nextgens — APPROVED** [review]

**Review by ghostwheel42 — APPROVED** [review]
Lgtm

**Pull request merged**
