### PR TITLE
Update antispam.rst

### PR DESCRIPTION
**Pull request by woj-tek**
## What type of PR?

documentation

## What does this PR do?

Change hostname of rspamd (`antispam` wasn't the one available in our k8s deployment) and add rspamc call to teach bayes filter with ham/spam.

### Related issue(s)
- https://github.com/Mailu/Mailu/issues/2442

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [-] In case of feature or enhancement: documentation updated accordingly
- [-] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
I am sorry but this isn't mergeable.

Please follow instructions from https://mailu.io/master/contributors/workflow.html#pr-workflow

1) It needs to be targeting master (and not 1.9)
2) the hostname is the right one, if it doesn't match on k8s, it's a problem that should be reported on https://github.com/Mailu/helm-charts/

**Comment by woj-tek** [comment]
> It needs to be targeting master (and not 1.9)

My bad - I clicked on "edit on GitHub" just after navigating to https://mailu.io/, which defaults to stable 1.9. I'll create propper one

> the hostname is the right one, if it doesn't match on k8s, it's a problem that should be reported on https://github.com/Mailu/helm-charts/

I digged a little bit more and it seems it's "by design" - Deployment and Service name is configured to be prefixed with configured mailu name (vide https://github.com/Mailu/helm-charts/blob/eccf0342c81609c9b770205eb12c02683396f93a/mailu/templates/rspamd.yaml#L12-L12 and https://github.com/Mailu/helm-charts/blob/eccf0342c81609c9b770205eb12c02683396f93a/mailu/templates/rspamd.yaml#L164-L164)

Keeping that in mind, would it be acceptable to mention in the documentation as a sidenote/comment, that in case of k8s deployment hostname may be different and it's recommendable to check it using `kubectl` command, and that by default it should be `mailu-rspamd`?

**Comment by nextgens** [comment]
I really think that it should be changed on the helm side of things...

Isn't it the hostname parameter that needs changing?
https://github.com/Mailu/helm-charts/blob/eccf0342c81609c9b770205eb12c02683396f93a/mailu/templates/rspamd.yaml#L37

IMHO it makes no sense for it to be different from what we use in docker-compose... if it is, it means that migrations from one to the other will result in lost history of the rspamd scans (as per https://github.com/Mailu/helm-charts/issues/95)

**Comment by woj-tek** [comment]
Done: https://github.com/Mailu/helm-charts/issues/189

**Pull request closed without merging**
