### PR TITLE
Kubernetes manifest update

### PR DESCRIPTION
**Pull request by hacor**
## What type of PR?

Enhancement

## What does this PR do?
It fixes the infinite redirect loops in Kubernetes Admin interface. 
The change is to add the complete uri string to the rewrite rule.
Updated antispam URL

### Related issue(s)
#1021

### CODE REVIEW

**Comment by blinkeye** [comment]
May I ask what you plan to do with this specific PR? You updated the K8s manifests to reference the 1.6 images, so, in the current state this would be a bugfix/hotfix of the 1.6 release branch. But then you starting point is wrong (because on the 1.6 release the manifests already reference the 1.6 images).

If, on the other hand (and what I assume) you intend to merge this PR to the master I would assume that you should not reference the 1.6 images  but the current development master images?

**Comment by kaiyou** [comment]
@micw, could you review this work and either provide some feedback or make sure that your helm chart builds on it.

I am not sure if we should keep both a chart and set of k8s configs, any advice?

**Comment by micw** [comment]
The changes here are very specific for nginx ingress controller and would eventually break others like traefik. Unfortunately I don't have nginx ingress (only traefik), so I cannot verify this.
What I can do is to test if this would still work on traefik (which btw. does not have the issue described here).

**Comment by kaiyou** [comment]
Any hint on the matter would be great. I'll try and test this tomorrow but I cannot promise anything.

**Comment by micw** [comment]
I tried to get this work on traefik too but I could not find a portable way. So it will either work with nginx ingress or with traefik ingress, so the solution is far from being optimal.

The best solution would be to have the admin service listening on /admin (and not on /). In this case, we would not require path rewriting and we can use standard ingress definitions.

**Comment by micw** [comment]
@hacor I have created PR https://github.com/Mailu/Mailu/pull/1117 which addresses this issue in a different way.  I have tested it using traefik ingress. Can you test it with nginx? A ready-to-use docker image is built at 

micwy/mailu-test-builds:admin--admin-ui-path

**Pull request closed without merging**
