### PR TITLE
Preparations for 1.8 release.

### LINKED ISSUE #1651: Announce mailu-postgres-image deprecation
In preparation for 1.8 release, according to #1582 , add a deprecation warning to the mailu-postgres-option in setup utility. Also make the "external" option the default one.

### LINKED ISSUE #1652: Remove setup stack "replicas" option
In preparation for 1.8-rc release, and according to #1582 , remove the "replicas" option from setup step 5 in the stack deployment option. Also add an additional notice that users should review their configuration by hand, as well as a big warning about "replicas prone to data-corruption" to the "experimental" box at the top of setup.
(note that replicas is just *currently* not supported.)

Note that if you know what you’re doing, replicas can be easily configured by hand.

Relates: #1222 #1224 #1637

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?
Preparation for release 1.8. 

## What does this PR do?
Preparation for release 1.8. 
See meeting notes for additional tasks that must still be done.

#issues
- Closes #1651 
- Closes #1652 

## To do
From our meeting notes, these are the last things we must still do before we can merge this PR.
Once you have done of these items, please let me know in a comment. I'll update it in the below  overview. 

### setup
- [x] Make sure both version 1.7 (still default) and 1.8 and master are options. (This is handled via infra project: setup/.env)
- [x] When selecting 1.8, add a message this is version is "only for testing". 
- [x] Make 1.7 the default version option. (Is handled via infra project: setup/.env )
- Replication
  - [x] Completely remove step 5 where you can set the replica count for docker-stack.
  - [x] Add additional warning to ´experimental' notice in setup for stack . "please check your config by hand. please think hard about replication". Using replication will lead to issues with the default docker-compose.yml en mailu.env. Manual post-configuration is required for using replica count higher than 1.
- PostgreSQL database selection
  - [x] Add a notice the shipped PostgreSQL is deprecated. It WILL be removed from Mailu 1.9. With the release of Mailu 1.9 we will offer a mechanism to migrate your data to another database management system.
  - [x] Make the external PostgreSQL database the default option.

### Docs
- [x] Finalize changelogs (Docs\Releases.rst)
- [x] Make 1.7 the default version (stable_version': '1.7', in docs\conf.py)

### General
- [x] Update mergify.yml with 1.8 version
- [x] Check for more forgotten version-containing files. If you find these, please update the [wiki](https://github.com/Mailu/Mailu/wiki/Release-workflow) with this information.

### CODE REVIEW

**Comment by Diman0** [comment]
For "When selecting 1.8, add a message this is version is "only for testing"." I suggest we introduce an environment variable stable_version. 
For each release we can set in infra/setup/.env what the stable version is. 
In "Mailu/setup/templates/wizard.html" we can add a check. If the selected version is not stable_version, then display the warning message that this version is for testing. This means that the 'test version' and master will always have  this additional warning. 
"Mailu/setup/server.py" must be modified to get the new environment variable and pass it on to the template page.

**Comment by Diman0** [comment]
> For "When selecting 1.8, add a message this is version is "only for testing"." I suggest we introduce an environment variable stable_version.
> For each release we can set in infra/setup/.env what the stable version is.
> In "Mailu/setup/templates/wizard.html" we can add a check. If the selected version is not stable_version, then display the warning message that this version is for testing. This means that the 'test version' and master will always have this additional warning.
> "Mailu/setup/server.py" must be modified to get the new environment variable and pass it on to the template page.

I have introduced a new environment variable stable_version for setup. When in setup, the selected version does not match the env variable stable_version, then the warning is displayed that this version is for testing only. The warning is displayed for the test version and master version. I have updated the PR for intfra to add this env variable to the docker-compose.yml file.

**Comment by Diman0** [comment]
I think it is ready now. The only thing someone else could do is double check If I missed any version-containing files. I could not find these. 
When merging this PR, we must immediately create a 1.8 branch and merge the PR for infra project to ensure mailu.io keeps functioning.

**Comment by Diman0** [comment]
bors try

**Comment by Nebukadneza** [comment]
Unanimously approved for merge in release-videoconf, so … merging it manually.

**Pull request merged**
