### PR TITLE
Add a sigterm handler to make docker stop go faster

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

- Add a sigterm handler to make ``docker stop`` go way faster
- Ensure we don't log requests to /ping in admin
- Fixup doc
- Upgrade WTForms to fix alias creation

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors retry

**Comment by nextgens** [comment]
bors retry

**Comment by Diman0** [comment]
bors try

**Review by Diman0 — APPROVED** [review]
lgtm

**Pull request merged**
