### PR TITLE
Feat/haproxy 1.9

### LINKED ISSUE #1472: PROXY Protocol support
Hello,

I'm trying to deploy Mailu behind a load balancer but it seems that Mailu doesn't support the PROXY Protocol.

Would it be feasible to add support for the PROXY Protocol?
From I can see the NGINX documentation allows switching to the PROXY Protocol: https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/ but I don't know if this can easily be implemented into Mailu.

### PR DESCRIPTION
**Pull request by hitech95**
## What type of PR?

Enhancement

### Related issue(s)
- Use traefik or any proxy for SSL termination: #1422
- Allow to have `front` behind a mail proxy (like another nginx instance) : closes #1472

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by hitech95** [comment]
bors try

**Comment by nextgens** [comment]
Thank you for your contribution.

Can you submit f55048df09946d128aa8cec88f9f3c0c5fb34361 on a separate PR to address #2296 please?

All PRs should be using master as a base branch... we will backport things from there if required.

**Comment by hitech95** [comment]
Hi,
yes this is a draft PR. on documentation there was no info about how you want to handle PRs.

Today I'll run more tests. (this night I might have found a bug), and I'll make a proper PR for that commit.

I'm also still working on the documentation for the changes.
I want to provide an example for traefik.

This patch is based on `1.9` do you prefere to have it based on `master`?

**Comment by hitech95** [comment]
@nextgens I have no idea on how to create the changelog tho...
I'll have to read the doc again... 😄

**Comment by hitech95** [comment]
See #2300

**Pull request closed without merging**
