### PR TITLE
Rollback to mysql-connector-python==8.0.29

### LINKED ISSUE #2553: admin container unable to start with MariaDB
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master-arm`

## Description

The admin container is unable to start when configured to use with mysql/MariaDB as the backend database. Although MariaDB is suppose to work, it is unable to connect to MariaDB (tested with version10.6.x and 10.10.x official dockerhub repo). 

Further investigation shows that a change in the python module `mysql-connector-python` from `8.0.29` to `8.0.30` broke this. The version of `mysql-connector-python` at the point of reporting is `8.0.31` and it is broken as well.

`Page 5` of https://downloads.mysql.com/docs/connector-python-relnotes-en.pdf might shed some light on the change.

Manually downgrading to `8.0.29` seems to work but I did not test for all functions.
## Replication Steps

1. create an external MariaDB from dockerhub. https://hub.docker.com/_/mariadb
2. Configure mailu to use MySQL as the database.
3. Start mailu using docker-compose.

## Observed behaviour

The admin docker was unable to start and healthcheck is unhealthy.

## Expected behaviour

The admin docker should start without errors.

## Logs

Looking at the logs, the following error was observed.

```
[2022-11-22 09:02:08,388] ERROR in app: Exception on /internal/rspamd/local_domains [GET]
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 320, in connect
    return _ConnectionFairy._checkout(self)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
    rec = pool._do_get()
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
    return _ConnectionRecord(self)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
    self.__connect()
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 677, in __connect
    with util.safe_reraise():
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/app/venv/lib/python3.10/site-packages/mysql/connector/pooling.py", line 287, in connect
    return MySQLConnection(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/mysql/connector/connection.py", line 137, in __init__
    self.connect(**kwargs)
  File "/app/venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1105, in connect
    self.config(**kwargs)
  File "/app/venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 516, in config
    self._charset_id = CharacterSet.get_charset_info(charset, collation)[0]
  File "/app/venv/lib/python3.10/site-packages/mysql/connector/constants.py", line 775, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/app/venv/lib/python3.10/site-packages/mysql/connector/constants.py", line 746, in get_default_collation
    raise ProgrammingError(f"Character set '{charset}' unsupported")
mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported
```

### PR DESCRIPTION
**Pull request by nextgens**
See #2553

## What type of PR?

bug-fix

## What does this PR do?

Rollback to mysql-connector-python==8.0.29

### Related issue(s)
- closes #2553 

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by ghostwheel42** [comment]
Hmm, no: You'd need to pin the version in the requirements-dev.txt if you'd like to stick with 8.0.29
But this will disallow future upgrades, which will probably make more problems in the future.

As far as I can see mariadb is != mysql now. So we probably need to add mariadb to the requirements.
And maybe use mariadb:// as connect string. I'll see if I can find a test environment for this.

**Comment by nextgens** [comment]
Hopefully they'll fix whatever the problem is upstream

**Comment by ghostwheel42** [comment]
Yes. This works:
```
>>> import sqlalchemy
>>> e=sqlalchemy.create_engine('mysql+mariadbconnector://mailu:mailu@212.7.160.242/mailu')
>>> e.connect()
<sqlalchemy.engine.base.Connection object at 0x72ced1e03eb0>
```

**Review by ghostwheel42 — APPROVED** [review]
Okay, lets do this for now to fix master.
We need to update the db module(s) like in my comment to fix this.

**Pull request merged**
