### PR TITLE
Fix hardcoded reference to admin container.

### LINKED ISSUE #1323: Hardcoded http://admin/ in fetchmail.py
I've tweaked ``docker-compose.yml`` so that all my containers related to ``mailu`` are prefixed, in order to avoid conflict with other containers I start alongside containers relted to ``mailu``.

However, the hardcode ``http://admin/...`` below causes failure in ``fetchmail``, since my container container is now named ``maily-admin`` in my docker-compose.yml, not ``admin`` as the code supposes it should be.

```
./services/fetchmail/fetchmail.py:47:    fetches = requests.get("http://admin/internal/fetch").json()
./services/fetchmail/fetchmail.py:85:            requests.post("http://admin/internal/fetch/{}".format(fetch["id"]),
```

### PR DESCRIPTION
**Pull request by frgomes**
## What type of PR?

big-fix

## What does this PR do?

Fixes a hardcoded reference to ``admin`` container which may or may not be called ``admin`` in reality, since the user may eventually to name the container otherwise.

### Related issue(s)
- closes #1323 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- This PR is intended to be applied over branch 1.7
- Ideally, a new branch (or tag) should be made available
- Minor bug-fix, no additional documentation needed.

### CODE REVIEW

**Comment by frgomes** [comment]
bors retry

**Comment by micw** [comment]
Please PR against master. Thank you!

**Comment by micw** [comment]
Hello Richard, looks like that went wrong :-/
You successfully rebased your branch to master but still try to PR against 1.7. I guess you just need to close this one and create a new against master.

**Comment by frgomes** [comment]
Dropped in favour of #1330

**Pull request closed without merging**
