### PR TITLE
Fix 1552 configurable folder names

### LINKED ISSUE #1552: Is it possible to change the name of the Junk folder?
In https://github.com/Mailu/Mailu/pull/1470, it states that Mailu will learn messages as spam if they are moved to the `Junk` folder, and learn them as ham if they are moved out of it.

However, I do not call the folder `Junk` — I call it `@Spam`, as I don't like having a system folder appearing in the middle of the folder list. Is there a way to tell Mailu to use this folder instead?

### PR DESCRIPTION
**Pull request by unikitty37**
## What type of PR?

Enhancement

## What does this PR do?

Allows the default IMAP folder names to be configured for users who prefer different names, or who are using software which has fixed ideas about what those names should be.

As most people will be able to go with the defaults, there doesn't seem to be much need to complicate the setup generator, so this PR just adds four unset variables to `mailu.env`. Setting one of them will override the values placed in the generated `dovecot.conf`, both when assigning the special folder names and, when the Junk folder is overridden, in the monitoring rules generated.

I'm not 100% happy about the `user.spam_folder` as it's really a server setting — if anybody can suggest a better place to put that, I can move it.

### Related issue(s)
closes #1552 

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [X] In case of feature or enhancement: documentation updated accordingly
- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by Nebukadneza** [comment]
bors try

**Comment by unikitty37** [comment]
bors try

**Comment by Nebukadneza** [comment]
bors ping

**Comment by Nebukadneza** [comment]
bors try-

**Comment by Nebukadneza** [comment]
bors ping

**Comment by Nebukadneza** [comment]
bors try

**Comment by Nebukadneza** [comment]
It seems the build failed because some python dependency could not be downloaded from pypi … trying again *sigh*

bors try

**Comment by Nebukadneza** [comment]
Hi again,

we’ve just discussed this feature, and found the change a little bit too invasive for the small steps we’re currently trying to take.

Also, we came up with another idea:
Looking at this documentation:
https://doc.dovecot.org/configuration_manual/config_file/config_file_syntax/
you can merge multiple inbox-namespaces into one. This should work when one of the namespaces is specified in the included override. Since you can also specify multiple user-visible names for the same special-use-folder, as mailcow does here:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/dovecot.conf#L86
… this would mean that technically your use-case should be possible already today … right?

 If you can find the time to try this out, that would be great. If it turns out to really work like we envisioned currently … how would you feel about adding that to the documentation, instead?

Thanks a lot for your contribution, and sorry for the slow response~

**Comment by unikitty37** [comment]
Thanks — unfortunately, this is what I'm already doing, and it doesn't work fully. There are two problem areas:

The first is https://github.com/Mailu/Mailu/blob/3a89c1e91096b06f05c3919d8496bc20b1e81982/core/admin/mailu/internal/templates/default.sieve#L25 which has the folder name `Junk` hardcoded, and uses the `:create` flag, so there is still a system folder listed in the middle of the regular folders. This rule runs before any user-defined rules, so the only way to filter spam is rather unintuitive: you must *disable* spam filtering in the admin area, then create a custom rule based on headers added by rspamd. This loses the ability to set a threshold from the admin area; you must now change the level at which rspamd changes from classifying as "Spam: No" to "Spam: Yes", and this is not a per-user change.

The second is https://github.com/Mailu/Mailu/blob/535b95bca75ea34190a036a34a9832805eec405d/core/dovecot/conf/dovecot.conf#L176 which runs `overrides/dovecot.conf` as an include, rather than a complete replacement for the system-provided ones. This means that the existing Junk folder is still created by https://github.com/Mailu/Mailu/blob/535b95bca75ea34190a036a34a9832805eec405d/core/dovecot/conf/dovecot.conf#L32 and is still given its special behaviour by https://github.com/Mailu/Mailu/blob/535b95bca75ea34190a036a34a9832805eec405d/core/dovecot/conf/dovecot.conf#L163.

These are the criteria I'm going by, and how they work with the overrides:

* ❌   A top-level folder called `@Spam`is created by Mailu, and new users are auto-subscribed to it.
* ❌   There is not a top-level folder called `Junk`. I can create it without it conflicting with predefined folders.
* ✔️  When rspamd classifies a mail as spam, it is delivered to the `@Spam` folder.
* ✔️  When I move an email that wasn't classified as spam to the `@Spam` folder, it is classified as spam.
* ✔️  When I move an email that was classified as spam to the `@Ham` folder, it is classified as ham.
* ❌   Moving messages to the user-created `Junk` folder doesn't change their spam classification.
* ❌   Moving messages from the user-created `Junk` folder doesn't change their spam classification.
* ❌   Moving messages from the `@Spam` folder to somewhere other than `@Ham` doesn't change their spam classification.
  
Here's the override file I used to get this:

```
namespace inbox {
  inbox = yes
  mailbox "Trash" {
    auto = subscribe
    special_use = \Trash
  }
  mailbox "Drafts" {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox "Sent" {
    auto = subscribe
    special_use = \Sent
  }
  mailbox "@Spam" {
    auto = subscribe
    special_use = \Junk
  }
}

plugin {
  sieve = file:~/sieve;active=~/.dovecot.sieve
  sieve_before = dict:proxy:/tmp/podop.socket:sieve
  sieve_plugins = sieve_imapsieve sieve_extprograms
  sieve_extensions = +spamtest +spamtestplus +editheader
  sieve_global_extensions = +vnd.dovecot.execute

  # Sieve execute
  sieve_execute_bin_dir = /conf/bin

  # Send vacation replies even for aliases
  # See the Pigeonhole documentation about warnings: http://wiki2.dovecot.org/Pigeonhole/Sieve/Extensions/Vacation
  # It appears that our implemntation of mail delivery meets criteria of section 4.5
  # from RFC 5230 and that disabling the recipient checks is not an issue here.
  sieve_vacation_dont_check_recipient = yes

  # Include the recipient in vacation replies so that DKIM applies
  sieve_vacation_send_from_recipient = yes

  # extract spam score from headers
  sieve_spamtest_status_type = strlen
  sieve_spamtest_status_header = X-Spam-Level
  sieve_spamtest_max_value = 15

  # Learn from spam
  imapsieve_mailbox1_name = @Spam
  imapsieve_mailbox1_causes = COPY
  imapsieve_mailbox1_before = file:/conf/report-spam.sieve
  imapsieve_mailbox2_name = *
  # Learn ham
  imapsieve_mailbox3_name = @Ham
  imapsieve_mailbox3_from = *
  imapsieve_mailbox3_causes = COPY
  imapsieve_mailbox3_before = file:/conf/report-ham.sieve
}
```

I can't see how to get around the points of failure using an override, given that the override file can't undo some of the things that has been done by the built-in one.

I realise you're trying to only make small changes at the moment, but this feels like it is a small change to me — it doesn't change default behaviour, and only adds four environment variables to the config.

Admittedly, I still don't know if it causes any tests to fail, as I've never managed to get bors to complete a run 😐

**Comment by HorayNarea** [comment]
> The first is
> 
> https://github.com/Mailu/Mailu/blob/3a89c1e91096b06f05c3919d8496bc20b1e81982/core/admin/mailu/internal/templates/default.sieve#L25
> which has the folder name Junk hardcoded, and uses the :create flag, so there is still a system folder listed in the middle of the regular folders.

Hm interesting… now I wonder why a very similar setup works in mailcow as they also use the name "Junk" in their global sieve filter: https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/global_sieve_after#L11 but without `:create`, So I'm not sure how this folder get's created initially… and if it would work in mailu if we just remove `:create`?

> This rule runs before any user-defined rules, so the only way to filter spam is rather unintuitive: …

Would it help if we allowed an override before our hardcoded sieve-rules?

**Comment by unikitty37** [comment]
> Hm interesting… now I wonder why a very similar setup works in mailcow as they also use the name "Junk" in their global sieve filter: https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/global_sieve_after#L11 but without `:create`, So I'm not sure how this folder get's created initially… and if it would work in mailu if we just remove `:create`?

I think the `dovecot.conf` entry causes it to get created anyway, because I've got `user.spam_enabled` set to off so I can use my own custom rule, which means that rule never gets called — and yet, if I delete the Junk folder, it reappears when Mailu is restarted.

I'm not sure what would happen if that rule got triggered when the folder didn't exist, though — would it cause the message to get dropped, or just passed on to the next rule?

I also tried to create a personal copy of the default rule but couldn't see a way to get over the fact that `user.spam_threshold` is inserted using the templating engine here https://github.com/Mailu/Mailu/blob/575f6b169133a925c0d51048e2f2d2d76fe74814/core/admin/mailu/internal/views/dovecot.py#L48

I'm assuming that rebuilds the user's default Sieve rules each time something's changed in that UI. But it means you can't use that threshold in your own rule, because that won't get rewritten — you have to configure spam rules yourself and mentally slap a "Do Not Touch" label on that section of the admin interface.
 
> > This rule runs before any user-defined rules, so the only way to filter spam is rather unintuitive: …
> 
> Would it help if we allowed an override before our hardcoded sieve-rules?

As long as the user-defined rule had a `stop` in it, I guess so. It would definitely be worth mentioning that in the docs 😀 

However, the inaccessibility of `user.spam_threshold` means you would still lose the use of the spam threshold setting.

**Comment by nextgens** [comment]
IMHO this is the wrong approach: aliases in an override would be much better/simpler.

https://github.com/Mailu/Mailu/issues/1552#issuecomment-965676196

**Comment by Diman0** [comment]
After discussing this PR during the last mailu meeting we have decided to close it. It  adds too much complexity with not enough gain for the project. This can be achieved via overrides for dovecot as mentioned by Nextgens.

**Pull request closed without merging**
