### PR TITLE
Implement a start date filter for autoreply, fixes #362

### LINKED ISSUE #362: Vocation: fields start
I have requests from customers who would like to put their vocations in advance. In fact, can we put a start field in vocation ?

### PR DESCRIPTION
**Pull request by kaiyou**

### CODE REVIEW

**Comment by kaiyou** [comment]
This is pretty simple if anyone is able to review. It will become obsolete once #612 is merged though.

**Comment by kaiyou** [comment]
> > It will become obsolete once #612 is merged though.
> 
> Then why trying to merge it?
> 
> If needed, I'm planning a review & test round Monday and I can take this up.

I should have been clearer, the Dovecot configuration part will be obsolete and some modifications will be required, the administration ui part is still good to merge :)

**Comment by muhlemmer** [comment]
Will review after #612 is merged, and perhaps this one merged against the new master.

**Comment by muhlemmer** [comment]
@kaiyou  Please merge against latest master for review.

**Comment by kaiyou** [comment]
Closing in favor of using my own branch

**Pull request closed without merging**
