### PR TITLE
Add newline before list to display properly

### PR DESCRIPTION
**Pull request by gitting**

### CODE REVIEW

**Comment by muhlemmer** [comment]
Strange it didn't get automerged... Manually merging.

**Comment by muhlemmer** [comment]
Strange...GitHub showed me the option to merge and then rejected it. So didn't do it.

**Comment by kaiyou** [comment]
Uh. This is targeted for 1.5, which is the issue.

**Comment by gitting** [comment]
Let me know if I should create a PR off `master`. I just followed "Edit on GitHub" link from the page to create this one.

**Comment by kaiyou** [comment]
If it is not too much trouble, that would be prefereable indeed :)

**Comment by gitting** [comment]
Redone off `master` to be able to merge. See #646.

**Pull request closed without merging**
