### PR TITLE
Drop postfix rsyslog localhost messages with IPv6 address

### PR DESCRIPTION
**Pull request by UbiquitousBear**
## What type of PR?

Enhancement

### Related issue(s)
#2594

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Review by nextgens — APPROVED** [review]
LGTM

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
Maybe we should discard the messages with "discarding EHLO keywords: PIPELINING" too

**Review by Diman0 — APPROVED** [review]
lgtm

**Comment by UbiquitousBear** [comment]
@nextgens i can work on making this configurable. Probably not this year

**Pull request merged**
