### PR TITLE
Minor doc fixes

### PR DESCRIPTION
**Pull request by dgtlmoon**
## What type of PR?

Documentation cleanup for the 'Mailu' setup at https://setup.mailu.io/1.7/

## What does this PR do?

Fixes spelling errors, grammatical mistakes and minor relocation of checkbox description text and styling, overall big readability improvement in the setup helper.

### CODE REVIEW

**Comment by dgtlmoon** [comment]
@Nebukadneza Glad to help, actually I was working on a similar project recently but came across this one and decided to spend my energy here instead :) it's a nice project!

One thing

`Fetchmail allows to download mails over IMAP/POP3 and uploads it your Mailu mailbox.`

This sentence needs work, but I'm unsure what's best, maybe

`"Fetchmail" is an application that retrieves mail from an external mail-server via IMAP/POP3 and inserts it into your Mailu mailbox." 

thoughts?

**Comment by Nebukadneza** [comment]
Your suggestion is better than what we currently have, building on your, i’d say
```
"Fetchmail" allows users to retrieve mail from an external mail-server via IMAP/POP3 and puts it in their inbox.
```

I think a bit shorter, and focussing on that it’s not systemwide but allows it for each user makes it clearer to the admin who’s just configuring his/her setup.
What do you think…?

**Comment by dgtlmoon** [comment]
@Nebukadneza reads perfectly clear to me, commit your suggestion please :)

**Comment by Nebukadneza** [comment]
is there anything more you’d like to add? otherwise i’m perfectly happy taking this in …

**Comment by dgtlmoon** [comment]
@Nebukadneza for now it's perfectly fine :)

**Pull request merged**
