### PR TITLE
Add missing dependencies to build podop for ARM

### LINKED ISSUE #2133: Missing dependencies dovecot/postfix when building with buildx and build_arm.h v1.9.0
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose

### Versions
1.9.0

## Description
Building dovecot and postfix images for ARM requires additional dependencies to build `podop>0.2.5` from source as this is not available as binary for ARM:

`core/dovecot/Dockerfile` and `core/postfix/Dockerfile`:
```diff
-pip3 install "podop>0.2.5" 
+RUN apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev \
+  && pip3 install "podop>0.2.5" \
+  && apk del .build-deps
```

## Replication Steps
Build images using `buildx` (not officially supported yet) or by running `tests/build_arm.sh`.

## Expected behaviour
No build errors

## Logs
Copied from #1200:

```
ERROR: for imap  (<Service: imap>, 'The command \'/bin/sh -c pip3 install "podop>0.2.5"\' returned a non-zero code: 1')

ERROR: for smtp  (<Service: smtp>, 'The command \'/bin/sh -c pip3 install "podop>0.2.5"\' returned a non-zero code: 1')
ERROR: Service 'smtp' failed to build: The command '/bin/sh -c pip3 install "podop>0.2.5"' returned a non-zero code: 1
```

```
Step 25/25 : HEALTHCHECK CMD curl -f -L http://localhost/ui/login?next=ui.index || exit 1
 ---> Using cache
 ---> e60682344d07
[Warning] One or more build-args [QEMU] were not consumed
Successfully built e60682344d07
Successfully tagged mailu/admin:local
Collecting podop>0.2.5
Collecting podop>0.2.5
  Downloading podop-0.2.6-py3-none-any.whl (9.2 kB)
  Downloading podop-0.2.6-py3-none-any.whl (9.2 kB)
Collecting aiohttp
Collecting aiohttp
  Downloading aiohttp-3.8.1.tar.gz (7.3 MB)
  Downloading aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/lib/python3.7/site-packages (from aiohttp->podop>0.2.5) (4.5.2)
Collecting async-timeout<5.0,>=4.0.0a3
Collecting attrs>=17.3.0
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/lib/python3.7/site-packages (from aiohttp->podop>0.2.5) (1.3.0)
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/lib/python3.7/site-packages (from aiohttp->podop>0.2.5) (1.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/lib/python3.7/site-packages (from aiohttp->podop>0.2.5) (4.5.2)
Collecting aiosignal>=1.1.2
Collecting charset-normalizer<3.0,>=2.0
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting asynctest==0.13.0
Collecting charset-normalizer<3.0,>=2.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting typing-extensions>=3.7.4
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting frozenlist>=1.1.1
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.2.0.tar.gz (65 kB)
  Downloading frozenlist-1.2.0.tar.gz (65 kB)
  Installing build dependencies: started
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting asynctest==0.13.0
  Preparing metadata (pyproject.toml): finished with status 'done'
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting idna>=2.0
Collecting idna>=2.0
  Downloading idna-3.3-py3-none-any.whl (61 kB)
  Downloading idna-3.3-py3-none-any.whl (61 kB)
Building wheels for collected packages: aiohttp, frozenlist
  Building wheel for aiohttp (pyproject.toml): started
Building wheels for collected packages: aiohttp, frozenlist
  Building wheel for aiohttp (pyproject.toml): started
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /usr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmppw6qi6ob
       cwd: /tmp/pip-install-up52ktrq/aiohttp_4b784f826c97499f8b20ba537bf789a4
  Complete output (95 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.7
  creating build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/http.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/http_exceptions.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/streams.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/pytest_plugin.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/log.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/__init__.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/cookiejar.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/client_proto.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_log.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_response.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/payload_streamer.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/worker.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_server.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/client_ws.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_routedef.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/connector.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_protocol.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/client_reqrep.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/helpers.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/http_websocket.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/resolver.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_app.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_request.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/test_utils.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/multipart.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_urldispatcher.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_middlewares.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/typedefs.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/client_exceptions.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/base_protocol.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_fileresponse.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_runner.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/locks.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/payload.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/http_parser.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/abc.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_exceptions.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/http_writer.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/client.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/tracing.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/hdrs.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/tcp_helpers.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/formdata.py -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/web_ws.py -> build/lib.linux-aarch64-3.7/aiohttp
  running egg_info
  *********************
  * Accelerated build *
  *********************
  warning: no files found matching 'aiohttp' anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '*.lib' found anywhere in distribution
  warning: no previously-included files matching '*.dll' found anywhere in distribution
  warning: no previously-included files matching '*.a' found anywhere in distribution
  warning: no previously-included files matching '*.obj' found anywhere in distribution
  warning: no previously-included files found matching 'aiohttp/*.html'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'aiohttp.egg-info/SOURCES.txt'
  copying aiohttp/_cparser.pxd -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_find_header.c -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_find_header.h -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_find_header.pxd -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_headers.pxi -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_helpers.c -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_helpers.pyi -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_helpers.pyx -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_http_parser.c -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_http_parser.pyx -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_http_writer.c -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_http_writer.pyx -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_websocket.c -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/_websocket.pyx -> build/lib.linux-aarch64-3.7/aiohttp
  copying aiohttp/py.typed -> build/lib.linux-aarch64-3.7/aiohttp
  creating build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-aarch64-3.7/aiohttp/.hash
  running build_ext
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/aiohttp
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.7m -c aiohttp/_websocket.c -o build/temp.linux-aarch64-3.7/aiohttp/_websocket.o
  error: command 'gcc' failed: No such file or directory: 'gcc'
  ----------------------------------------
  ERROR: Failed building wheel for aiohttp
  Building wheel for aiohttp (pyproject.toml): finished with status 'error'
  Building wheel for frozenlist (pyproject.toml): started
  Building wheel for aiohttp (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /usr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpczgagiu8
       cwd: /tmp/pip-install-crmeg1n_/aiohttp_9d517ca520da43ebb03477e078b834b5
```

### PR DESCRIPTION
**Pull request by Erriez**
## What type of PR?

Bugfix.

## What does this PR do?

Fix missing dependencies to build podop from source for ARM.

### Related issue(s)
- Mention an issue like: #1200, #2133
- Auto close an issue like: closes #2133

## Prerequisites

- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
I think this introduces too much overhead... can we do it only when required?

```
pip3 install "podop>0.2.5" || (apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev && pip3 install "podop>0.2.5" && apk del .build-deps)
```

Or maybe using ```uname -m``` or ```arch```?

**Comment by Erriez** [comment]
`uname -m` returns the current platform which is `x86_64`. The packages `gcc musl-dev python3-dev` are required when building for ARM only. `buildx` contains a target platform macro which can be used, but I've no idea how to make this compatible with the legacy `tests/build_arm.sh` script as users can specify a various number of `ARCH` ARM flavors.

A [successful](https://github.com/Mailu/Mailu/issues/1200#issuecomment-1004779420) build was reported in issue 1200.

**Comment by nextgens** [comment]
Maybe it's time we deprecate tests/build_arm.sh once and for all. I'd rather we document a single way to cross-compile... and if buildx is the way that's fine by me

**Comment by Erriez** [comment]
Yes, my intention was to migrate to `buildx` as I've created a minimal single [commit](https://github.com/Erriez/Mailu/commit/ede928f083438d577e60e6ed24ef120e58b09420) on top of my forked 1.9.0 tag. However, I could not find a solution to get the current Github Actions compatible with `buildx` in `core/admin/Dockerfile` as the `FROM` line is not recognized by `docker build`:

```diff
-FROM ${ARCH}node:16 as assets
+# Temporary build image
+FROM --platform=$BUILDPLATFORM node:16 as assets  # <- Incompatible with docker build command
+ARG BUILDPLATFORM
```

Otherwise I can provide a PR with `buildx` support without touching the Github Actions CI. Ideas are welcome.

**Comment by nextgens** [comment]
That's fine, we can drop support for build if buildx works

**Comment by Erriez** [comment]
Thanks for your confirmation. Then I'll check how to update the `CI.yml` with `buildx`. That's a challenge and takes some time.

**Comment by leolivier** [comment]
#2403 PR should deprecate this one, I think.
I don't really get why, but the above packages are not useful anymore for building on ARM with this PR.

**Comment by Diman0** [comment]
Yes. This is deprecated by PR #2403 . That PR is already able to build ARM. If changes are still required, then we can do this after PR #2403 is merged.

**Pull request closed without merging**
