### PR TITLE
core/*/Dockerfile: Move to alpine 3.15.4

### PR DESCRIPTION
**Pull request by mrueg**
## What type of PR?

Enhancement

## What does this PR do?
Updates alpine to latest 3.15.x
https://alpinelinux.org/posts/Alpine-3.15.0-released.html
### Related issue(s)
None

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [] In case of feature or enhancement: documentation updated accordingly
- [] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by mrueg** [comment]
bors retry

**Comment by Diman0** [comment]
I don't understand this PR. You are only updating alpine in 3 of the 11 containers that use alpine. It does not even update all core containers (such as admin).

bors retry

**Comment by mrueg** [comment]
> I don't understand this PR. You are only updating alpine in 3 of the 11 containers that use alpine. It does not even update all core containers (such as admin).
> 
> bors retry

It initially failed CI, so I was repushing to reduce Change.

**Comment by Diman0** [comment]
The build initially failed because the documentation image did not have pinned dependencies and a breaking update was released for one of the dependencies of the documentation image. Building works again.

Either the PR should update all the Dockerfile's or you can close this PR. Both are fine. Normally we update all dependencies (including alpine version) when we near a release.

**Comment by mrueg** [comment]
Understood, closing it then.

**Pull request closed without merging**
