### PR TITLE
To make smtp_tls_security_level and smtp_tls_wrappermode configurable

### LINKED ISSUE #1558: Make smtp_tls_policy_maps easily configurable
Hi Team,

It will be great to have following options configurable from mailu.env as they are required in many cases
when SMTP RELAY from an ISP is in use:
smtp_tls_security_level
smtp_tls_wrappermode
(PR is following)

### PR DESCRIPTION
**Pull request by Snakesms**
## What type of PR?

Enhancement

## What does this PR do?
Make following Postfix options configurable:
smtp_tls_security_level
smtp_tls_wrappermode

They are required in many cases for to let SMTP RELAY properly work with ISP's SMTP servers
They are not added to configuration html on purpose, for not to confuse 

### Related issue(s)
- Mention an issue like: #1558 
- Auto close an issue like: closes #1558 

## Prerequistes:
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [+] In case of feature or enhancement: documentation updated accordingly
- [+] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by lub** [comment]
It seems `smtp_tls_security_level` is already configurable via `OUTBOUND_TLS_LEVEL` due to #1478

**Comment by Snakesms** [comment]
> It seems `smtp_tls_security_level` is already configurable via `OUTBOUND_TLS_LEVEL` due to #1478

removed respective option from my PR

**Comment by Robin-floss** [comment]
would be nice, but seems like this pr is dead

**Comment by Snakesms** [comment]
> would be nice, but seems like this pr is dead

I agree it looks dead and really long-lasting.
However, as a PR owner, I can't imagine how much it can be alive for such a simple change.
If I knew instead of being accepted straight away it will sit in the backlog for a year I won't even bother to spend time on it, just would fix for myself and move on

**Comment by nextgens** [comment]
Being discussed on #1558

**Pull request closed without merging**
