### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by Prosta4okua**
Hello there! 
I've done Ukrainian translation. Do I need to change `"Last-Translator: Jaume Barber <jaumebarber@gmail.com>\n"` or something else? Did I translate everything?
Thanks in advance!

### CODE REVIEW

**Comment by Prosta4okua** [comment]
> Hello there! I've done Ukrainian translation. Do I need to change `"Last-Translator: Jaume Barber <jaumebarber@gmail.com>\n"` or something else? Did I translate everything? Thanks in advance!

@nextgens hi, could you help?

**Comment by nextgens** [comment]
Thank you for your contribution.

I am sorry, I am not very familiar with the l10n... nor the specific of Ukrainian locale.

I believe you need to edit core/admin/assets/Dockerfile too when you add a new language for it to work; Can you add those changes to the PR please?

I wonder if the folder name 'uk_UA' is the right one; Why not just 'uk' and uk:uk-UA in the Dockerfile? If that's right, can you git move them please?

**Comment by Prosta4okua** [comment]
okay, according to https://www.andiamo.co.uk/resources/iso-language-codes/ Ukrainian is ua. Anything else? @nextgens

**Comment by ghostwheel42** [comment]
I'll try to review this in the next days. Sorry, I'm very busy at the moment. 
There is some kind of locale translation between the locale used by mailu an the locale used by the JavaScript AdminsLTE module. 
We may need to add such a translation.

**Review by ghostwheel42 — APPROVED** [review]
LGTM. I'll rename it to "uk" after merging

**Review by nextgens — APPROVED** [review]

**Comment by ghostwheel42** [comment]
I'll continue in #2936

**Pull request closed without merging**
