### PR TITLE
Ensure we always ask for the existing password before allowing a change

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

Ensure we always ask for the existing password before allowing a change.

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by Diman0** [comment]
The code changes looks OK to me. I only need to test it.

bors try

**Comment by Diman0** [comment]
It seems there is some kind of network issue with writing the build cache to ghcr.io. I will try tomorrow again.

**Comment by Diman0** [comment]
Just a confirmation I tested the PR and it works fine. Tomorrow I will double check the network issue is gone and will accept the PR.

**Comment by nextgens** [comment]
bors try

**Review by Diman0 — APPROVED** [review]
LGTM

**Pull request merged**
