### PR TITLE
Fix spelling errors and add diagram of mailu network

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?

documentation

## What does this PR do?
Originally created by @nextgens. Credits go to him. Unfortunately since his account is hidden and this hides PR 2993 as well, I've created this PR to merge his changes.

This PR fixes spelling errors. It also adds a programmed diagram that allows the folks of the helm-chart project to generate NetworkPolicies

### Related issue(s)
- closes #2993

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [n/a ] In case of feature or enhancement: documentation updated accordingly
- [n/a ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
bors try-

**Comment by Diman0** [comment]
bors retry

**Comment by Diman0** [comment]
bors try-

**Comment by Diman0** [comment]
bors retry

**Review by ghostwheel42 — APPROVED** [review]

**Comment by Diman0** [comment]
I don't understand why the filters and core test suddenly fail on the imap connection.

**Comment by Diman0** [comment]
#2993 is visible again. So we can close this (now) duplicate PR.

**Pull request closed without merging**
