### PR TITLE
Bug/1536

### PR DESCRIPTION
**Pull request by toastboy70**
## What type of PR?

Fix for https://github.com/Mailu/Mailu/issues/1536

## What does this PR do?

As defined in https://nlnetlabs.nl/documentation/unbound/unbound.conf/, log messages will go to /dev/stderr if logfile is set to "" in the config file.

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [n/a ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by lub** [comment]
Hi @toastboy70,

thank you for the PR!

Could you please base your changes on master instead of (I suspect) 1.7?

**Comment by toastboy70** [comment]
@lub Will do. I saw recent commits on 1.7 so I was assuming that was the right place. As you may be able to tell I'm new to this kind of submission. Shall I close this pull request?

**Comment by lub** [comment]
You can also fix it in your toastboy70:bug/1536 branch and force push it, but easiest is probably creating a new branch and a new pull request.

Just make sure your new branch is based on master https://mailu.io/master/contributors/workflow.html#pr-workflow

**Comment by toastboy70** [comment]
Abandoning this PR and making a new one based on master.

**Pull request closed without merging**
