### PR TITLE
Ratelimit outgoing emails per user

### LINKED ISSUE #1031: Set sending quotas per user?
Hi all

We're currently using Virtualmin for email. It's been rock solid, but we'd like to be able to move to a docker solution to make maintenance and upgrading easier. Also rainloop has a much nicer UI than roundcube.

The only thing we need that I can't find information on is whether we can set sending rate limits and monthly quotas per user in mailu. Is this possible? We're providing email as part of a hosting service, so this is a must for us.

Thanks!

### LINKED ISSUE #1774: Is MESSAGE_RATELIMIT used at all??
Hello

I found that in the master and version 1.8 docs appears the MESSAGE_RATELIMIT setting but in the source code it doesnt seem to be used at all. Only appear in the docs subdir:
```
# grep -r  MESSAGE_RATELIMIT *
docs/compose/.env:MESSAGE_RATELIMIT=100/day
docs/configuration.rst:The ``MESSAGE_RATELIMIT`` is the limit of messages a single user can send. This is
```
So what is the current status of this setting? Can i use it in mailu 1.7 or 1.8 or is it a future addition in the works?

Thanks

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

Feature

## What does this PR do?

A conflict-free version of #1360 implementing per-user sender limits

### Related issue(s)
- close #1360 
- close #1031
- close #1774 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
Unlike its predecessor, it doesn't limit what relays can do (smtpd_relay_restrictions vs smtpd_client_restrictions). Do we want the limit to be global or per user?

**Comment by nextgens** [comment]
We've talked about it at the regular meeting, spam using BCC isn't a real-world concern

**Review by Diman0 — CHANGES_REQUESTED** [review]
The code itself looks fine. I still need to test it.

However a new setting is introduced in mailu.env, but not documented in configuration.rst.
Can you add this to configuration.rst? I can also do this and push to the PR if you prefer this.

**Comment by nextgens** [comment]
If you don't mind doing it, that'd be great.

What about the default setting? Is 100/hour fine or should we make it 100/day to limit the "blast radius" even further?

**Comment by Diman0** [comment]
I will update the documentation. Besides configuration.rst, webadministration.rst must also be updated since you added a new setting to the web ui. 

I have no clue on the default setting. It is quite rare for me to send emails. 100/day would be sufficient for me, but I'm not sure if this is high enough for people who do send emails all day. This would entail to 100/24=4 emails per hour if you insist on sending emails 24/7. Maybe we can make it 200?

**Comment by nextgens** [comment]
200 sounds good to me

**Comment by Diman0** [comment]
The configuration.rst already contained the documentation for message_ratelimit. It was added by mistake. We must not forget to close #1774 after this PR is merged. Let's ask BORS kindly to build the new images again and I will try testing it this evening.

bors try

**Comment by Diman0** [comment]
Looks good to me. It works flawlessly. Roundcube also showed me the error that I was sending too many messages.
Only thing we must not forget, is to document in the future how to reset the rate limiting. I'm planning to create a brand new security page where we centralise all information on security measures and how to configure them.

So far I could see, the rate limit can only be reset by changing the MESSAGE_RATELIMIT value in mailu.env and then recreating your containers. Only recreating your containers does not reset the setting.

I pushed one more commit, because I incorrectly thought before you could configure the message_ratelimit in the web gui. However it only shows you what the status is of the rate limit for each user (that is fine).

I think the PR is now ready to be merged and I can approve it @nextgens?

**Comment by Diman0** [comment]
Just a precaution. build again to confirm I did not make breaking changes.

bors try

**Comment by nextgens** [comment]
> document in the future how to reset the rate limiting

We could make a clickable button in the UI

> I think the PR is now ready to be merged and I can approve it @nextgens?

Yes, I think so

**Comment by Diman0** [comment]
With sane settings it should not be required to reset it. If people really require this then we could still add it in the future.

**Review by Diman0 — APPROVED** [review]
LGTM. Thank you for another great contribution :+1:

**Comment by zigazajc007** [comment]
Hello,

This pull request seems to add a feature on how many emails each user can send per day.
I found that you can change that in .env file, but I can't find where I can do that per-user.

It would be great if this would be implemented in the admin web panel under "Features and quotas" category when adding a new user.

Something like that:
image

**Comment by elandorr** [comment]
I'd also like to see that. Even if just to protect against hacked/leaked accounts causing spam issues. Globally and per user would be nice.

**Comment by nextgens** [comment]
This is the wrong place to talk about it: this PR has been merged.

Please create a new issue and put thumbs up on it to express interest.

We have a global limit (MESSAGE_RATELIMIT) so the feature would be to have it per user.

**Comment by elandorr** [comment]
My bad, will do!

**Pull request merged**
