### PR TITLE
Add managesieve proxy

### PR DESCRIPTION
**Pull request by mildred**
Add managesieve proxy so it can be accessed from the outside. See #308

Built on top of #429

### CODE REVIEW

**Comment by kaiyou** [comment]
I'll probably not merge this until we have a proper configuration wizard and this can be properly made optional. It looks really good though and could help many users I guess.

**Comment by mildred** [comment]
I just updated my PR. This PR is just adding a new docker image to build and it's up to you to use it or not.

**Comment by muhlemmer** [comment]
Thanks for submitting your pull request. We want to apologize for not reviewing your submission more promptly. Note that this is a [GitHub saved reply](https://help.github.com/articles/about-saved-replies/) and not all content might apply to you.

I would like to notify you, we had some significant changes on our master branch. If you are still looking to merge this PR, please merge the source branch with the upstream master. This will help us doing a functional review of this PR.

A possible workflow for this would be:
```
git remote add upstream https://github.com/Mailu/Mailu.git
git fetch --all
git checkout <your_branch>
git merge upstream/master
```

Git will tell you if there are any merge conflicts. See also: [how conflicts are presented](https://git-scm.com/docs/git-merge#_how_conflicts_are_presented). If the merge conflicts are extensive, you might want to use [`git mergetool`](https://stackoverflow.com/a/163659/1816774). After resolving any conflicts, you'll have to finish the merge by running:
```
git commit -a
```
Now you should push, to make the new changes available in the PR. We will be notified automatically about the updated PR.
```
git push
```

We will then start the review process. Thanks in advance!

**Comment by muhlemmer** [comment]
Additional comment @kaiyou: we've started work on the setup utility. If the general implementation of this seems satisfying, we can merge this PR into master. We will then pickup the works inside setup from there.

**Comment by kaiyou** [comment]
@muhlemmer there will however be a conflict with the abstract db thing. I say we block this a bit longer until I finish writing the "write" part of the in-database sieve scripts first, so they can be edited both using managesieve *and* the admin ui.

**Comment by muhlemmer** [comment]
Just trying my luck: https://trac.nginx.org/nginx/ticket/1697

**Comment by micw** [comment]
@mildred Are you still interested in adding this to mailu? If so, I'd like to test and review it.

From what I've seen, the PR runs a lightweight dovecot in front of managesieve for only auth+proxy, correct? If so, I'd suggest to also mount /certs and add some code to reload it on cert updates and expose it via TLS (if supported by dovecot and clients).

**Comment by tjikkun** [comment]
Not sure if this is still of interest to you guys, but I submitted a patch for nginx to support proxying sieve. See mail thread at https://mailman.nginx.org/pipermail/nginx-devel/2020-April/013082.html

**Comment by micw** [comment]
@tjikkun This is really great, it solves this issue in a much leaner and better way than running another dovecot as proxy. Is the patch already merged upstream?

**Comment by tjikkun** [comment]
@micw I don't have a reply on the patch yet, so it is not (yet?) merged upstream. Of course I hope it will be accepted and merged soon, but I am not the one to make that decision.
The proxy behaves just like the existing mail proxies (Like SMTP and IMAP) in nginx, so yes, it uses the mail_auth_http_module.

**Comment by muhlemmer** [comment]
@tjikkun Awesone! I've seen their latest reply and they lack resources to review it :disappointed: . But I understand them.

Are you a Mailu user @tjikkun? or did you write this for other purposes? As they suggest to make the patch as an external module (for now), perhaps we can host it as a Mailu repo. If @kaiyou agrees.

I see you did units tests and everything, that's great! We can even wire it up to travis. If you need help from the devops side, just shout! Even if its not going to be a Mailu repo ;).

My philosophy is: if the module is actually used in real live, there will be a higher change of adoption by upstream in the long run. This happens all the time in the linux kernel.

**Comment by tjikkun** [comment]
@muhlemmer I am not a Mailu user, but I ran across this issue when I search for existing options to proxy managesieve with nginx.
I wrote this for my employer, and we actually run this is production for a while now, without any issues thus far. We have hundreds of thousands mailboxes, but only a very few of them (percentage wise) use sieve, and then of that, you only use managesieve now and then. So in the end, it is not tested with very high concurrency, but it is not like it hasn't seen any real usage either.

I just use https://github.com/AntagonistHQ/nginx/archive/%{commit}/nginx-%{shortcommit}.tar.gz as my source for building nginx, where at the moment
%global commit 50a0f31d97c998d4942469e0b91295c3730c6955
%global shortcommit %(c=%{commit}; echo ${c:0:7}
(This is from an RPM spec-file)

**Comment by muhlemmer** [comment]
Okay, I'm tempted to set up my own build on alpine with your patch, as an experiment.

Two more questions:
1. What is the license of your patch? As it is not yet committed to Nginx and I haven't seem a copyright assignment to Nginx, I believe you or your employer are the copyright holder.
2. Do mind I send you a direct e-mail requesting a confirmation that the patch is available under an open source license? I will use the e-mail address used for patch submission at Nginx mailing-list.

**Comment by tjikkun** [comment]
Hi @muhlemmer 
Since I sent it for inclusion in nginx, it will be under the same license, https://nginx.org/LICENSE
For now consider it BSD 2-clause
If you sent me the email I can confirm it for you

**Comment by NIronwolf** [comment]
This is encouraging.  I was hoping to be able to switch to just using the Thunderbird extension to manage rules rather than having a web browser open along side to add them in RainLoop.  Were your tests successful enough that it may become a feature?  I'm only a little bit coder level so I can't really do any heavy lifting but I'm willing to do testing.

Thanks for such a great package.  Recently set it up on my unRAID server and plan to post there about the experience.

**Comment by Diman0** [comment]
After discussing this PR during the last Mailu meeting. We decided to close it.
- Our security model is that ALL communication goes via front. This PR circumvents this.
- TLS termination happens in the dovecot container. It must also check for SSL cert renewal. 
- Auth is not checked centrally like we have implemented for everything else.

The real option is waiting for that [nginx patch](https://trac.nginx.org/nginx/ticket/1697) for a managesieve proxy to be merged. 
Once this is merged, we will revisit this topic. Anyone interested in this functionality, please ask via that [nginx patch](https://trac.nginx.org/nginx/ticket/1697) if the nginx team will merge it.

**Comment by svoop** [comment]
@tjikkun I'm also stuck as far as Sieve is concerned due to managesieve missing on the proxy. Has you patch ever been considered (or even merged) by Nginx?

**Comment by ghostwheel42** [comment]
The patch was not merged. I've reviewed it and fixed some bugs months ago. 
I can try to apply it to the latest nginx and send it to you if you like.
We didn't want to maintain it as mailu Team but I'll raise the issue at our next meeting.

**Comment by svoop** [comment]
That's unfortunate and I understand if you don't want to carry on with it. I'm no C coder, so I doubt to be much help trying to get it merged... other than begging maybe. 😃  Server-side filter rules are somewhat essential, in my case my CI should be able to manage the rules, and the managesieve port is ideal for my Ruby CI bot to talk to. If Nginx is a dead end, maybe the Mailu team would accept another approach even if not all is funneled through the front container? I know, it's almost a rhetorical question.

**Comment by tjikkun** [comment]
@svoop Yeah, unfortunately nginx doesn't seem very welcoming to outside contributions. I've got one reply in 2020, telling me they might look into it in May, after that I got nothing. Tried to ask for a reply a few times, but only got silence.

@ghostwheel42 Are your fixes available somewhere online? I would be interested to see them :)

**Comment by svoop** [comment]
@tjikkun Isn't there any other way such as exposing the port from the IMAP (Dovecot) container directly? It's not such a common feature, so a plan B could be a README which tells how to tweak things to get it to work, even if you break the "everything thru the front container" paradigm in doing so.

**Comment by ghostwheel42** [comment]
> Isn't there any other way such as exposing the port from the IMAP (Dovecot) container directly?

There is. But we decided against it. You can do it if you know how but we didn't want to encourage people by providing a FAQ entry. 

See https://github.com/Mailu/Mailu/pull/428#issuecomment-967195644

**Comment by ghostwheel42** [comment]
> @ghostwheel42 Are your fixes available somewhere online? I would be interested to see them :)

@tjikkun I don't have access right now but I'll try to find it and send you a link in the next two weeks.

**Pull request closed without merging**
