### PR TITLE
AdminLTE 3

### PR DESCRIPTION
**Pull request by DjVinnii**
## What type of PR?

Enhancement

## What does this PR do?

This PR implements AdminLTE 3 for the admin interface. It also includes the implementation of DataTables and a language selector.

### Related issue(s)
- closes: #1567
- closes: #1764 

## Prerequistes

- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
Will definitely look into this after 1.8 is out

**Comment by Diman0** [comment]
I resolved the merge conflicts. In core/admin/package.json there were some conflicts with packages. I did not take over:
"file-loader": "^6.2.0",
"popper.js": "^1.15.0",
"style-loader": "^3.2.1",
These were all pointing to 3 year old versions. They should not be used anymore. I think these got removed when we updated the dependencies. 

"@babel/preset-env": "^7.14.7"
I did take over this dependency. I'm not certain if it is used, but maybe @DjVinnii Dj can shed some light on this.

**Comment by Diman0** [comment]
Lets see if we can automatically use the new CI/CD workflow :pray: 

bors try

**Comment by Diman0** [comment]
bors cancel

**Comment by Diman0** [comment]
I resolved the build issues and updated all the dependencies and update master to node 16 again. 

bors try

**Review by nextgens — DISMISSED** [review]
LGTM

**Comment by Diman0** [comment]
Merged hopefully the last merge conflict. I will build it one more time and will try testing it tomorrow.

bors try

**Comment by Diman0** [comment]
I think I resolved the merge conflict incorrectly. All icons are missing now.

**Comment by Diman0** [comment]
@nextgens Did you really test the PR?
When I go back to the second last commit [5afbf37292cfe9dfbd3b06dbde9913c61d0f6a6e](https://github.com/Mailu/Mailu/pull/1800/commits/5afbf37292cfe9dfbd3b06dbde9913c61d0f6a6e), I still have missing icons in the Admin interface.
That is the commit that you approved.

I can remember I had a quick look at the PR a long time ago. I know for certain that all icons were displayed correctly with the last commit from the PR author:
https://github.com/Mailu/Mailu/pull/1800/commits/60766f6d80f482463ed646474390266b101d67ba
After this commit, one of my commits broke the icons?

I guess I will keep going back in commits and rebuild all images until I got back to the working state.

**Comment by nextgens** [comment]
Yes I did test it... but my branch may have been dirty as I've been playing with other things. Icons didn't look obviously broken to me (but may have been cached by my browser or something)

**Comment by Diman0** [comment]
I think I found the culprit. For font-family 5 some additional CSS styling is needed. I got it working with the cdn 
@import url("//use.fontawesome.com/releases/v5.15.3/css/all.css");

I'm now trying to find the minimal changes required. I don't want to use that all.css from the fontawesome cdn.

**Comment by DjVinnii** [comment]
@Diman0 The CSS for Font Awesome should be included in [vendor.js](https://github.com/Mailu/Mailu/blob/00276d8b7014e9cd757c080ebd03f99aa852a2fa/core/admin/assets/vendor.js)

**Comment by Diman0** [comment]
@DjVinnii I can already see it included in vendor.js. Yet I see squares instead of icons.

When I add ```@import url("//use.fontawesome.com/releases/v5.15.3/css/all.css"); ``` to app.cs it works. All icons are displayed.
Maybe there is an error in the css file we include via vendor.js?

**Comment by Diman0** [comment]
@DjVinnii No. I had already resolved that error. I should have stated that before. I have pushed the commit that resolves the error from expose-loader. 

So when I add 
```@import url("//use.fontawesome.com/releases/v5.15.3/css/all.css"); ```
to app.css and then build the admin image, then the icons are displayed for me.

Yet when I compare the differences using the developr tools I cannot see any important differences.

**Comment by Diman0** [comment]
Adminlte3 uses the exact same fontawesome version. Strange stuff. I have no clue why it doesn't simply work. 

Maybe we should use that CDN in the app.css file?
It is a pinned version.

**Comment by Diman0** [comment]
The fontawesome plugin included with adminlte3 is also version 5.13.3. I say we directly include the all.css file from the cdn as a workaround.
Maybe someone in the future can get the icons working again using the local plugin from adminlte.

**Comment by Diman0** [comment]
I have added ```@import url("//use.fontawesome.com/releases/v5.15.3/css/all.css");``` as a hopefully temporary workaround.  I hope the fontawesome plugin included with adminlte will magically work again when we update to a newer adminlte version in the future. Or perhaps someone more experienced in python/adminlte/web developement can get it working.

It may be a small nitpick, but I'd like to have the Mailu blue color at the top left. Having a blue background behind the Mailu logo is our signature. It is also displayed on Mailu.io. 

bors try

**Comment by Diman0** [comment]
We found the culprit. It is the deprecated url-loader. The icons are back now. 

Last thing left is returning the sidebar to the old look and feel.
At least the top left should show the blue background again.
Ideally the middle element (the user name in the side bar) and the menu list in the side bar also get the old background colour back.

bors try

**Review by Diman0 — APPROVED** [review]
Lgtm. Thank you for your contribution.
In another pull request we will fix the styling of the sidebar.

**Review by nextgens — APPROVED** [review]
LGTM

**Review by HaleyACS — APPROVED** [review]

**Review by HaleyACS — APPROVED** [review]

**Review by HaleyACS — APPROVED** [review]

**Review by HaleyACS — APPROVED** [review]

**Review by HaleyACS — APPROVED** [review]

**Pull request merged**
