### PR TITLE
expose pop3 port, remove imap-ssl from dovecot in kubernetes manifest

### PR DESCRIPTION
**Pull request by sbias**
## What type of PR?
bug-fix

## What does this PR do?
Exposes provided pop3 service in service definition to get useable by front

### CODE REVIEW

**Comment by kaiyou** [comment]
This is related to #1111. @micw, could review? You are probably more of a k8s expert than any of us.

**Comment by kaiyou** [comment]
Adding a priority label if we can merge it in 1.7.

**Comment by micw** [comment]
@kaiyou I found that issue too when creating my helm chart. The fix is valid and should be merged. I don't have approval permissions.

The ports should also be named in the deployment (not only in the service). That's not required but should be done for readability and consistency.

Maybe we should also remove the imap-ssl port exposure because it's completely unused (ssl termination is done by nginx).

**Comment by sbias** [comment]
You are absolutely correct, the port should be added in the deployment too. At the same time we can add names to the ports there to make them consistent. Should i add it in this PR?

**Comment by micw** [comment]
> Should i add it in this PR

I think so, then we have this done too and can close #1111 when this is merged.

**Comment by sbias** [comment]
Ok, i will check imap-ssl removal too. If ssl is terminated in nginx there is no reason to map it in this service.

**Comment by micw** [comment]
Thumbs up from my side. Thank you!

**Pull request merged**
