### PR TITLE
1.5 autobuild

### PR DESCRIPTION
**Pull request by muhlemmer**
In preparation of a multi-version documentation setup, I considered it would be helpful to move 1.5 to travis building also. This is a simplified back port, without any testing.

@kaiyou, If you agree with this, I'll disable the autobuild on Docker hub, before merging this PR. This is to prevent collisions.

### CODE REVIEW

**Comment by muhlemmer** [comment]
Good idea ;). Radicale does not build anymore on alpine 3.7, so I've moved it to edge.

**Comment by kaiyou** [comment]
It seems to run just fine on my side with the images built from ``tests/build.yml``, so let's go through with it. This way, we can also benefit from cron builds on 1.5.

**Comment by muhlemmer** [comment]
Ok, I'll disable the build on docker hub and I'll do the merge when done.

**Comment by kaiyou** [comment]
Once done, I believe the compose file from the master branch should run just fine. You actually did 90% of the job setting this up :)

**Comment by muhlemmer** [comment]
I'll probably need to do some small mods to the compose file (as I found with setup). I'll keep the working version on master.

Done with docker hub, will merge this now.

**Pull request merged**
