### PR TITLE
Testing images are pushed to DOCKER_ORG_TESTS again.

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?

Bug fix

## What does this PR do?
Fixes CI workflow. Testing images ( *:pr-xxxx) where pushed to DOCKER_ORG (mailu) instead of DOCKER_ORG_TESTS (mailuci). Images for testing (branch testing) are pushed to mailuci again.

### CODE REVIEW

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
bors try

**Comment by Diman0** [comment]
Looks good. The retry worked. See the mailuci docker repo. Let's try one more time.

bors try

**Comment by Diman0** [comment]
Nice, testing images are pushed to mailuci again
https://hub.docker.com/r/mailuci/fetchmail/tags
You might have to refresh that page to see the latest tags.

**Review by nextgens — APPROVED** [review]
LGTM

**Pull request merged**
