### PR TITLE
Limiter implementation

### LINKED ISSUE #634: Ratelimit only failed authentications
currently the ratelimiting happens for all authentications, it would make much more sense to limit only if it's a brute-force == many failed logins

with the current implementation i get complains from some of my users who send (legitimate) newsletters and it feels wrong to set the limit higher because then brute-forcing is much easier

### LINKED ISSUE #1195: Better handling of authentication limit
As discussed in #301 and  #686 the auth limit causes trouble in some scenarios. A probably simple solution would be to only count failed authentications in this limit. To make it still work against brute-force attacks, the behavior should be like:

- If an auth fails, increment the counter
- If the counter is above a certain threshold, reject any auth (valid as well as invalid)
- Don't increment the counter for valid authentication requests

Edit:
- Webmail auth rate limit should be done at HTTP level in nginx so that the limit applies on a per-ip base.

### PR DESCRIPTION
**Pull request by micw**
## What type of PR?

(Feature, enhancement, bug-fix, documentation)

## What does this PR do?

Adds a custom limter based on the "limits" lirary that counts up on failed auths only

### Related issue(s)
- closes #1195
- closes #634

## Prerequistes

- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by kaiyou** [comment]
From my understanding of the limits module, because we do not want to reject legitimate imap clients that just open many connections (webmails), we should not raise when hit returns False, only when the check fails.

**Comment by micw** [comment]
Let's assume a limit of 3. With the current code users get:

invalid login 1 -> no limit exception
invalid login 2 -> no limit exception
invalid login 3 -> raises the exception on hit
valid login -> still a limit exeception

Or:
invalid login 1 -> no limit exception
invalid login 2 -> no limit exception
valid login -> login ok

If I don't raise on hit:

invalid login 1 -> no limit exception
invalid login 2 -> no limit exception
invalid login 3 -> no limit exception
valid login -> limit exeception

Or:
invalid login 1 -> no limit exception
invalid login 2 -> no limit exception
valid login -> login ok

Does not make much difference.

**Comment by kaiyou** [comment]
After rethinking it myself, because you only hit on error, the difference is negligeable indeed.

**Comment by kaiyou** [comment]
bors try

**Comment by micw** [comment]
@kaiyou Please have a look to https://github.com/alisaifee/flask-limiter/issues/234 - the author of the lib is about to add this function to the annotations. Does this help or do we still require a programmatic way (e.g. for rate-limiting mails and other things)?

**Comment by kaiyou** [comment]
I like your implementation for its simplicity and the fact that we can check the counter value in a fairly straightforward way.

 If they add the `penalty_condition` I think it would cover most cases. Using the library will be at the cost of a slightly more complex code though.

I would personally go for it and have them maintain the limiter logic then have us focus on delivering email :p

**Comment by kaiyou** [comment]
Anyway depending on the timeframe, we might still want to merge this PR in the meantime.

**Comment by micw** [comment]
From my side it can be merged. I put the roundcube limiter in a different PR.

**Comment by micw** [comment]
@Nebukadneza @kaiyou Can we go with that?

**Comment by kaiyou** [comment]
Yep, lets see if the test succeds then merge.

**Pull request merged**
