### PR TITLE
Prevent clamav from failing with HTTP429 when testing

### LINKED ISSUE #1784: BORS / Travis fails building due to sending too many requests to clamav
## Description
See the [travis logs](https://travis-ci.org/github/Mailu/Mailu/builds/762136308?utm_source=github_status&utm_medium=notification).
```
Tue Mar  9 13:30:29 2021 -> daily database available for download (remote version: 26103)
Tue Mar  9 13:30:32 2021 -> !The daily.cvd database downloaded from https://database.clamav.net is more than one version older than the version advertised in the DNS TXT record.
Tue Mar  9 13:30:32 2021 -> Trying again in 5 secs...
Tue Mar  9 13:30:37 2021 -> daily database available for download (remote version: 26103)
Tue Mar  9 13:30:37 2021 -> !downloadFile: Unexpected response (429) from https://database.clamav.net/daily.cvd
```
One of the tests that involve clamav requires clamav to download the latest virus definitions. Apparently we send too many requests to clamav since the clamav website responds with HTTP CODE 429: Too many requests.

We can resolve this by configuring clamav **not** to download the latest virus definitions. We could modify the test to use a static database file for clamav and not to check for updates. This way we do not send update requests to the https://database.clamav.net/daily.cvd site and we have eliminated one common cause for travis failing.

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?

enhancement

## What does this PR do?

See #1784 . We often have that builds fail due to hammering the clamav update software. When this happens, it is basically not possible anymore to perform more builds. This is a temporary solution to use a static database file when a test is run. This is done via an environment variable that is only set when testing. In normal situations the static DB file is removed on startup.

Ideally the CI/CD environment caches the clamav file. We cannot investigate this possibility until we have switched from Travis to the new environment. 

### Related issue(s)
- closes #1784

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
I still have to create the towncrier announcement.

**Comment by Diman0** [comment]
Discussed with @nextgens it makes much more sense to
- set a environment variable in travis that we are testing. This could be added to travis.yml so that it is explicitly clear that our tests depend on this environment variable. E.g. in the before_script: pass testing=true to the docker-compose file
``` - testing=true docker-compose -f tests/build.yml build```
- In the Docker-compose file pass the env variable as an argument to the build script
```
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-local}
    build: ../optional/clamav
      args:
        TESTING: $testing
```
- In the Dockerfile, only copy the test definitions if ARG TESTING equals true. 
- In the Dockerfile pass the value of arg TESTING as env variable to the image
- In the image (start.py) skip freshclam if env var TESTING=true.

**Comment by nextgens** [comment]
> Discussed with @nextgens it makes much more sense to
> 
>     * set a environment variable in travis that we are testing. This could be added to travis.yml so that it is explicitly clear that our tests depend on this environment variable. E.g. in the before_script: pass testing=true to the docker-compose file
>       ` - testing=true docker-compose -f tests/build.yml build`
> 
>     * In the Docker-compose file pass the env variable as an argument to the build script
> 
> 
> ```
>   antivirus:
>     image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-local}
>     build: ../optional/clamav
>       args:
>         TESTING: $testing
> ```
> 
>     * In the Dockerfile, only copy the test definitions if ARG TESTING equals true.
> 
>     * In the Dockerfile pass the value of arg TESTING as env variable to the image
> 
>     * In the image (start.py) skip freshclam if env var TESTING=true.

Yes, I was thinking to use one of Travis' built-in env variables instead of TESTING (say CI instead)
https://docs-staging.travis-ci.com/user/environment-variables/#default-environment-variables

**Comment by Diman0** [comment]
I will close this PR since we are moving to a different CI/CD. If required, we can create a new PR for this issue.

**Pull request closed without merging**
