### PR TITLE
Corrected ingress redirection loop error

### PR DESCRIPTION
**Pull request by hacor**
## What type of PR?

Enhancement

## What does this PR do?
It fixes the infinite redirect loops in Kubernetes Admin interface. 
The change is to add the complete uri string to the rewrite rule.

### Related issue(s)
#1021 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

I will pull this to master as well

### CODE REVIEW

**Comment by hoellen** [comment]
Is this a specific issue on 1.6? If not, can you please rebase this PR to master?

**Comment by hacor** [comment]
Created a PR #1045 on the master branch in favor of this one. 
Sorry for the delay!

**Comment by blinkeye** [comment]
Since you opened a new PR #1045 we could close this one?

**Comment by kaiyou** [comment]
Closing indeed.

**Comment by JavierAbrego** [comment]
these changes were lost and they are still needed

**Pull request closed without merging**
