### PR TITLE
Add password plugin

### PR DESCRIPTION
**Pull request by harveyconnor**
## What type of PR?

enhancement

## What does this PR do?
Adds password plugin so users can change their password within roundcube.
By going to Settings > Password.

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by lub** [comment]
Does this actually work? As far as I can see you'd also have to supply the password plugin settings to set the password directly in the database in the same format as the admin gui.

https://github.com/roundcube/roundcubemail/blob/master/plugins/password/config.inc.php.dist

Also I don't know if it makes sense to support two ways to change the password, because e.g. when 2fa gets implemented due to #783 you maybe want to verify the second factor during password changes.
Or when you login with an authentication token you shouldn't be able to change your password with it, because that would defeat the purpose of the authentication token. I'm not sure if roundcube could differentiate that.

**Comment by Diman0** [comment]
As lub already stated, this will not work. This plugin requires additional configuration. The password is stored in the database.  

The admin web interface is the main interface for changing user settings including the password. I'm not certain if we want to allow other services than admin to change user passwords.

**Comment by harveyconnor** [comment]
okay makes sense. I think it would be a good option for the user to have some control over that password.

**Comment by lub** [comment]
Users should be able to change the password themselves via admin, when you actually expose the admin interface to them.

**Comment by Diman0** [comment]
The web administration interface is not only meant for administrators. Each user can change user preferences via the web administration interface. Users are also able to change their password via the web administration interface.

Unfortunately the web administration interface is not documented. This includes what settings can be configured by normal users (such as your password). The PR to add this to the documentation is pending (https://github.com/Mailu/Mailu/pull/1592). You can read more here.

**Comment by harveyconnor** [comment]
ahh okay well that makes sense then. I'll let my users know that they can do that.

**Pull request closed without merging**
