### PR TITLE
Apply DEFAULT_QUOTA to user creation admin ui page

### PR DESCRIPTION
**Pull request by PMExtra**
## What type of PR?

Feature

## What does this PR do?

Apply `DEFAULT_QUOTA` settings to user creation admin ui page.

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] ~In case of feature or enhancement: documentation updated accordingly~
- [ ] ~Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.~

I'm sorry for that I'm not good at English to update the documentation. But this is not a completed new feature. `DEFAULT_QUOTA` is an existing configuration. I just completed the behaviors. Although this configuration was never documented.

### CODE REVIEW

**Comment by PMExtra** [comment]
bors retry

**Comment by Diman0** [comment]
bors try

**Review by Diman0 — DISMISSED** [review]
In the future, please first open an issue. This allows discussion before a pull request is created. 

A changelog entry is missing. See https://mailu.io/1.9/contributors/workflow.html#changelog for more details.

This setting must also be documented in configuration.rst.

**Comment by ghostwheel42** [comment]
> This setting must also be documented in configuration.rst.

`DEFAULT_QUOTA` is not new. This is just a bug-fix.
But yes, it should be documented.

**Review by ghostwheel42 — APPROVED** [review]
Thanks. LGTM

**Review by Diman0 — APPROVED** [review]
lgtm

**Pull request merged**
