### PR TITLE
implement DNS Blacklists #336

### PR DESCRIPTION
**Pull request by morbidick**
This is a very basic implementation. I tested the template generation but couldn't test it "in the wild" with incoming  mails since i have no public setup yet. I'm not sure if postfix will check against the nginx proxy ip or the real client ip.

If the change itself is good i would add more documentation and will try to find some more public blacklists (most are only for private use).

### CODE REVIEW

**Comment by kaiyou** [comment]
The PR looks basically good :)

Just some thinking: does this need to be implemented in Postfix or Rspamd? The semantic would be different of course. Implementing it in Postfix means an actual blacklist while implementing it in Rspamd has more of a "spam" flavor.

I think I would feel better with it implemented in Rspamd, but then if the semantic is really that of a blacklist, is there a way to enforce email rejection?

For details: https://rspamd.com/doc/modules/rbl.html

**Comment by ripkens** [comment]
Please make sure, if querying those blacklists, dont use public dns resolvers like google dns.
The lists use a fair use policy and blocks dns queries if queried to often.

Implement a local resolver to avoid query limits like dnsmasq or unbound dns.
At least mention in the wiki, to use the ISP dns or a docker dns server and not google dns.

**Comment by kaiyou** [comment]
Adding something to the documentation is a nice first step. Then, at some point maybe we could embed a dnsmasq for this sort of thing but it sounds overkill at this point.

**Comment by morbidick** [comment]
implementing the same functionality with rspamd is still on my todo list, but havent found the time yet. So i gonna close this PR for now.

**Pull request closed without merging**
