### PR TITLE
update Dockerfile to alpine 3.14.3

### PR DESCRIPTION
**Pull request by willofr**
## What type of PR?
Security fix

## What does this PR do?
Updated the Dockerfile to use the latest alpine version 3.14.3 where several CVEs have been fixed: https://alpinelinux.org/posts/Alpine-3.14.3-released.html
New images successfully built on my test env.

### Related issue(s)
None

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
@nextgens @ghostwheel42 
The list of changes can be found here:
https://www.alpinelinux.org/posts/Alpine-3.14.3-released.html

Do we want to include this with 1.9? Or is it likely to introduce new issues again in Mailu?
We need to test it thoroughly before accepting. The last 2 times we upgrade alpine it introduced new issues.
We could also opt to backport this after 1.9. This gives more time for testing.

**Comment by nextgens** [comment]
I'd refrain from merging it one day before the scheduled code-freeze

**Comment by Diman0** [comment]
> I'd refrain from merging it one day before the scheduled code-freeze

I concur. We can remove the blocked label once 1.9 is released.

**Review by nextgens — APPROVED** [review]
LGTM

**Review by Diman0 — APPROVED** [review]
LGTM. 
CI/CD succeeded. So all core functionality such as sending/receiving emails work correctly.
Brave people who run on master can tell us if this newer Alpine release introduced new issues.

**Pull request merged**
