### PR TITLE
Upgrade alpine, make setup use the base image

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

Upgrade alpine, make setup use the base image, introduce a health-check, drop privileges. Drop privileges on admin too.

It may or may not help #2536

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
See if it helps with the warnings.
bors try

**Comment by nextgens** [comment]
Ask bors if that broke anything.

bors try

**Comment by nextgens** [comment]
Try the new test too.

bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by Diman0** [comment]
bors try

It looks good to me. I will do some smoke testing before approving it.

**Review by Diman0 — CHANGES_REQUESTED** [review]
admin uses /mailu/data.
fetchmail uses /mailu/data/fetchmail
So the chown for admin, changes the file permissions for fetchmail. It appears not to result in problematic issues for fetchmail. The real solution is to use `/mailu/data/admin` for admin in my opinion. Of course this means I must mention in the release notes that users must manually mv these files when upgrading to the new mailu version. If you choose to do this, the newsfragment should also warn about this.

For rspamd we must also use chown to change permissions for the host mounted folders:
- /var/lib/rspamd (filter folder in mailu data folder)
  - os.system("chown rspamd:rspamd -R /var/lib/rspamd")
  - a problem is that antivirus uses the EXACT same folder /mailu/filter. Maybe this PR is the time to introduce the folder /mailu/filter/antivirus & /mailu/filter/fetchmail?
- /etc/rspamd/override.d (/overrides/rspamd in mailu data folder
  - os.system("chown rspamd:rspamd -R /etc/rspamd/override.d")
  - This is currently not possible, because we mount  the overrides folder as read-only. We could ignore this and then it is the user's problem to make sure it is readable? Or we could remove the :ro flag on the host mount.

**Comment by nextgens** [comment]
I have done the minimum in 44c4758; I suggest we rethink the folder hierarchy and instruction to users in another PR

bors try

**Comment by nextgens** [comment]
bors try

**Review by Diman0 — APPROVED** [review]
lgtm

**Pull request merged**
