### PR TITLE
Upgrading to a 2048-bit DKIM key

### PR DESCRIPTION
**Pull request by radtkedev**
## What type of PR?

Enhancement

## What does this PR do?

Upgrades to a 2048-bit DKIM key from the currently used and outdated 1024-bit DKIM key.

### Related issue(s)
- #1301

### CODE REVIEW

**Comment by kaiyou** [comment]
As stated in the issue, we should check that this does not affect DNS records. Are they still short enough to fit in a single record?

**Comment by kaiyou** [comment]
Here is an example article mentioning the issue: http://hack.limbicmedia.ca/how-to-split-dns-dkim-records-properly/

**Comment by HorayNarea** [comment]
> Are they still short enough to fit in a single record?

I'm using 2048-bit DKIM keys on a non-Mailu server in a single record just fine, so yeah!

4096-bit keys would be the harder case because then it doesn't fit in a single record _and_ is bigger then DNS over UDP without EDNS0 allows :sweat_smile:

**Comment by kaiyou** [comment]
Okay, then we are a go.

**Pull request merged**
