### PR TITLE
Address sender restrictions to avoid forged mail

### PR DESCRIPTION
**Pull request by ribeiromiranda**
## What type of PR?

enhancement

## What does this PR do?
Add address sender restrictions to avoid forged mail.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by ribeiromiranda** [comment]
@nextgens  Do not send email when the sender does not exist.

**Comment by nextgens** [comment]
Mailu already prevents unknown senders from sending emails... except in the case of of hosts in RELAYNETS for which it's assumed that they do their own checking.

Can you give a concrete example of what you are trying to do?

**Comment by ribeiromiranda** [comment]
I had a problem with spam without this option to check if the sender exists.

Even a user without login was able to send emails generating fake emails.
For example: xxxxx@domainname.com, where domainname.com is the main email domain

**Comment by nextgens** [comment]
The line ```smtpd_sender_login_maps = ${podop}senderlogin``` in main.cf ensures that Mailu gets its say on what the sender can be.

Please detail your configuration, how you were sending the email and related logs

**Comment by ribeiromiranda** [comment]
Generate a example
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:25:25"
      - "127.0.0.1:465:465"
      - "127.0.0.1:587:587"
      - "127.0.0.1:110:110"
      - "127.0.0.1:995:995"
      - "127.0.0.1:143:143"
      - "127.0.0.1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/dav:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data/fetchmail:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Webmail

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=S0YX72GDQH1CGDDE

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=domainname.com

# Hostnames for this server, separated with comas
HOSTNAMES=domainname.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=notls

# Authentication rate limit per IP (per /24 on ipv4 and /56 on ipv6)
AUTH_RATELIMIT_IP=60/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=100/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=false

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, lz4, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=

# Path to the admin interface if enabled
WEB_ADMIN=

# Path to the webmail if enabled
WEB_WEBMAIL=

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mailu.io



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```

```
telnet 127.0.0.1 25
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
220 domainname.com ESMTP ready
EHLO domainname.com
250-domainname.com
250-PIPELINING
250-SIZE
250-50000000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
MAIL FROM: <invalid-email@domainname.com>
250 2.0.0 OK
RCPT TO:<valid-email@gmail.com>       
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
From: Me <invalid-email@domainname.com>  
To: Him <valid-email@gmail.com>
Subject: This is a testing mail
This message is only sent for testing purposes.
.
250 2.0.0 Ok: queued as 49D81BCE2AB
QUIT
221 2.0.0 Bye
```


> 2022-01-19T12:35:23.723511+00:00 5b132b9bb948 postfix[111]: Postfix is running with backwards-compatible default settings
> 2022-01-19T12:35:23.723521+00:00 5b132b9bb948 postfix[111]: See http://www.postfix.org/COMPATIBILITY_README.html for details
> 2022-01-19T12:35:23.723527+00:00 5b132b9bb948 postfix[111]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
> 2022-01-19T12:35:23.954713+00:00 5b132b9bb948 postfix[326]: Postfix is running with backwards-compatible default settings
> 2022-01-19T12:35:23.954724+00:00 5b132b9bb948 postfix[326]: See http://www.postfix.org/COMPATIBILITY_README.html for details
> 2022-01-19T12:35:23.954730+00:00 5b132b9bb948 postfix[326]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
> 2022-01-19T12:35:24.137487+00:00 5b132b9bb948 postfix/postfix-script[390]: starting the Postfix mail system
> 2022-01-19T12:35:24.143204+00:00 5b132b9bb948 postfix/master[391]: daemon started -- version 3.6.3, configuration /etc/postfix
> 2022-01-19T12:38:48.324927+00:00 5b132b9bb948 postfix/smtpd[403]: connect from mailu-front-1.mailu_default[192.168.203.6]
> 2022-01-19T12:38:48.325792+00:00 5b132b9bb948 postfix/smtpd[403]: lost connection after MAIL from unknown[192.168.203.1]
> 2022-01-19T12:38:48.325870+00:00 5b132b9bb948 postfix/smtpd[403]: disconnect from unknown[192.168.203.1] ehlo=1 xclient=0/1 mail=0/1 commands=1/3
> 2022-01-19T12:39:55.235123+00:00 5b132b9bb948 postfix/smtpd[403]: connect from mailu-front-1.mailu_default[192.168.203.6]
**> 2022-01-19T12:39:55.302572+00:00 5b132b9bb948 postfix/smtpd[403]: 49D81BCE2AB: client=unknown[192.168.203.1]
> 2022-01-19T12:40:33.590289+00:00 5b132b9bb948 postfix/cleanup[478]: 49D81BCE2AB: message-id=<>
> 2022-01-19T12:40:34.806780+00:00 5b132b9bb948 postfix/qmgr[393]: 49D81BCE2AB: from=<invalid-email@valid-domain.com>, size=374, nrcpt=1 (queue active)
> 2022-01-19T12:40:37.160686+00:00 5b132b9bb948 postfix/smtp[490]: connect to gmail-smtp-in.l.google.com[2800:3f0:4003:c00::1a]:25: Address not available
> 2022-01-19T12:40:44.546810+00:00 5b132b9bb948 postfix/smtpd[403]: disconnect from unknown[192.168.203.1] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
> 2022-01-19T12:41:07.190034+00:00 5b132b9bb948 postfix/smtp[490]: connect to gmail-smtp-in.l.google.com[64.233.186.27]:25: Operation timed out
> 2022-01-19T12:41:37.210226+00:00 5b132b9bb948 postfix/smtp[490]: connect to alt1.gmail-smtp-in.l.google.com[64.233.184.27]:25: Operation timed out
> 2022-01-19T12:41:37.210263+00:00 5b132b9bb948 postfix/smtp[490]: connect to alt1.gmail-smtp-in.l.google.com[2a00:1450:400c:c0b::1b]:25: Address not available
> 2022-01-19T12:41:37.215397+00:00 5b132b9bb948 postfix/smtp[490]: connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4013:c16::1b]:25: Address not available
> 2022-01-19T12:41:37.358086+00:00 5b132b9bb948 postfix/smtp[490]: 49D81BCE2AB: to=<valid-email@gmail.com>, relay=none, delay=102, delays=40/0.02/62/0, dsn=4.4.1, status=deferred (connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4013:c16::1b]:25: Address not available)**

To avoid send e-mail and checking spam using "smtpd_sender_restrictions"

**Comment by nextgens** [comment]
Okay, so I can see two things that are wrong:
1) you're doing the test from localhost: a host that is in RELAYNETS by default (and that you can't remove easily). Try connecting from a different IP address and this shouldn't work
2) your DOMAIN and HOSTNAMES are the same; HOSTNAMES should be hostname.example.org

**Pull request closed without merging**
