### PR TITLE
Fixing AUTH_RATELIMIT_IP not working on imap/pop3/smtp

### LINKED ISSUE #2283: AUTH_RATELIMIT_IP not working on imap/pop3/smtp
### Environment
 - [x] docker-compose
 - [x] kubernetes
 - [x] docker swarm (not tested)

### Versions
- 1.9

## Description
Currently, `AUTH_RATELIMIT_IP` seems to have no effect when logging in using imap/pop3/smtp.

## Replication Steps
1. Start a new (local) mailu server (no certs needed) using the web generator and set `AUTH_RATELIMIT_IP` to `3/hour`.
2. `telnet localhost 143` -> `login nobody@example.com PASSWORD`
3. repeat step 2 three times.

## Expected behaviour
On the last login, the server should respond with `. NO Temporary authentication failure (rate-limit)`.
Instead, it's possible to to repeat the login attempt, until `AUTH_RATELIMIT_USER` hits. 

## Additional information
When the user gets into `AUTH_RATELIMIT_IP` using the web interface, imap/pop3/smtp login attempts are stopped as expected.

## Logs
```
❯ telnet localhost 143
Telnet escape character is '^Q'.
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^Q'.
* OK IMAP4 ready
. login nobody@example.com PASSWORD
. NO Authentication credentials invalid
Connection closed by foreign host.
❯ telnet localhost 143
Telnet escape character is '^Q'.
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^Q'.
* OK IMAP4 ready
. login nobody@example.com PASSWORD
. NO Authentication credentials invalid
Connection closed by foreign host.
❯ telnet localhost 143
Telnet escape character is '^Q'.
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^Q'.
* OK IMAP4 ready
. login nobody@example.com PASSWORD
. NO Authentication credentials invalid
Connection closed by foreign host.
❯ telnet localhost 143
Telnet escape character is '^Q'.
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^Q'.
* OK IMAP4 ready
. login nobody@example.com PASSWORD
. NO Authentication credentials invalid
Connection closed by foreign host.
```

I'll provide a PR.

### PR DESCRIPTION
**Pull request by fischerscode**
#2283

## What type of PR?

bug-fix

## What does this PR do?
This fixes AUTH_RATELIMIT_IP not working on imap/pop3/smtp.

### Related issue(s)
closes #2283

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by fischerscode** [comment]
The `=="True"` is needed, since the headers are converted to Strings two lines above.
I am not too familiar with python, so maybe there is a better solution for this, but it works.

**Comment by fischerscode** [comment]
### For 1.9:
https://github.com/Mailu/Mailu/blob/36eaa0d16eebdb316570fbe8ec8594042022badd/core/admin/mailu/internal/nginx.py#L97
has to be changed to `is_valid_user = user is not None` as well.

**Comment by fischerscode** [comment]
bors try

**Comment by nextgens** [comment]
Doh.

> Edit: Should I create a PR to the 1.9 branch, too?

mergify will do that for us; We just need to add a commit to it

**Review by nextgens — DISMISSED** [review]
LGTM

**Review by ghostwheel42 — APPROVED** [review]
lgtm

**Comment by ghostwheel42** [comment]
bors try

**Review by ghostwheel42 — APPROVED** [review]
lgtm

**Review by Diman0 — APPROVED** [review]
Lgtm

**Pull request merged**
