### PR TITLE
Roundcube: Add defaults.inc.php and remove mails from Junk immediately

### PR DESCRIPTION
**Pull request by Farthen**
Moving mails from Junk to Trash will mark them all as ham. See issue #474. To mitigate
this problem at least in roundcube, this config option is required.

### CODE REVIEW

**Comment by kaiyou** [comment]
Mmmh, why can't this be configured in ``config.php``?

**Comment by muhlemmer** [comment]
The right fix is already implemented in PR #510, which is merged. Issue #474 is also closed.

@Farthen (or @kaiyou), I my opinion this PR can be closed as well.

**Comment by kaiyou** [comment]
I agree, just waiting for @Farthen to confirm if all aspects of the PR are indeed already handled by #510 :)

**Comment by kaiyou** [comment]
I'll close, @Farthen, feel free to comment and/or reopen in any case.

**Pull request closed without merging**
