### PR TITLE
Update traefik-certs-dumper

### PR DESCRIPTION
**Pull request by YouriT**
## What type of PR?

bug-fix

## What does this PR do?

Remove a useless dependency & update the command line according to the [latest ldez/traefik-certs-dumper documentation](https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md).

### CODE REVIEW

**Comment by YouriT** [comment]
I made this change because I was unable to have the cert-dumper to work properly (as in the docs).

**Comment by kaiyou** [comment]
I am unable to test but the code looks okay. If anyone can confirm this works fine, I think we can merge quickly.

**Comment by muhlemmer** [comment]
@YouriT, I've re-enabled building of certdumper by reverting an earlier commit. I had to push to your branch in order to test your changes.

If you choose to contribute more in the future, may I suggest you use a different branch as `master` on your own fork. Because:

1. Reviewers are able to change code in the PR-ed branch. This means I or anybody on the team can write to your master. This can end up weird if you are using your own master for production.
2. Now that you (and I) commited to your `master` branch, you won't be able to do a fast-forward merge anymore. So any new branches from your `master` will be contaminated with additional commits, making it difficult to merge future pull requests.

It is not obligated, but just a suggestion to make live easier ;)

**Comment by muhlemmer** [comment]
Since the change is small I will let bors to merge it after 1 review.

bors +r

**Comment by YouriT** [comment]
@muhlemmer thanks for the comment. I just did something quick and dirty don't worry, I'll pull mailu:master and force push it to mine if needed. I was not using my own version, just dropped in a Dockerfile in my folder and built it myself, then did a little PR to facilitate life to people trying out the same.

Thanks for merging!

**Pull request merged**
