### PR TITLE
Add 1.8 to the release-list displayed in 1.7 docs

### PR DESCRIPTION
**Pull request by Nebukadneza**
## What type of PR?
bug-fix

### Related issue(s)
- related: #1653

### CODE REVIEW

**Review by lub — APPROVED** [review]
lgtm

**Review by Diman0 — CHANGES_REQUESTED** [review]
1.5 must be removed. This version is not available anymore.

**Review by Diman0 — APPROVED** [review]
Lgtm

**Comment by Diman0** [comment]
bors retry

**Pull request merged**
