### PR TITLE
Use dovecot-proxy

### LINKED ISSUE #2848: Client-Port HTTP header not expanded
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description
I'm currently trying to troubleshoot an issue in Mailu between nginx and postfix. I used `tcpdump` to dump some traffic and noticed that the HTTP headers sent by nginx to Mailu are not expanded correctly. This is most likely unrelated to my actual problem and I don't think it is currently causing any issues, but it might be worth fixing anyway. Here is the observed traffic between nginx and the email auth endpoint:

```
GET /internal/auth/email HTTP/1.0
Host: admin
Connection: close
Auth-Method: plain
Auth-User: [redacted]
Auth-Pass: [redacted]
Auth-Protocol: smtp
Auth-Login-Attempt: 1
Client-IP: [redacted]
Client-Host: [redacted]
Auth-SSL: on
Auth-SSL-Protocol: TLSv1.2
Auth-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Auth-Port: 465
Client-Port: $remote_port

HTTP/1.0 200 OK
Server: gunicorn
Date: Mon, 05 Jun 2023 20:31:11 GMT
Connection: close
Content-Type: text/html; charset=utf-8
Auth-Status: OK
Auth-Server: 192.168.203.6
Auth-User: [redacted]
Auth-User-Exists: True
Auth-Port: 10025
Content-Length: 0


```
## Replication Steps
Log in to a Mailu instance via its nginx `front` container.

## Observed behaviour
The `Client-Port` request header is set to `$remote_port`.

## Expected behaviour
The `Client-Port` header should contain the actual port, not the variable name.

## Logs
See HTTP dump

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

Use dovecot-proxy instead of nginx's mail module.

This will be required if we want to have BURL, XOAUTH2 or HA/load-balancing (with more than one IMAP instance).

pros:
- fixes $remote_port

cons:
- seems to break SSL resumption

### Related issue(s)
- closes #2848

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Review by Diman0 — APPROVED** [review]
LGTM

**Pull request merged**
