### PR TITLE
Interface cosmetics

### LINKED ISSUE #2570: Small feature - add mailu version in the admin UI
Add mailu version in the admin UI 
I think it would nice to be able to see which version of mailu we are running, unless there is other simple way?

Thanks

### PR DESCRIPTION
**Pull request by ghostwheel42**
## What type of PR?

enhancement, bug-fix

## What does this PR do?

- add default sort order to all tables
- repair sliders
- add quota in list
- improve mailu logo in roundcube webmail when using responsive skin
- show version in the footer (after login)

### Related issue(s)

- closes #2570

### CODE REVIEW

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
I think I'll introduce a MAX_QUOTA config setting to allow changing the maximum when creating a domain.
I'll also implement the max_quota_bytes workaround introduced for users to the domain edit dialog.

**Review by nextgens — APPROVED** [review]
LGTM

**Pull request merged**
