### PR TITLE
Support domain literals (fix #1087)

### LINKED ISSUE #1087: MAIL FROM: does-not-exist@[X.X.X.X] results in an admin exeption stacktrace
If a client (read: malicious attacker) connects to Postfix and uses an IP address within brackets instead of a domain name for the sender, e.g.:

```
$ telnet mail.example.com 25

Connected to example.com
Escape character is '^]'.
220 mail.example.com ESMTP ready
EHLO dummy.example.com
250-mail.example.com
250 STARTTLS
MAIL FROM: does-not-exist@[116.203.165.200]
250 2.0.0 OK
RCPT TO: some-user@example.com
451 4.3.0 <does-not-exist@[116.203.165.200]>: Temporary lookup failure
```

we see the following stracktrace in the admin container:

```
[2019-07-27 14:26:27,015] ERROR in app: Exception on /internal/postfix/domain/[116.203.165.200] [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 271, in alabel
    ulabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 307, in ulabel
    check_label(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 261, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+005B at position 1 of '[116' not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 669, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1182, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 30, in process_bind_param
    return idna.encode(value).decode("ascii").lower()
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 361, in encode
    s = alabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 273, in alabel
    raise IDNAError('The label {0} is not a valid A-label'.format(label))
idna.core.IDNAError: The label b'[116' is not a valid A-label

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/mailu/internal/views/postfix.py", line 9, in postfix_mailbox_domain
    domain = models.Domain.query.get(domain_name) or \
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 924, in get
    ident, loading.load_on_pk_identity)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1007, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 250, in load_on_pk_identity
    return q.one()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2954, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
    None, None)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 669, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1182, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 30, in process_bind_param
    return idna.encode(value).decode("ascii").lower()
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 361, in encode
    s = alabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 273, in alabel
    raise IDNAError('The label {0} is not a valid A-label'.format(label))
sqlalchemy.exc.StatementError: (idna.core.IDNAError) The label b'[116' is not a valid A-label [SQL: 'SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled \nFROM domain \nWHERE domain.name = ?'] [parameters: [{'%(140312238936248 param)s': '[116.203.165.200]'}]]
10.36.0.0 - - [27/Jul/2019:14:26:27 +0000] "GET /internal/postfix/domain/%5B116.203.165.200%5D HTTP/1.1" 500 291 "-" "Python/3.7 aiohttp/3.5.4"
10.44.0.0 - - [27/Jul/2019:14:26:31 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"
```

NOTE: the lookup is cached I think and you need to use another IP address to reproduce the error multiple times.

I think we're missing some validation rules, because trying a similar (invalid) MAIL FROM with an IP (but without brackets) is handled properly:

```
telnet mail.example.com 25
Trying ...
Connected to example.com.
Escape character is '^]'.
220 mail.example.com ESMTP ready
EHLO dummy.example.com
250-mail.example.com
250 STARTTLS
MAIL FROM: does-not-exist@192.168.1.1
250 2.0.0 OK
RCPT TO: some-user@example.com
501 5.1.7 Bad sender address syntax
Connection closed by foreign host.
```

### PR DESCRIPTION
**Pull request by hoellen**
## What type of PR?
bug-fix

## What does this PR do?
This PR adds error handling for idna enocding. With telnet you now get a "Bad sender address syntax"  message.

```
> telnet mail.example.com 25

Connected to example.com.
Escape character is '^]'.
220 mail.example.com ESMTP ready
EHLO dummy.example.com
250-mail.example.com
250 STARTTLS
MAIL FROM: does-not-exist@[116.203.165.200]
250 2.0.0 OK
RCPT TO: some-user@example.com
501 5.1.7 Bad sender address syntax
Connection closed by foreign host.
```

### Related issue(s)
fix #1087

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by blinkeye** [comment]
Thanks @hoellen for the super fast fix! May I ask what the expected behaviour is? I assume from your comment and what I would expect is that the smtp session should be aborted (with a `501 5.1.7 Bad sender address syntax` message).

What happens is that if you cherry-pick your fix on the 1.6/master is that I can now actually deliver such mails from:
```
Delivered-To: <todo@example.com>
Return-Path: <antispam@[116.203.165.200]>
Received: from mail.example.com ([10.36.0.0])
	by mail.example.com with LMTP
	id 7Yb8D6vIPV2VVgAAJxq3yg
	(envelope-from <antispam@[116.203.165.200]>)
	for <me@example.com>; Sun, 28 Jul 2019 16:09:15 +0000
Received: from my-server.example.com (unknown [116.203.165.100])
	by mail.example.com (Postfix) with ESMTP id 86D3117C1EC
	for <todo@example.com>; Sun, 28 Jul 2019 16:09:14 +0000 (UTC)
From: <antispam@[116.203.165.200]>
To: <todo@example.com>
Subject: Testing SMTP Mail
X-Spamd-Bar: ++++++++++++
X-Spam-Level: ************
X-Rspamd-Server: mailu-security-676dcfc9df-jrtkl
Authentication-Results: mail.example.com;
	dkim=none;
	dmarc=none;
	spf=none (mail.example.com: domain of antispam@[116.203.165.200] has no SPF policy when checking 116.203.165.100) smtp.mailfrom=antispam@[116.203.165.200]
X-Rspamd-Queue-Id: 86D3117C1EC
X-Spamd-Result: default: False [12.84 / 15.00];
X-Spam: Yes

This is only a test. Please do not panic. If this works, then all is well, else all is not well.
```

**Comment by hoellen** [comment]
Yeah in my tests I accidentally used an IP address, which does not exist (> 255). That is the reason I got an `501 5.1.7 Bad sender address syntax`.

`antispam@[116.203.165.200]` is a valid email address for postfix. With the square brackets postfix interprets it as an IP address. That's the reason why it rejects e.g. `localpart@[116.203.165.300]`.

This behavior is also used for transport table. `man 5 transport`:
> The interpretation of the nexthop field is transport dependent. In the case of SMTP, specify a service on a non-default port as host:service, and disable MX (mail exchanger) DNS lookups with [host] or [host]:port. The [] form is required when you specify an IP address instead of a hostname.

<br>
This PR fixes the stack trace produced by the admin container.

**Comment by kaiyou** [comment]
My question now: if the encoding error is ignored, what will the binding return? Probably None. How is this interpreted by SQLAlchemy?

I feel kind if uncomfortable passing irrelevant data to the database query unless we are absolutely certain the query will return zero result.

For instance, what about an update query from the admin including an invalid domain name? Will it now replace the domain part with null?

**Comment by hoellen** [comment]
As discussed in matrix, we only consider domain literals in the internal views now (not catch exceptions from IDNA encoding). So we still get stacktraces if something goes wrong.

**Comment by kaiyou** [comment]
Sounds a lot better to me, I fail to understand the second regex though. Does it even compile?

**Comment by hoellen** [comment]
Indeed there was a backslash missing, but it worked anyway. I probably cleaned up too much... 

The second regex `(^|.*@)\[.*\]$` is for two different kind of inputs:
1. starting with bracket (like the first regex): `[1.1.1.1]`
2. query an email address: `user@[1.1.1.1]`

**Comment by blinkeye** [comment]
I cherry-picked the PR here onto a `release/1.6` branch but don't see a change of behaviour. I still get:
```
2019-09-29 15:06:05,676] ERROR in app: Exception on /internal/postfix/sender/access/does-not-exist@[116.203.165.200] [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 271, in alabel
    ulabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 307, in ulabel
    check_label(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 261, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+005B at position 1 of '[116' not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 669, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1182, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 30, in process_bind_param
    return idna.encode(value).decode("ascii").lower()
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 361, in encode
    s = alabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 273, in alabel
    raise IDNAError('The label {0} is not a valid A-label'.format(label))
idna.core.IDNAError: The label b'[116' is not a valid A-label

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/mailu/internal/views/postfix.py", line 56, in postfix_sender_access
    localpart, domain_name = models.Email.resolve_domain(sender)
  File "/app/mailu/models.py", line 263, in resolve_domain
    alternative = Alternative.query.get(domain_name)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 924, in get
    ident, loading.load_on_pk_identity)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1007, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 250, in load_on_pk_identity
    return q.one()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2954, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
    None, None)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 669, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1182, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 30, in process_bind_param
    return idna.encode(value).decode("ascii").lower()
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 361, in encode
    s = alabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 273, in alabel
    raise IDNAError('The label {0} is not a valid A-label'.format(label))
sqlalchemy.exc.StatementError: (idna.core.IDNAError) The label b'[116' is not a valid A-label [SQL: 'SELECT alternative.created_at AS alternative_created_at, alternative.updated_at AS alternative_updated_at, alternative.comment AS alternative_comment, alternative.name AS alternative_name, alternative.domain_name AS alternative_domain_name \nFROM alternative \nWHERE alternative.name = ?'] [parameters: [{'%(140430874646680 param)s': '[116.203.165.200]'}]]
```

**Comment by kaiyou** [comment]
This sounds like a similar but slightly different issue related to sender access (i.e. endpoints that are called in different contexts). Could you open a dedicated issue? It will need fixing in all releases.

**Pull request merged**
