### PR TITLE
Update alpine-linux to 3.14.4 - OpenSSL security FIX

### PR DESCRIPTION
**Pull request by willofr**
## What type of PR?
Security fix

## What does this PR do?
Update Dockerfiles to use alpine-linux 3.14.4 which contains a security fix for openssl
https://alpinelinux.org/posts/Alpine-3.12.10-3.13.8-3.14.4-released.html

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
bors try

**Review by ghostwheel42 — APPROVED** [review]
lgtm

**Review by Diman0 — APPROVED** [review]

**Pull request merged**
