### PR TITLE
Add Belarusian translation.

### PR DESCRIPTION
**Pull request by spoooyders**
## What type of PR?

Translation.

## What does this PR do?
Adds Belarusian translation.

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
bors try

**Review by Diman0 — CHANGES_REQUESTED** [review]
Thank you for your contribution. Can you also add a translation for the text string `Current password`?

https://github.com/Mailu/Mailu/blob/efb3892b09655ee8890571ba828ad51fa16f04be/core/admin/mailu/ui/forms.py#L134
https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/ui/templates/user/password.html

This text string is shown on the password update page. The URL for accessing this page is:
https://myhostname.com/myuser(thelocalpart)/user/password
E.g. if your login is `example@mailu.io` and the hostname is `mailu.io`:
https://mailu.io/example/user/password

**Review by Diman0 — DISMISSED** [review]
The same applies for the text string `Download zonefile`

https://github.com/Mailu/Mailu/blob/efb3892b09655ee8890571ba828ad51fa16f04be/core/admin/mailu/ui/templates/domain/details.html#L19

This string is used on the Domain details page:
https://example.com/admin/domain/details/mailu.io
where mailu.io is the mail domain

**Comment by Diman0** [comment]
Both untranslated text strings are new in the upcoming release and have not been translated yet in any of the other languages. That is why you missed these.

**Comment by Diman0** [comment]
On the user edit page (https://example.com/admin/user/edit/admin@mailu.io) you are also missing the translations for:
* Force password change at next login
* Allow the user to spoof the sender (send email as anyone)

You can translate the earlier mentioned missing translations via:
```
#: mailu/ui/templates/domain/details.html:19
msgid "Download zonefile"
msgstr "translation of Download zonefile"

#: mailu/ui/forms.py:134
msgid "Current password"
msgstr "translation of Current password"

#: mailu/ui/forms.py:102
msgid "Force password change at next login"
msgstr "translation of Allow the user to spoof the sender (send email as anyone)"

#: mailu/ui/forms.py:98
msgid "Allow the user to spoof the sender (send email as anyone)"
msgstr "translation of Allow the user to spoof the sender (send email as anyone)"
```

**Comment by Diman0** [comment]
You are correct. Only maintainers can trigger a build. You can test the new build using tag pr-3207
Ghcr.io/Mailu/admin:pr3207

Bors try

**Comment by Diman0** [comment]
> @Diman0 I verified it, everything looks good.

Thank you for the confirmation. It also looks good to me. At least that the interface is translated to a different language than English. I don't speak Belarusian so I trust the translation is correct.

**Review by Diman0 — APPROVED** [review]
LGTM

**Review by nextgens — APPROVED** [review]

**Pull request merged**
