### PR TITLE
Add button to mailu-admin in roundcube task menu

### PR DESCRIPTION
**Pull request by ghostwheel42**
## What type of PR?

feature

## What does this PR do?

Adds a button to the roundcube interface. This button gets you back to the admin interface.

### Related issue(s)
- Replaces  #2367

### CODE REVIEW

**Comment by ghostwheel42** [comment]
bors try

**Review by nextgens — DISMISSED** [review]
I don't see the icon here.

image
image
image

**Comment by ghostwheel42** [comment]
Ah, yes. The dockerfile is missing...

**Comment by ghostwheel42** [comment]
bors try

**Review by nextgens — APPROVED** [review]
LGTM

**Pull request merged**
