### PR TITLE
Make ratelimit exemptions less generous

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

enhancement

## What does this PR do?

Make ratelimit exemptions less generous, as discussed on #mailu-dev

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors try-

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
In fact there is no good rationale for applying the rate-limits on port 25: it's either:
- non-authenticated (email-delivery) and we should let postfix handle it
- authenticated (a password spraying/bruteforce attempt from bots)

bors try

**Review by Diman0 — APPROVED** [review]
LGTM

**Pull request merged**
