### PR TITLE
Format python, rst and yml source with pre-commit hook

### LINKED ISSUE #1839: Use code lint / formating for python
The python codebase would benefit from linters and formater. I suggest to add black and pylint/flake8 as additional CI breaker steps.

### PR DESCRIPTION
**Pull request by parisni**
## What type of PR?

Feature

## What does this PR do?

This provide a pre-commit hook to format every source the same way for each commit. The existing source have been reformated. Note that this will affect `git blame` and this commit should be hidden accordingly in a other PR.

This PR does not deal with lint which need many modification in the source, and will be addressed later

### Related issue(s)

- closes #1839

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [X] In case of feature or enhancement: documentation updated accordingly
- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
IMHO this should be at least two different PRs: one with the proposed commit hook (that we can discuss code-style wise) and one with the re-indentation

**Comment by Diman0** [comment]
I concur. There are too many changed files now. I can't easily see what files are relevant for the proposed commit hook and what files are only reformatted.

**Comment by parisni** [comment]
On July 10, 2021 12:25:11 PM UTC, Florent Daigniere ***@***.***> wrote:
>IMHO this should be at least two different PRs: one with the proposed commit hook (that we can discuss code-style wise) and one with the re-indentation
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/pull/1860#issuecomment-877629812
Agreed

**Comment by Diman0** [comment]
After discussing this PR during the last meeting, we decided to close this PR. 

- We do not like formatters affect git blame. Suddenly the commit author affected all lines in the file due to using a formatter.
- There are proven cases that formatters such as black lead to non-working code or differently working code. The black project issues section shows multiple open issues for this. Nextgens also has negative experiences with formatters in previous projects that resulted in different working code.
- The code style used by all contributors of the Mailu project is quite good.

We do think it is a good idea to
- Update the development guidelines on how to use a linter in visual code that warns you about code not being compliant with the pep8 standard.
- Enhance CI workflow (github action) with a linter. If the linter finds issues, add a message to the PR that the linter check failed with the report. The PR author and any reviewers are now informed the PR does not follow pep8 guidelines.

I will update this in the linked issue.

**Pull request closed without merging**
