### PR TITLE
Update user_external example for nextcloud

### PR DESCRIPTION
**Pull request by kesselb**
## What type of PR?

documentation

## What does this PR do?

Update the user_external example for Nextcloud due an upstream change. PHP will remove the imap extension. Newer user_external releases requires a different configuration for imap.

### Related issue(s)
- https://github.com/nextcloud/user_external/issues/52

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by kesselb** [comment]
Please review @violoncelloCH :ping_pong:

**Comment by violoncelloCH** [comment]
so nextcloud/user_external#65 is merged and released in v0.6.3

**Comment by kesselb** [comment]
Are these required? The default should be fine for most user?

**Comment by violoncelloCH** [comment]
no as they are at the end and as they have a default value they are not required... I just thought you might want to add them to the documentation here as well, because they might be useful...

**Comment by kesselb** [comment]
Have a look @violoncelloCH @Nebukadneza :construction_worker_man:

**Comment by violoncelloCH** [comment]
@kesselb Looks good! (only Nextcloud writes itself with a lowercase "c", doesn't it?)

**Pull request merged**
