### PR TITLE
IPv6 stuff

### LINKED ISSUE #827: Authentication issues when using IPv6 via robbertkl/ipv6nat
I'm using robbertkl/ipv6nat to simplify my IPv6 management and it's causing issues with auth due to the new $SUBNET requirement for things. 

TLDR. I believe that IPv6 causes issues for containers that communicate over IPv6 since the authentication is based on the IPv4 $SUBNET property.

Using robbertkl/ipv6nat lets me treat IPv6 on my server in an identical fashion to my normal IPv4 services. It does standard NAT using the iptables firewall so that opening ports on a container works for both standards without changes.

The issue is that, on an apparent random basis (I think) the internal traffic uses the ULA local addresses to communicate amongst containers and as this does not match the $SUBNET things sometimes don't work. The most noticeable service with this issue is the Rspamd UI which spews near constant error messages, which when viewed in the inspector, are 403 errors. 

My (abbreviated) compose file is:

```
version: '2.1'

services:

  front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    logging:
      driver: $LOG_DRIVER
    ports:
    - "80:80"
    - "443:443"
    - "110:110"
    - "143:143"
    - "993:993"
    - "995:995"
    - "25:25"
    - "465:465"
    - "587:587"
    volumes:
      - "$ROOT/certs:/certs"
      - "$ROOT/overrides/nginx:/overrides"

... other services ...

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
        - subnet: $SUBNET6
```

As you can see I've added some IPv6 config to the network which is needed for the ipv6nat container to be able to route to the services.

The reason I setup the system this way (and not even because I tend to always do it) is because without doing this the standard docker-compose file you recommend would have my IPv6 services be inaccessible. I was not able to have any service connect to them. This is on a standard Ubuntu 18.04 VM with the latest vendor Docker installed and the UFW firewall running. Using the ipv6nat tool allows me to keep the firewall without changes as docker then manages the IPv6 the same way as IPv4.

### PR DESCRIPTION
**Pull request by muhlemmer**
## What type of PR?

(Feature, enhancement, bug-fix, documentation) -> A bit of everything

## What does this PR do?

Document how to use ipv6nat. This, however triggers some kind of flaky behavior with the Docker DNS resolver, resulting in lookup failures inside Podop. So this is fixed in theis PR as well... We now do `admin` resolving once, during startup. (As we did with other services).

Note: `docker-compose.yml` downgrade is necessary, as IPv6 settings are not supported by the Docker Compose file format 3 :disappointed:  

Credit to @cooperaj for finding this ipv6nat tool. And @robbertkl for writing it in the first place!

### Related issue(s)
- Fixes #827 
- Hopefully helps with #829 and #834

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: place entry in the [changelog](CHANGELOG.md), under the latest un-released version.

### CODE REVIEW

**Comment by robbertkl** [comment]
Cool project, guys! Glad my tool helps a bit.

**Comment by hoellen** [comment]
Works for me! The IPv6 addresses are now shown in the logs. Furthermore #834 is working for me. 

But now some services are not resolved correctly (e.g. redis):

```
admin_1      | [2019-01-18 16:25:49,742] ERROR in app: Exception on /internal/auth/email [GET]                                                                                                                       
admin_1      | Traceback (most recent call last):                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 493, in connect                                                                                                                   
admin_1      |     sock = self._connect()                                                                                                                                                                            
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 520, in _connect                                                                                                                  
admin_1      |     socket.SOCK_STREAM):                                                                                                                                                                              
admin_1      |   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo                                                                                                                                       
admin_1      |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                                                                                                           
admin_1      | socket.gaierror: [Errno -2] Name does not resolve                                                                                                                                                     
admin_1      |                                                                                                                                                                                                       
admin_1      | During handling of the above exception, another exception occurred:                                                                                                                                   
admin_1      |                                                                                                                                                                                                       
admin_1      | Traceback (most recent call last):                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/client.py", line 754, in execute_command                                                                                                               
admin_1      |     connection.send_command(*args)                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command                                                                                                              
admin_1      |     self.send_packed_command(self.pack_command(*args))                                                                                                                                                
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command                                                                                                       
admin_1      |     self.connect()                                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 498, in connect                                                                                                                   
admin_1      |     raise ConnectionError(self._error_message(e))                                                                                                                                                     
admin_1      | redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name does not resolve.                                                                                                           
admin_1      |                                                                                                                                                                                                       
admin_1      | During handling of the above exception, another exception occurred:                                                                                                                                   
admin_1      |                                                                                                                                                                                                       
admin_1      | Traceback (most recent call last):                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 493, in connect                                                                                                                   
admin_1      |     sock = self._connect()                                                                                                                                                                            
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 520, in _connect                                                                                                                  
admin_1      |     socket.SOCK_STREAM):                                                                                                                                                                              
admin_1      |   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo                                                                                                                                       
admin_1      |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                                                                                                           
admin_1      | socket.gaierror: [Errno -2] Name does not resolve                                                                                                                                                     
admin_1      |                                                                                                                                                                                                       
admin_1      | During handling of the above exception, another exception occurred:  
admin_1      | During handling of the above exception, another exception occurred:                                                                                                                                   
admin_1      |                                                                                                                                                                                                       
admin_1      | Traceback (most recent call last):                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                                                        
admin_1      |     response = self.full_dispatch_request()                                                                                                                                                           
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                                                           
admin_1      |     rv = self.handle_user_exception(e)                                                                                                                                                                
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                                                           
admin_1      |     reraise(exc_type, exc_value, tb)                                                                                                                                                                  
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise                                                                                                                       
admin_1      |     raise value                                                                                                                                                                                       
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request                                                                                                           
admin_1      |     rv = self.dispatch_request()                                                                                                                                                                      
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request                                                                                                                
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)                                                                                                                                        
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 542, in __inner                                                                                                            
admin_1      |     self.__check_request_limit(False)                                                                                                                                                                 
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 479, in __check_request_limit                                                                                              
admin_1      |     six.reraise(*sys.exc_info())                                                                                                                                                                      
admin_1      |   File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise                                                                                                                                
admin_1      |     raise value                                                                                                                                                                                       
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 462, in __check_request_limit                                                                                              
admin_1      |     self.__evaluate_limits(endpoint, all_limits)                                                                                                                                                      
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 336, in __evaluate_limits                                                                                                  
admin_1      |     if not self.limiter.hit(lim.limit, *args):                                                                                                                                                        
admin_1      |   File "/usr/lib/python3.6/site-packages/limits/strategies.py", line 130, in hit                                                                                                                      
admin_1      |     self.storage().incr(item.key_for(*identifiers), item.get_expiry())                                                                                                                                
admin_1      |   File "/usr/lib/python3.6/site-packages/limits/storage.py", line 408, in incr                                                                                                                        
admin_1      |     return self.lua_incr_expire([key], [expiry])                                                                                                                                                      
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/client.py", line 3498, in __call__                                                                                                                     
admin_1      |     return client.evalsha(self.sha, len(keys), *args)                                                                                                                                                 
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/client.py", line 2704, in evalsha                                                                                                                      
admin_1      |     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)                                                                                                                              
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/client.py", line 760, in execute_command                                                                                                               
admin_1      |     connection.send_command(*args)                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command                                                                                                              
admin_1      |     self.send_packed_command(self.pack_command(*args))                                                                                                                                                
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command                                                                                                       
admin_1      |     self.connect()                                                                                                                                                                                    
admin_1      |   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 498, in connect                                                                                                                   
admin_1      |     raise ConnectionError(self._error_message(e))                                                                                                                                                     
admin_1      | redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name does not resolve.    
```

**Comment by muhlemmer** [comment]
That's bad news :(

Just to make sure, have you set a link local IPv6 Subnet in Docker compose?:

```
networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
        - subnet: fd38:7bed:abcd:beef::/64
```

I've not really mentioned this in the docs, since setup is generating the link-local range automatically now. If you want to do it manually, you can use https://cd34.com/rfc4193/.

If that was not the problem, Docker's DNS resolver is really shitty! :-1:

**Comment by hoellen** [comment]
Yes I added the IPv6 subnet to my docker-compose. I used the python function from this PR for generating it (`fdf4:dce8:2b8e:beef::/64`).
The error seems randomly. Sometimes the names are resolved correctly. Also `ping -6 redis` inside the container is working correctly.

**Comment by muhlemmer** [comment]
Yes, on my side I saw those errors when resolving admin from imap. I worked around it by doing the resolving part during start.

I guess we'll have to start doing that for all services. This means a complete overhaul for the start scripts I'm afraid

Probably best to write a single library which just populates a dictionary with the relevant IP addresses and use that one in all start.py scripts.

We'll get into it after the weekend, I hope. 

On 18 January 2019 19:36:48 EET, hoellen <notifications@github.com> wrote:
>Yes I added the IPv6 subnet to my docker-compose. I used the python
>function from this PR for generating it (`fdf4:dce8:2b8e:beef::/64`).
>The error seems randomly. Sometimes the names are resolved correctly.
>Also `ping -6 redis` inside the container is working correctly.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/pull/844#issuecomment-455627635

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by muhlemmer** [comment]
I will close this. We will start with some major overhauling of `start.py` and reopen a PR when done.

**Pull request closed without merging**
