### PR TITLE
Allow specifying the traefik version for cert dumping

### PR DESCRIPTION
**Pull request by timoschwarzer**
## What type of PR?

Enhancement

### Related issue(s)
- #1011 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [X] In case of feature or enhancement: documentation updated accordingly
- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by kaiyou** [comment]
This looks good, but I would have to try it first, haven't got around playing much with traefik 2 yet.

**Comment by Niecke** [comment]
This PR would be nice. Looks the same like my local solution.
Looking forward to the merge :)

**Comment by unixfox** [comment]
Just tested, can confirm it works with Traefik 2.0.
Docker image for testing available here: https://hub.docker.com/r/unixfox/mailu-traefik-certdumper

**Comment by staehle** [comment]
+1 for this. Ran into this issue with my Traefik v2 setup

**Pull request merged**
