### PR TITLE
Corrected 'adminitration' to 'administration'

### PR DESCRIPTION
**Pull request by warsix4**
## What type of PR?

documentation/bug-fix

## What does this PR do?

'adminitration' has been corrected to 'administration'

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by Nebukadneza** [comment]
bors try

**Comment by Nebukadneza** [comment]
Ah, I didn’t see before — it seems this needs to be rebased on master so that
31c4f13
is included, which currently prevents this PR from building.

**Comment by hoellen** [comment]
bors try

**Comment by hoellen** [comment]
@Nebukadneza I changed the branch to master and rebased this PR. Can you please approve it again? Thanks!

**Pull request merged**
