### PR TITLE
Use nginx for kubernetes ingress

### LINKED ISSUE #1021: Kuebernetes Admin UI URL in redirect loop
I'm attempting to get this set up on Kubernetes to evaluate.

Unfortunately, when trying to hit the admin, I get in a redirect loop to /admin/ui/

```
$ curl -I -L https://mail.example.com/admin/ui/                                                            

HTTP/1.1 301 MOVED PERMANENTLY
Date: Wed, 15 May 2019 19:15:56 GMT 
Content-Type: text/html; charset=utf-8
Content-Length: 291 
Connection: keep-alive
Location: https://mail.example.com/admin/ui/
Strict-Transport-Security: max-age=15724800; includeSubDomains
...
...
...
HTTP/1.1 301 MOVED PERMANENTLY
Date: Wed, 15 May 2019 19:15:58 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 291
Connection: keep-alive
Location: https://mail.example.com/admin/ui/
Strict-Transport-Security: max-age=15724800; includeSubDomains

curl: (47) Maximum (50) redirects followed
```

I think this is a combination of the admin flask app and the nginx-ingress redirects (although that may be wrong as I've no experience with flask)

I'm using a previously installed nginx-ingress (from https://github.com/kubernetes/kops/blob/master/addons/ingress-nginx/v1.6.0.yaml) and am running kubernetes as this is Kubernetes installed via KOPS on AWS.

The ingresses seem to be configured correctly, SSL certs in palce etc and annotiation prefix made sure to match.

This does not appear to be a http -> https loop, all redirects are to and from https

Any assistance would be greatly appreciated.

### LINKED ISSUE #1121: Proxy rspamd through admin ui for security reasons
Currently the security of rspamd on kubernetes relies on a feature available on nginx ingress. If the ingress does not support that annotation, rspamd will be exposed unprotected. It would be better if the admin ui proxies rspamd and adds authentification.

### PR DESCRIPTION
**Pull request by micw**
## What type of PR?

enhancement

## What does this PR do?

Currently, kubernetes uses a complex ingress setting which is not portable across different ingress controllers. This PR simplifies the ingress and delegates everythins special to Mailu to the front container,

### Related issue(s)
- closes #1121
- closes #1117
- closes #1021
- closes #1045

## Prerequistes

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog]

### CODE REVIEW

**Comment by kaiyou** [comment]
This looks really good. I am setting up a testing k8s at home so hopefully I can test and provide feedback.

**Comment by micw** [comment]
also closes #1158

**Comment by kaiyou** [comment]
Well. This is #1158 🤔

**Comment by micw** [comment]
@kaiyou Recursion: see recursion ;-)

I meant: also closes #1128

**Comment by fionera** [comment]
I tried this but since Nginx wants to bind to :80 and the Pod is configured to use the host network, it fails when having an nginx-ingress handler...

**Comment by kaiyou** [comment]
There are so many things that need improving on the k8s side, and your PR is definitely showing the way. After crawling my way through setting the proper pvc and specifying the node affinity rule, it somehow runs fine. I am all for merging this and going forward with improving the k8s docs.

**Comment by fionera** [comment]
@micw Yeah now it nearly work out of the box... The front.yaml is missing the port 80 definition :)

**Comment by micw** [comment]
@fionera 
There's no webmail ingress, it's handled by front nginx. If you pass WEBMAIL env to front, it should be there (https://github.com/Mailu/Mailu/blob/44837fc0075c9ae557791f60e21f3fe6c4455b5f/core/nginx/conf/nginx.conf#L104)

**Comment by micw** [comment]
No idea why antispam returns 502. Are you logged in as admin?

**Comment by micw** [comment]
I have added the missing port in front.yml

**Comment by fionera** [comment]
I use a different domain for the webmail to make it easier. Regarding antispam, yes I am logged it as Admin in Mailu, but as soon as I try to load the antispam I get a 502...

**Comment by kaiyou** [comment]
Webmail ingress will probably not return, we have debated this a couple times already and it makes things difficult to maintain. We could of course have different flavors but that is not the current direction: we are trying to do simple things well before we do anything complex.

**Comment by micw** [comment]
@fionera Can you see in the 502 error if it comes from traefik or from nginx? I'm quite sure it's from nginx. If so, please check and provide the following details:
- nginx logs when you access the rspamd
- generated nginx configuration, especially the rspamd part
- verify that the antispam address is correct in nginx config and it's reachable from the front container

Regarding webmail ingress: you are always free just to deploy another ingress that points to http://front/webmail/. For traefik, you can also add the traefik.ingress.kubernetes.io/app-root annotation to it, so that you get redirected from / to /webmail on the webmail domain.

**Comment by micw** [comment]
I have it running by using my helm chart: https://github.com/micw/charts/tree/mailu/incubator/mailu
Webmail, antispam and admin-ui are reachable without any problems.

@kaiyou If you are fine with that, you can merge it. If any unexpected issues occur, I'd fix it in separate issues.

**Comment by kaiyou** [comment]
bors merge

**Pull request merged**
