### PR TITLE
Attempt stripping recipient delimiter from localpart

### LINKED ISSUE #755: recipient_delimiter no longer working
We've found that that `recipient_delimiter` is no longer working. It stopped functioning somewhere around two weeks ago, after we migrated our production server from 1.5 to master. We don't really have time to research this right now, so I'm opening an issue instead.

In `mailu.env` is set:
```
# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+
```
In the container's `/etc/postfix/main.cf` it evaluated correctly:
```
# Recipient delimiter for extended addresses                             
recipient_delimiter = + 
```
Results in the following errors in the smtp logs:
```
mailu_smtp.1.re3f5q4d8raz@prod02.redacted.com    | postfix/smtpd[26303]: NOQUEUE: reject: RCPT from unknown[10.255.0.2]: 550 5.1.1 <redacted+GitHub@redacted.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<noreply@github.com> to=<redacted+GitHub@redacted.com> proto=ESMTP helo=<smtp.github.com>
```
And in admin it is seen that the part after delimiter is not cut by postfix and send as-is to through podop:
```
mailu_admin.1.52ugkzvrrbam@prod01.redacted.com    | 192.168.203.4 - - [18/Dec/2018:08:18:17 +0000] "GET /internal/postfix/sender/access/noreply@github.com HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.4.4"
mailu_admin.1.52ugkzvrrbam@prod01.redacted.com    | 192.168.203.4 - - [18/Dec/2018:08:18:17 +0000] "GET /internal/postfix/alias/redacted+github@redacted.com HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.4.4"
mailu_admin.1.52ugkzvrrbam@prod01.redacted.com    | 192.168.203.4 - - [18/Dec/2018:08:18:17 +0000] "GET /internal/postfix/mailbox/redacted+github@redacted.com HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.4.4"
```

### PR DESCRIPTION
**Pull request by Nebukadneza**
Since postfix now asks us for the complete email over podop, which
includes the recipient-delimiter-and-what-follows not stripped, we need
to attempt to find both the verbatim localpart, as well as the localpart
stripped of the delimited part ….

Fixes #755

**Most likely depends on https://github.com/Mailu/Podop/pull/3**

### CODE REVIEW

**Comment by muhlemmer** [comment]
I've added the blocked label, until Mailu/Podop#3 is merged.

**Comment by Nebukadneza** [comment]
Thanks @kaiyou @muhlemmer for the help on this ^_^

**Comment by muhlemmer** [comment]
Correction, needs a second review for merge.

**Comment by hoellen** [comment]
I just wanted to test this patch on my test setup.  **Without** this patch and podop 0.2.5, the following happens:
- `user+test@domain.tld` -> works
- `alias+test@domain.tld `-> doesn't work

Unfortunately this patch  **doesn't change** anything of this behavior. I dont' have enough time to dig into this right now (hopefully in the evening). Maybe someone can reproduce this in the meantime.

**Comment by Nebukadneza** [comment]
Hm, that is strange — I tested aliases, and they did work for me. I just re-did these tests:

```
smtp_1       | postfix/smtpd[123]: connect from mailu_front_1.mailu_default[192.168.203.3]
admin_1      | 192.168.203.3 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/transport/wubwub%2Bfoo@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/transport/* HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/alias/wubwub%2Bfoo@test02.usrpro.io HTTP/1.1" 200 24 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/smtpd[123]: 6AFE7E40254: client=unknown[192.168.203.1]
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/alias/wubwub%2Bfoo@test02.usrpro.io HTTP/1.1" 200 24 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/alias/root@test02.usrpro.io HTTP/1.1" 200 24 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/cleanup[243]: 6AFE7E40254: message-id=<f931e8a0b47ef9c25f2eba28d8276dc9@ghostdub.de>
smtp_1       | postfix/qmgr[112]: 6AFE7E40254: from=<daddel9@ghostdub.de>, size=1860, nrcpt=1 (queue active)
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/postfix/transport/root@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/dovecot/userdb/root@test02.usrpro.io HTTP/1.1" 200 36 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/dovecot/sieve/name/default/root@test02.usrpro.io HTTP/1.1" 200 10 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:00:53 +0000] "GET /internal/dovecot/sieve/data/default/root@test02.usrpro.io HTTP/1.1" 200 678 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/smtpd[123]: disconnect from unknown[192.168.203.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:00:53 +0000] "POST /internal/dovecot/quota/storage/root@test02.usrpro.io HTTP/1.1" 200 5 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:00:53 +0000] "POST /internal/dovecot/quota/messages/root@test02.usrpro.io HTTP/1.1" 200 5 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/lmtp[244]: 6AFE7E40254: to=<root@test02.usrpro.io>, orig_to=<wubwub+foo@test02.usrpro.io>, relay=imap[192.168.203.10]:2525, delay=0.36, delays=0.21/0.05/0.01/0.1, dsn=2.0.0, status=sent (250 2.0.0 <root@test02.usrpro.io> fMCbJaVpM1zEAAAA2ZEJlw Saved)
smtp_1       | postfix/qmgr[112]: 6AFE7E40254: removed
```

Same for alias with `%` in it:
```
smtp_1       | postfix/smtpd[123]: connect from mailu_front_1.mailu_default[192.168.203.3]
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/transport/foobarPERCENT%2Bdelimited@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/transport/* HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/alias/foobarpercent%2Bdelimited@test02.usrpro.io HTTP/1.1" 200 24 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/smtpd[123]: 5BAC8E40254: client=unknown[192.168.203.1]
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/alias/foobarPERCENT%2Bdelimited@test02.usrpro.io HTTP/1.1" 200 24 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/alias/root@test02.usrpro.io HTTP/1.1" 200 24 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/cleanup[243]: 5BAC8E40254: message-id=<3a3c4f1e8be57acbf690c8bf939a5881@ghostdub.de>
smtp_1       | postfix/qmgr[112]: 5BAC8E40254: from=<daddel9@ghostdub.de>, size=1911, nrcpt=1 (queue active)
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.9 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/postfix/transport/root@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/dovecot/userdb/root@test02.usrpro.io HTTP/1.1" 200 36 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/dovecot/sieve/name/default/root@test02.usrpro.io HTTP/1.1" 200 10 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:02:11 +0000] "GET /internal/dovecot/sieve/data/default/root@test02.usrpro.io HTTP/1.1" 200 678 "-" "Python/3.6 aiohttp/3.5.1"
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:02:11 +0000] "POST /internal/dovecot/quota/storage/root@test02.usrpro.io HTTP/1.1" 200 5 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/smtpd[123]: disconnect from unknown[192.168.203.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
admin_1      | 192.168.203.10 - - [07/Jan/2019:15:02:11 +0000] "POST /internal/dovecot/quota/messages/root@test02.usrpro.io HTTP/1.1" 200 5 "-" "Python/3.6 aiohttp/3.5.1"
smtp_1       | postfix/lmtp[244]: 5BAC8E40254: to=<root@test02.usrpro.io>, orig_to=<foobarPERCENT+delimited@test02.usrpro.io>, relay=imap[192.168.203.10]:2525, delay=0.26, delays=0.15/0.04/0/0.08, dsn=2.0.0, status=sent (250 2.0.0 <root@test02.usrpro.io> cBQIHvNpM1zEAAAA2ZEJlw Saved)
smtp_1       | postfix/qmgr[112]: 5BAC8E40254: removed
```

Did you do anything special to produce that behavior?

**Comment by hoellen** [comment]
It is working now. Maybe it was some cached queries...

**Pull request merged**
