### PR TITLE
Ensure that we do not silently discard PUAs flagged by clamav

### LINKED ISSUE #3048: Dovecot silently discards emails with password protected attachments (excel files)
## Environment & Version

- `docker compose version 2.21.0`
- Mailu Version: `2.0`

## Description
If an email is received with an excel attachment that is password protected, the following happens:
Email is received, sender is notified of successful delivery(enabled on sender's part).
The Email gets forwarded successfully to my alternate email in the settings.
Email gets discarded silently by lmtp
Webmail/Imap clients do not get the email. Forwarded address gets the email.

The expected behaviour should be to either reject the message, notifying the sender, or deliver it to INBOX

## Replication Steps

Create an empty excel file, type a few numbers, password protect the file, send it as an attachment to an internal domain(haven't verified externally)
Set a forwarder to your email address, to see that the forwarded email gets delivered

## Logs

```
smtp_1       | Nov 09 10:46:57 m1 postfix/smtpd[25630]: connect from mailu_front_1.mailu_default[192.168.203.4]
smtp_1       | Nov 09 10:46:57 m1 postfix/smtpd[25630]: discarding EHLO keywords: PIPELINING
smtp_1       | Nov 09 10:46:57 m1 postfix/smtpd[25630]: discarding EHLO keywords: PIPELINING
smtp_1       | Nov 09 10:46:58 m1 postfix/smtpd[25630]: 0D5F44E3B13: client=unknown[REDACTED], sasl_method=XCLIENT, sasl_username=sender@domain.com
smtp_1       | Nov 09 10:46:58 m1 postfix/cleanup[25706]: 0D5F44E3B13: message-id=<007301da12f1$ae5204c0$0af60e40$@domain.com>
smtp_1       | Nov 09 10:47:07 m1 postfix/qmgr[385]: 0D5F44E3B13: from=<sender@domain.com>, size=6993906, nrcpt=2 (queue active)
smtp_1       | Nov 09 10:47:08 m1 postfix/lmtp[25708]: 0D5F44E3B13: to=<receiver@domain.com>, relay=imap[192.168.203.7]:2525, delay=10, delays=9.9/0.04/0/0.15, dsn=2.0.0, status=sent (250 2.0.0 <receiver@domain.com> cGNWNZuqTGWXzgAA4L/waQ Saved)
smtp_1       | Nov 09 10:47:08 m1 postfix/smtp[25791]: Verified TLS connection established to gmail-smtp-in.l.google.com[108.177.126.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (prime256v1)
smtp_1       | Nov 09 10:47:09 m1 postfix/smtp[25791]: 0D5F44E3B13: to=<forwarded_recipient@gmail.com>, orig_to=<receiver@domain.com>, relay=gmail-smtp-in.l.google.com[108.177.126.27]:25, delay=12, delays=9.9/0.04/0.54/1.2, dsn=2.0.0, status=sent (250 2.0.0 OK  1699523229 ti5-20020a170907c20500b0099cb9d70178si3143767ejc.869 - gsmtp)
smtp_1       | Nov 09 10:47:09 m1 postfix/cleanup[25718]: A40854E7291: message-id=<20231109094709.A40854E7291@m1.domain.email>
smtp_1       | Nov 09 10:47:09 m1 postfix/bounce[25801]: 0D5F44E3B13: sender delivery status notification: A40854E7291
smtp_1       | Nov 09 10:47:09 m1 postfix/qmgr[385]: A40854E7291: from=<>, size=3051, nrcpt=1 (queue active)
smtp_1       | Nov 09 10:47:09 m1 postfix/qmgr[385]: 0D5F44E3B13: removed
smtp_1       | Nov 09 10:47:09 m1 postfix/lmtp[25708]: A40854E7291: to=<sender@domain.com>, relay=imap[192.168.203.7]:2525, delay=0.1, delays=0.04/0.02/0/0.04, dsn=2.0.0, status=sent (250 2.0.0 <sender@domain.com> yC+0K52qTGWXzgAA4L/waQ Saved)
smtp_1       | Nov 09 10:47:09 m1 postfix/qmgr[385]: A40854E7291: removed
smtp_1       | Nov 09 10:47:10 m1 postfix/smtpd[25630]: disconnect from unknown[REDACTED] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
imap_1       | Nov 09 10:47:07 lmtp(52887): Info: Connect from 192.168.203.6
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; proxy; finalize_item: slow rule: SEM_URIBL_FRESH15_UNKNOWN(549): 368.99 ms; enable slow timer delay
smtp_1       | Nov 09 10:47:07 m1 postfix/qmgr[385]: 0D5F44E3B13: from=<sender@domain.com>, size=6993906, nrcpt=2 (queue active)
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; lua; common.lua:141: skip oletools check as it is too large: 5102592 (3145728 is allowed)
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; lua; greylist.lua:331: Score too low - skip greylisting
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; proxy; rspamd_stat_classifier_is_skipped: learn condition for classifier bayes returned: already in class ham; probability 98.84%; skip classifier
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; proxy; rspamd_task_process: skip learning: all learn conditions denied learning ham in default classifier
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; lua; neural.lua:351: skip ham sample to keep spam/ham balance; probability 0.8891891891891892; 41 spam and 369 ham vectors stored
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; proxy; rspamd_task_write_log: id: <007301da12f1$ae5204c0$0af60e40$@domain.com>, qid: <0D5F44E3B13>, ip: REDACTED, user: sender@domain.com, from: <sender@domain.com>, (default: F (no action): [-18.83/11.00] [FROM_WHITELISTED_SPF_DKIM(-10.00){domain.com;},FROM_WHITELISTED(-5.00){domain.com;},BAYES_HAM(-2.73){98.84%;},FROM_WHITELIST_TLD(-1.00){sender@domain.com;},MIME_GOOD(-0.10){multipart/mixed;multipart/alternative;text/plain;},ARC_NA(0.00){},ASN(0.00){asn:35444, ipnet:80.90.80.0/20, country:AL;},CLAM_VIRUS(0.00){PUA.Doc.Packed.EncryptedDoc-6563700-0;},DKIM_SIGNED(0.00){domain.com:s=dkim;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},HAS_ATTACHMENT(0.00){},IS_LOCAL_DOMAIN_E(0.00){domain.com;},IS_LOCAL_DOMAIN_H(0.00){domain.com;},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:+;1:+;2:+;3:~;4:~;},NEURAL_HAM(0.00){-0.998;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},TO_DN_ALL(0.00){},TO_DOM_EQ_FROM_DOM(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 6993868, time: 494.048ms, dns req: 30, digest: <6f0b3f312679df2d2d33d714fc36e436>, rcpts: <receiver@domain.com>, mime_rcpts: <receiver@domain.com>
antispam_1   | 2023-11-09 10:47:07 #208(rspamd_proxy) <b1f11e>; proxy; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 2 regexps matched, 176 regexps total, 49 regexps cached, 0B scanned using pcre, 10.92KiB scanned total
smtp_1       | Nov 09 10:47:08 m1 postfix/lmtp[25708]: 0D5F44E3B13: to=<receiver@domain.com>, relay=imap[192.168.203.7]:2525, delay=10, delays=9.9/0.04/0/0.15, dsn=2.0.0, status=sent (250 2.0.0 <receiver@domain.com> cGNWNZuqTGWXzgAA4L/waQ Saved)
imap_1       | Nov 09 10:47:08 lmtp(receiver@domain.com)<52887><cGNWNZuqTGWXzgAA4L/waQ>: Info: sieve: msgid=<007301da12f1$ae5204c0$0af60e40$@domain.com>: discard action: Marked message to be discarded if not explicitly delivered (discard action)
imap_1       | Nov 09 10:47:08 lmtp(52887): Info: Disconnect from 192.168.203.6: Logged out (state=READY)
smtp_1       | Nov 09 10:47:08 m1 postfix/smtp[25791]: Verified TLS connection established to gmail-smtp-in.l.google.com[108.177.126.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (prime256v1)
imap_1       | Nov 09 10:47:09 lmtp(52887): Info: Connect from 192.168.203.6
imap_1       | Nov 09 10:47:09 lmtp(sender@domain.com)<52887><yC+0K52qTGWXzgAA4L/waQ>: Info: sieve: msgid=<20231109094709.A40854E7291@m1.domain.email>: stored mail into mailbox 'INBOX'
imap_1       | Nov 09 10:47:09 lmtp(52887): Info: Disconnect from 192.168.203.6: Logged out (state=READY)
front_1      | 2023/11/09 10:47:09 [info] 13#13: *103369 client REDACTED:50085 connected to 0.0.0.0:993
smtp_1       | Nov 09 10:47:09 m1 postfix/smtp[25791]: 0D5F44E3B13: to=<forwarded_recipient@gmail.com>, orig_to=<receiver@domain.com>, relay=gmail-smtp-in.l.google.com[108.177.126.27]:25, delay=12, delays=9.9/0.04/0.54/1.2, dsn=2.0.0, status=sent (250 2.0.0 OK  1699523229 ti5-20020a170907c20500b0099cb9d70178si3143767ejc.869 - gsmtp)
smtp_1       | Nov 09 10:47:09 m1 postfix/cleanup[25718]: A40854E7291: message-id=<20231109094709.A40854E7291@m1.domain.email>
smtp_1       | Nov 09 10:47:09 m1 postfix/bounce[25801]: 0D5F44E3B13: sender delivery status notification: A40854E7291
smtp_1       | Nov 09 10:47:09 m1 postfix/qmgr[385]: A40854E7291: from=<>, size=3051, nrcpt=1 (queue active)
smtp_1       | Nov 09 10:47:09 m1 postfix/qmgr[385]: 0D5F44E3B13: removed
smtp_1       | Nov 09 10:47:09 m1 postfix/lmtp[25708]: A40854E7291: to=<sender@domain.com>, relay=imap[192.168.203.7]:2525, delay=0.1, delays=0.04/0.02/0/0.04, dsn=2.0.0, status=sent (250 2.0.0 <sender@domain.com> yC+0K52qTGWXzgAA4L/waQ Saved)

```

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

bug-fix

## What does this PR do?

Ensure that we do not silently discard PUAs flagged by clamav. Instead we will reject emails.

### Related issue(s)
- closes #3048 

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
bors try

**Comment by nextgens** [comment]
bors retry

**Comment by nextgens** [comment]
bors retry

**Review by Diman0 — APPROVED** [review]
lgtm

**Pull request merged**
