### PR TITLE
1.9 multiarch

### PR DESCRIPTION
**Pull request by mabels**
## What type of PR?

enhancement (the ci will fail configuration needed)

## What does this PR do?

it's complicated --- i need the aarch64 images of 1.9 to run it in production. I saw some tries on master to arm but my experience with arm builds on github helped me to go a different route and so i now have actual images in:

https://hub.docker.com/repository/docker/fastandfearless/....

with proper manifest.
To get to this point i did not forked the repro i "recreated it" to have full controll over the secrets and ocid connections. This repo is in

https://github.com/mabels/mailu-arm

To get this to work you need some additional work --- I use github external workers/runners which run native x86_64 and aarch64 machines. These machine could be hosted on:
- aws (need some adaption) using ocid 
- oci (oracle cloud) (should work)  using secrets from my tool
- gcp (google cloud) (working)  using ocid
I tried azure but they don't aarch64 VM for the public.
If you want to reuse and need some help please ask me. To setup the ocid need some base infrastructure in the related accounts: 

https://github.com/mabels/developers-paradise/tree/main/.github/workflows

### CODE REVIEW

**Comment by nextgens** [comment]
@mabels can you explain what's wrong with the manifests in master?

We are planning to have a release soon; at that point ARM will be officially supported in a stable release.
I encourage you to try out and contribute to the code that will be maintained going forward.

We are on https://riot.im/app/#/room/#mailu-dev:tedomum.net if you want to drop in for a chat.

**Comment by mabels** [comment]
> @mabels can you explain what's wrong with the manifests in master?
> 
> We are planning to have a release soon; at that point ARM will be officially supported in a stable release. I encourage you to try out and contribute to the code that will be maintained going forward.
> 
> We are on https://riot.im/app/#/room/#mailu-dev:tedomum.net if you want to drop in for a chat.

There is nothing wrong with the manifest in master --- but i needed them to work for 1.9.

When do you think you will release the next version including arm? I tried the master version on arm some weeks ago and it did not work.
If you see poor arm build times you could go this way to improve the build time --- the building happens in native not in qemu.

**Comment by nextgens** [comment]
Please give another try to what's in master; I currently run a deployment on an A1 instance. https://hub.docker.com/r/mailu/admin/tags

We are already building master natively on an A1 instance; The release is planned for year-end/early next year.

**Comment by nextgens** [comment]
The last ARM build took ~8mins https://github.com/Mailu/Mailu/actions/runs/3730767569

**Comment by Diman0** [comment]
We already have a functioning workflow for building arm images for master.
For 1.9 we don't support arm images and will also not introduce a workflow for building arm images. 

Within 1-2 months the next Mailu version is released. From that moment the new stable version will also have arm images available.

**Pull request closed without merging**
