### PR TITLE
updated roundcube to 1.5.1 and carddav to 4.3.0

### LINKED ISSUE #2031: Upgrade Roundcube to 1.5
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [x] kubernetes
 - [x] docker swarm

### Versions
Since this is not a bug report, I’m not sure if you need my current version.

## Description
Currently, Mailu still uses version 1.4 of the Roundcube webmail client, which has recently received an update. Highlights of the 1.5 release are summarized in this [blogpost from roundcube.net](https://roundcube.net/news/2021/10/18/roundcube-1.5.0-released), though (for me) the most interesting are:
- OAuth2 support
- Elastic now comes with a dark mode

From a quick glance at the Dockerfile, it didn’t seem like there are any huge requirements, but I’ll give it a try later and see what happens. I’d be happy to contribute this change if it works, but I don’t have a full picture of the behind the scenes of the mailu stack yet, so I may need help if I walk into any traps.

Thank you all for your work with mailu! It’s an awesome project and really makes hosting a mailserver extremly easy, at least on a small scale.

#### Changlog
[2021-11-01 08:41 +00]: add thank you note

### PR DESCRIPTION
**Pull request by ghostwheel42**
## What type of PR?

enhancement

## What does this PR do?

updated roundcube to 1.5 and carddav to 4.2.2
also runs cleanup cronjob _once_ at startup

### Related issue(s)

- closes #2031 
- runs cleanup job mentioned in #1702 at startup

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [X] In case of feature or enhancement: documentation updated accordingly
- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Diman0** [comment]
You beat me to it. I was also planning to create a PR for this, but didn't think about adding the database cleanup job. 
It looks good to me, but I will run some tests tonight before I accept it .

**Review by Diman0 — APPROVED** [review]
Looks good to me.

**Comment by Diman0** [comment]
When I click Drafts in roundcube, roundcube logs that a server error occurred. I can see the following in the roundcube container standard output

```
webmail_1    | 192.168.203.4 - - [02/Nov/2021:21:42:13 +0000] "GET /?_task=mail&_action=list&_refresh=1&_layout=widescreen&_mbox=INBOX&_page=1&_remote=1&_unlock=loading1635889333524&_=1635889163758 HTTP/1.1" 200 1464 "https://test.berichthier.nl/webmail/?_task=mail&_mbox=Drafts" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
webmail_1    | [Tue Nov 02 21:42:14.966324 2021] [php7:error] [pid 63] [client 192.168.203.4:43022] PHP Fatal error:  Uncaught Error: Class 'Spoofchecker' not found in /var/www/html/program/lib/Roundcube/rcube_spoofchecker.php:50\nStack trace:\n#0 /var/www/html/program/actions/mail/index.php(1400): rcube_spoofchecker::check('huisman.xyz')\n#1 /var/www/html/program/actions/mail/index.php(523): rcmail_action_mail_index::address_string('dimitri@huisman...', 3, false, NULL, 'US-ASCII')\n#2 /var/www/html/program/actions/mail/list.php(123): rcmail_action_mail_index::js_message_list(Array, false, Array)\n#3 /var/www/html/program/include/rcmail.php(275): rcmail_action_mail_list->run(Array)\n#4 /var/www/html/index.php(283): rcmail->action_handler()\n#5 {main}\n  thrown in /var/www/html/program/lib/Roundcube/rcube_spoofchecker.php on line 50, referer: https://test.berichthier.nl/webmail/?_task=mail&_mbox=INBOX
webmail_1    | 192.168.203.4 - - [02/Nov/2021:21:42:14 +0000] "GET /?_task=mail&_action=list&_refresh=1&_layout=widescreen&_mbox=Sent&_page=1&_remote=1&_unlock=loading1635889335068&_=1635889163759 HTTP/1.1" 500 552 "https://test.berichthier.nl/webmail/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
```

The problematic text is 
```Class 'Spoofchecker' not found in /var/www/html/program/lib/Roundcube/rcube_spoofchecker.php```

I will have a look at the roundcube project if this is a bug in roundcube.

**Comment by Diman0** [comment]
In [issue 8127](https://github.com/roundcube/roundcubemail/issues/8127) I can see that there is a new requirement. php-intl extension is now required. 

In the readme.md I can see the following new requirements have been introduced
- Require PHP >= 5.5
- Require php-intl
- Require GuzzleHttp\Client

**Review by Diman0 — CHANGES_REQUESTED** [review]
Dependencies php-intl and GuzzleHttp\Client must be added.

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
roundcube is running fine now.
I'll take a look and check if we can use the official docker image (https://github.com/roundcube/roundcubemail-docker) (fpm-alpine).

**Comment by ghostwheel42** [comment]
bors cancel

**Comment by ghostwheel42** [comment]
bors try

**Comment by Diman0** [comment]
Under the assumption we will use the official roundcube image with plugin support, I have added "closes #2035" to your PR description. (I know you will not start working on this PR until the other PR for updating Admin deps is finished.)

**Comment by 0xErnie** [comment]
It seems like images of 1.5 are held back because of reports of failing mySQL schema upgrades.
see https://github.com/roundcube/roundcubemail-docker/issues/148#issuecomment-950205373

**Comment by ghostwheel42** [comment]
According to https://github.com/roundcube/roundcubemail/issues/8231 there will be a fix (1.5.1) _in the second half of November_.

**Comment by Diman0** [comment]
@ghostwheel42 For your information, the [1.5.1-fpm docker image](https://hub.docker.com/r/roundcube/roundcubemail/tags?page=1&name=1.5.1-fpm-alpine) is now available.

**Comment by blinkeye** [comment]
Also note that the currently used [7.4-apache](https://github.com/Mailu/Mailu/blob/1.8/webmails/roundcube/Dockerfile#L4) base image has:
```bash
2 Critical, 3 High, 2 Medium, 79 Low
```
CVEs while the [php:7.4-fpm-alpine](https://github.com/roundcube/roundcubemail-docker/blob/master/fpm-alpine/Dockerfile#L1) used by the official image has:
```bash
php:7.4-fpm-alpine: has 0 Critical, 0 High, 0 Medium, 0 Low
```
according to Snyk. I double checked with [aquasecurity/trivy](https://github.com/aquasecurity/trivy).

**Comment by parsifallo** [comment]
FYI: I tested this PR with Trivy 0.17.2 and I get 464 Total (32 critical) vulnerabilities. For my setup I will try to create one a Docker image based on alpine. Does anyone use roundcube with an alpine image here at mailu?

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
bors try

**Comment by ghostwheel42** [comment]
@parsifallo 
> Does anyone use roundcube with an alpine image here at mailu?

Yes. It's running fine. We still have a discussion about php-fpm and nginx, but I think I'll change this PR to alpine/fpm/nginx next week.

**Comment by parsifallo** [comment]
> @parsifallo
> 
> > Does anyone use roundcube with an alpine image here at mailu?
> 
> Yes. It's running fine. We still have a discussion about php-fpm and nginx, but I think I'll change this PR to alpine/fpm/nginx next week.

This is great news, thank you!

**Review by nextgens — APPROVED** [review]
LGTM. Let's consider the switch to FPM in another PR

**Comment by blinkeye** [comment]
> @parsifallo
> 
> > Does anyone use roundcube with an alpine image here at mailu?
> 
> Yes. It's running fine. We still have a discussion about php-fpm and nginx, but I think I'll change this PR to alpine/fpm/nginx next week.

Since this PR has been merged in the meantime do you plan to create a new PR with a more secure base image (like the official roundcube image)? Context see https://github.com/Mailu/Mailu/pull/2035#issuecomment-985705834

**Comment by ghostwheel42** [comment]
> Since this PR has been merged in the meantime do you plan to create a new PR with a more secure base image (like the official roundcube image)?

Yes. This is still planned - unfortunately I don't have much free time to work on this.
Do you want to prepare a PR?

**Pull request merged**
