### PR TITLE
Add authentication for email relays

### LINKED ISSUE #387: Using external smtp relay server for outgoing emails
Hi,

I need to use mailchannels.com to relay all outgoing emails from my Mailu install. In this doc is what I need to change in Postfix:

https://mailchannels.zendesk.com/hc/en-us/articles/200262640-Setting-up-for-Postfix

Is there any way to do this in Mailu ?

Thanks,

### PR DESCRIPTION
**Pull request by daniel0611**
## What type of PR?

Feature

## What does this PR do?
Add support for email relays which require authentication like Mailgun, SendGrid and more.

### Related issue(s)
- Closes #387 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [X] In case of feature or enhancement: documentation updated accordingly
- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Comment by UnR34L** [comment]
Tested this and it works, can this be merged please.

**Comment by kaiyou** [comment]
Sorry about the relay. I am okay with the purpose, just a comment: I would rather use convert and jinja parsing in `start.py` than manual formatting.

**Comment by daniel0611** [comment]
@kaiyou fixed :)

**Comment by eXeC64** [comment]
Looks like the CI on this pull request has bugged. I see a comment from bors claiming success, but it's not merged due to bors still being pending?

**Comment by kaiyou** [comment]
Nope, it requires two reviews since it wasn't written by a regular contributor. Anyone?

**Comment by hcderaad** [comment]
Thanks for addressing this issue, my mail/vps provider setup really requires this feature to be usable before we can start mailu in production environments. So, question, when will this PR be made available in a regular installable release? I'd be happy to test and verify the setup if need be. See: https://github.com/Mailu/Mailu/issues/1061#issuecomment-517952126

**Pull request merged**
