### PR TITLE
Update front.yaml

### PR DESCRIPTION
**Pull request by cipianpascu**
To match the other kubernetes objects' version

## What type of PR? bug-fix

(Feature, enhancement, bug-fix, documentation)

### Related issue(s) #1237 
- Mention an issue like: #001
- Auto close an issue like: closes #001

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

### CODE REVIEW

**Review by Diman0 — APPROVED** [review]
Looks good to me.

**Review by nextgens — APPROVED** [review]

**Comment by Diman0** [comment]
bors cancel

**Comment by Diman0** [comment]
bors ping

**Comment by Diman0** [comment]
bors ping

**Comment by Diman0** [comment]
bors ping

**Comment by Diman0** [comment]
This PR a one liner. BORS appears not to respond anymore. I will merge this manually as an exception.

**Pull request merged**
