### PR TITLE
Upgrade dovecot: fix proxying ipv6 via xclient

### LINKED ISSUE #2918: Authentication failure when client connects via ipv6
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description
When a client connects via ipv6 it seems to be unable to send mails due to a "Bad ADDR syntax" error. The syntax of the ipv6 IP appears to be correct however (unless it's meant to be in brackets?). I've not found anything related to this error anywhere, seems like it's not a very common issue.

## Replication Steps
Enable ipv6 support in Mailu and try to connect via ipv6 natively. I don't know if there are any special things in my setup.

## Observed behaviour
Client isn't able to send mail due to an error (see logs).

## Expected behaviour
It should work just the same as ipv4.

## Logs
```
mailu-front-1      | Aug 21 09:18:45 submission-login: Error: proxy(test@example.com,192.168.203.7:10025): Aborting due to remote server: XCLIENT failed: 501 5.5.4 Bad ADDR syntax: 2003:eb:XXXX: user=<test@example.com>, method=PLAIN, rip=2003:eb:XXXX, rport=36882, lip=fdee:eeee:eeee:eeee::4, lport=587, TLS
mailu-front-1      | Aug 21 09:18:45 submission-login: Info: Disconnected: Connection closed (internal failure, 1 successful auths): user=<test@example.com>, method=PLAIN, rip=2003:eb:XXXX, rport=36882, lip=fdee:eeee:eeee:eeee::4, lport=587, TLS
```

(ipv6 address redacted, it is correct in the real log)

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

bug-fix

## What does this PR do?

Upgrade dovecot: fix proxying ipv6 via xclient

### Related issue(s)
- close #2918

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by nextgens** [comment]
bors try

**Comment by Diman0** [comment]
bors try

**Comment by nextgens** [comment]
We've run into this in the past... I've added to the ticket
https://gitlab.alpinelinux.org/alpine/aports/-/issues/15340

**Comment by nextgens** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Review by Diman0 — DISMISSED** [review]
You missed a `--no-cache` in the apk add command

**Review by Diman0 — APPROVED** [review]
lgtm

**Pull request merged**
