### PR TITLE
Fail2ban update

### PR DESCRIPTION
**Pull request by nextgens**
## What type of PR?

documentation

## What does this PR do?

Change the instructions on how to setup fail2ban

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Comment by Igortorrente** [comment]
Hi @nextgens,

I tested your changes and they seem to be working. I also noted that my sever was receiving spam from other kind of bots. I created a new filter that maybe you can add to you MR.

``` toml 
# filter.d/bad-auth-bots2.conf
[Definition]
failregex = ^.*?\[error\] \d+#\d+: \*\d+ recv\(\) failed \(111: Connection refused\) while in http auth state, client: <ADDR>, server:
ignoreregex =
```
``` toml 
# jail.d/bad-auth-bots2.conf 
[bad-auth-bots2]
enabled = true
port = 25,110,143,465,587,993,995,10025,10143
filter = bad-auth-bots
banaction = %(banaction_allports)s
action = iptables-allports[name=nginx-proxy, chain=FORWARD]
logpath = containers_logs_dir/nginx-proxy/mail.error.log
bantime = 604800
findtime = 600
maxretry = 5
```

**Comment by nextgens** [comment]
Thank you for testing it.

@Igortorrente I've just tried your regexp against my logs here and can't find any matching entry.

Can you paste the full transaction related to one match please? I don't think that "connection refused" is something we want to block.

**Comment by Igortorrente** [comment]
> Thank you for testing it.
> 
> @Igortorrente I've just tried your regexp against my logs here and can't find any matching entry.
> 
> Can you paste the full transaction related to one match please? I don't think that "connection refused" is something we want to block.

Hi @nextgens, maybe I miss-configured my sever, but I'm seeing this kind of logs in my nginx-proxy config:
```
2023/02/02 21:01:00 [error] 27#27: *1143 recv() failed (111: Connection refused) while in http auth state, client: 46.148.40.52, server: 0.0.0.0:25, login: "consultation@<domain>.com"
```

I think probably there's something wrong with my server configuration.

**Comment by nextgens** [comment]
These should be a very rare occurrence and yes, "something is wrong". I suggest you ask on https://riot.im/app/#/room/#mailu:tedomum.net if you need assistance.

**Comment by Diman0** [comment]
I have implemented the config from this PR and will check on Sunday/Monday if it worked. 
The config itself looks good.

**Comment by Diman0** [comment]
Since we are touching faq.rst anyway, on line 541 and 548 there are two small errors that could be fixed. 
541: missing space character . After ''admin''
548: [ character can be removed

**Comment by Diman0** [comment]
@nextgens  It doesn't work. Testing with fail2ban-regex also fails for me. 
When I check how it is logged in systemd using `journalctl -rt mailu-front`, I see:
`Mar 12 09:03:07 mailutest mailu-front[665771]: 2023/03/12 09:03:07 [info] 11#11: *2809 client login failed: "AUTH not supported" while in http auth state, client: 5.189.169.110, server: 0.0.0.0:25, login: "username.com"`
The first part is in white. The second part is in red and should be the actual log message. That is:

`2023/03/12 09:03:07 [info] 11#11: *2809 client login failed: "AUTH not supported" while in http auth state, client: 5.189.169.110, server: 0.0.0.0:25, login: "username.com"``

The datepattern does match. Fail2ban-regex shows the date pattern can be found for each log line.
When I remove the date:
`[info] 11#11: *2809 client login failed: "AUTH not supported" while in http auth state, client: 5.189.169.110, server: 0.0.0.0:25, login: "username.com"``
then the fail2ban-regex does work.  So it must be the date pattern.

**Comment by nextgens** [comment]
@Diman0 it was working as is for me... but I have pushed an even more precise regexp so that we can find out where it fails for you.

The datepattern is only matching ``Mar 12 09:03:07`` : I get a hit on ``{^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?`` so the regexp needs to take everything else into account.

```
fail2ban-regex /tmp/b '^ \S+ docker\-front\[\d+\]: \S+ \S+ \[info\] \d+#\d+: \*\d+ client login failed: \"AUTH not supported\" while in http auth state, client: <HOST>, server:'
```

**Comment by Diman0** [comment]
bors try

**Comment by nextgens** [comment]
bors try

**Comment by Diman0** [comment]
The bad-auth-bots filter is working for me as well now.
Now I only need to test the rate limiting part.

**Comment by nextgens** [comment]
bors try

**Comment by Diman0** [comment]
The rate limiting works as well and the documentation looks good now. i will approve the PR

**Review by Diman0 — APPROVED** [review]
LGTM

**Pull request merged**
