### PR TITLE
Standarize images

### PR DESCRIPTION
**Pull request by ionutfilip**
### Cleaning up start.py files

Cleaned up start.py files based on discussion on [#560](https://github.com/Mailu/Mailu/pull/560#discussion_r223207160)

### Switching from shell to python on startup scripts

Based on the discussion on [Matrix](https://riot.im/app/#/room/!RJFCFtixHgPhzacdhW:tedomum.net/$1533887839211990rTewa:matrix.org)
we changed the startup script from shell to python

### CODE REVIEW

**Comment by muhlemmer** [comment]
I will refrain from review, as this was done under my guidance.

**Comment by kaiyou** [comment]
Same question here. Also, it looks fine, but can be later improved by replacing some os.system calls with native Python calls.

**Comment by muhlemmer** [comment]
The current way we are creating the images are not ideal. Every ENTRY in a Dockerfile creates a new layer. Docker attempts to re-use those layers if they are identical. However, we install python together with all the other stuff we need for the images you mentioned. This makes them Unique and not sharable. By using a python base image, only install custom packages in `RUN`, the a larger part of the image becomes shareable and thus more consistent. Note that in this case, the image is shared with Admin. And later it will be the case also with Unbound.

Some examples:

**Current master**
```
[tim@mars ~]$ docker system df -v   
Images space usage:

REPOSITORY          TAG                 IMAGE ID            CREATED ago          SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS
mailu/fetchmail     master              f4f8dc617928        6 minutes ago ago    86.55MB             78.22MB             8.326MB             1
mailu/rainloop      master              d42e86644183        6 minutes ago ago    425.2MB             0B                  425.2MB             1
mailu/admin         master              7b7c9eab7976        8 minutes ago ago    173.7MB             78.22MB             95.43MB             1
mailu/radicale      master              191538c17b80        11 minutes ago ago   95.48MB             0B                  95.48MB             1
mailu/clamav        master              f897b288c0ae        11 minutes ago ago   15.3MB              4.413MB             10.88MB             1
mailu/postfix       master              27de0b85d2fa        11 minutes ago ago   76.06MB             4.413MB             71.65MB             1
mailu/rspamd        master              9c1ec2ae4ab6        11 minutes ago ago   119.3MB             4.413MB             114.9MB             1
mailu/dovecot       master              1c6f8aba3595        11 minutes ago ago   141.1MB             4.413MB             136.7MB             1
mailu/nginx         master              85ae427ff5ad        11 minutes ago ago   88.86MB             4.413MB             84.45MB             1
redis               alpine              05635ee9e1c7        11 days ago ago      40.85MB             4.413MB             36.43MB             1
```

**This branch** as PR-ed (clamav using python-3:alpine)

```
REPOSITORY          TAG                 IMAGE ID            CREATED ago          SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS
mailu/admin         master              22caf802faf4        10 minutes ago ago   173.7MB             78.22MB             95.43MB             1
mailu/clamav        master              ad7d91f1e8f8        10 minutes ago ago   86.02MB             78.22MB             7.804MB             1
mailu/rspamd        master              b8be4796ca14        10 minutes ago ago   119.3MB             4.413MB             114.9MB             1
mailu/postfix       master              87c464a14337        10 minutes ago ago   76.06MB             4.413MB             71.65MB             1
mailu/dovecot       master              67a816e5461c        10 minutes ago ago   141.1MB             4.413MB             136.7MB             1
mailu/fetchmail     master              f4f8dc617928        20 minutes ago ago   86.55MB             78.22MB             8.326MB             1
mailu/rainloop      master              d42e86644183        20 minutes ago ago   425.2MB             0B                  425.2MB             1
mailu/radicale      master              191538c17b80        24 minutes ago ago   95.48MB             0B                  95.48MB             1
mailu/nginx         master              85ae427ff5ad        25 minutes ago ago   88.86MB             4.413MB             84.45MB             1
redis               alpine              05635ee9e1c7        11 days ago ago      40.85MB             4.413MB             36.43MB             1
```

**This branch modified** to use `alpine:3.8` and install python and pip.

```
Images space usage:

REPOSITORY          TAG                 IMAGE ID            CREATED ago          SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS
mailu/clamav        master              77c3bb996ba6        19 seconds ago ago   64.37MB             4.413MB             59.95MB             1
mailu/admin         master              22caf802faf4        22 minutes ago ago   173.7MB             78.22MB             95.43MB             1
mailu/rspamd        master              b8be4796ca14        22 minutes ago ago   119.3MB             4.413MB             114.9MB             1
mailu/postfix       master              87c464a14337        23 minutes ago ago   76.06MB             4.413MB             71.65MB             1
mailu/dovecot       master              67a816e5461c        23 minutes ago ago   141.1MB             4.413MB             136.7MB             1
mailu/fetchmail     master              f4f8dc617928        32 minutes ago ago   86.55MB             78.22MB             8.326MB             1
mailu/rainloop      master              d42e86644183        32 minutes ago ago   425.2MB             0B                  425.2MB             1
mailu/radicale      master              191538c17b80        36 minutes ago ago   95.48MB             0B                  95.48MB             1
mailu/nginx         master              85ae427ff5ad        37 minutes ago ago   88.86MB             4.413MB             84.45MB             1
redis               alpine              05635ee9e1c7        11 days ago ago      40.85MB             4.413MB             36.43MB             1
```

You can see the Unique size went up from 7.8 MB to 60 MB.

So, in fact `clamav` is the only one playing nicely now. If we want to do it right, all the other Dockerfiles need changing to `python:3-alpine`. However, we didn't want to do this now, as we are discussing to change from [Alpine to Debian-slim](https://github.com/Mailu/Mailu/issues/593#issuecomment-428230293). For which I volunteered to implement and test it when more urgent matters are dealt with.

If you guys really insist on consistency, I can try to find some time tomorrow to move all images to `python:3-alpine` and commit it to this PR.

**Comment by muhlemmer** [comment]
So, I've done the migration to `python:3.6-alpine`. Only the result is not what I expected. Sharing is now much better. But the net result is near-zero, because the python image is way bigger then vanilla alpine + python3. So that was some wasted time. I'll try the same, based on alpine + python3.

Some intermediate results:

## Master
```
[tim@sky ~]$ sudo du -ch /var/lib/docker/overlay2 | grep total
2.8G    total

[tim@sky ~]$ docker system df -v
Images space usage:

REPOSITORY          TAG                 IMAGE ID            CREATED ago          SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS
mailu/fetchmail     master              f5b4c1caafd4        21 minutes ago ago   86.55MB             78.22MB             8.326MB             1
mailu/rainloop      master              6e6019e66654        21 minutes ago ago   425.2MB             0B                  425.2MB             1
mailu/admin         master              6d58f891fb60        22 minutes ago ago   173.7MB             78.22MB             95.43MB             1
mailu/radicale      master              698cf9cd436b        23 minutes ago ago   95.48MB             0B                  95.48MB             1
mailu/clamav        master              5f6db92cdfc7        23 minutes ago ago   15.3MB              4.413MB             10.88MB             1
mailu/rspamd        master              ef580aa60599        24 minutes ago ago   119.3MB             4.413MB             114.9MB             1
mailu/postfix       master              3e6bde263eb1        24 minutes ago ago   76.06MB             4.413MB             71.65MB             1
mailu/dovecot       master              1668bf479425        24 minutes ago ago   141.1MB             4.413MB             136.7MB             1
mailu/unbound       master              cac97c153198        25 minutes ago ago   96.99MB             78.22MB             18.77MB             1
mailu/nginx         master              c24b86e3173e        25 minutes ago ago   88.86MB             4.413MB             84.45MB             1
redis               alpine              05635ee9e1c7        12 days ago ago      40.85MB             4.413MB             36.43MB             1
```

## My working branch:

```
[tim@sky ~]$ docker system df -v
Images space usage:

REPOSITORY          TAG                 IMAGE ID            CREATED ago             SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS
mailu/fetchmail     master              954b65011b51        About an hour ago ago   82.93MB             74.3MB              8.625MB             1
mailu/clamav        master              9b9c6e2e604a        About an hour ago ago   82.14MB             74.3MB              7.83MB              1
mailu/rspamd        master              1c25402d458c        About an hour ago ago   142.9MB             81.84MB             61.05MB             1
mailu/postfix       master              e028989a04e4        About an hour ago ago   99.31MB             81.84MB             17.48MB             1
mailu/dovecot       master              c35786549a41        About an hour ago ago   164.8MB             81.84MB             82.96MB             1
mailu/nginx         master              1d95fa7111ad        About an hour ago ago   153.6MB             81.47MB             72.1MB              1
mailu/rainloop      master              517ed9f990bd        2 hours ago ago         426.6MB             0B                  426.6MB             1
mailu/admin         master              568a9b9a8360        2 hours ago ago         173.7MB             78.22MB             95.43MB             1
mailu/unbound       master              fcd02d1dfabf        2 hours ago ago         96.99MB             78.22MB             18.77MB             1
mailu/radicale      master              698cf9cd436b        2 hours ago ago         95.48MB             0B                  95.48MB             1
redis               alpine              05635ee9e1c7        12 days ago ago         40.85MB             4.413MB             36.43MB             1
```

**Comment by muhlemmer** [comment]
The output of the above `du` command was influenced by the running container. A better way of comparing this, is after the containers are stopped. I `docker system prune -a` just before stopping, so that only the production images are left behind.

So now after migrating all images to `alpine:3.8` I have the following stats:

```
Images space usage:

REPOSITORY          TAG                 IMAGE ID            CREATED ago          SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS
mailu/admin         master              47cb926daba1        9 minutes ago ago    143.3MB             57.54MB             85.75MB             0
mailu/rspamd        master              f191638b22fb        23 minutes ago ago   120.7MB             58.92MB             61.82MB             0
mailu/fetchmail     master              f905819b89b7        24 minutes ago ago   61.87MB             57.54MB             4.33MB              0
mailu/clamav        master              2d1203e567c1        25 minutes ago ago   66.09MB             57.54MB             8.552MB             0
mailu/unbound       master              497849547db6        25 minutes ago ago   70.45MB             58.56MB             11.89MB             0
mailu/nginx         master              8fe480df0081        25 minutes ago ago   149.3MB             58.56MB             90.73MB             0
mailu/postfix       master              70b50fde78f3        31 minutes ago ago   76.42MB             58.92MB             17.5MB              0
mailu/dovecot       master              74230a7c4d6f        31 minutes ago ago   141.4MB             58.92MB             82.51MB             0
mailu/rainloop      master              517ed9f990bd        3 hours ago ago      426.6MB             0B                  426.6MB             0
mailu/radicale      master              698cf9cd436b        3 hours ago ago      95.48MB             0B                  95.48MB             0
redis               alpine              05635ee9e1c7        12 days ago ago      40.85MB             4.413MB             36.43MB             0
```
There is about ~58mb of shared size on all the Mailu alpine based images. So a certain improvement!

To compare output of the `du` command:
Master:

```
sudo du -ch /var/lib/docker/overlay2 | grep total
1.3G    total
```

This branch: 

```
sudo du -ch /var/lib/docker/overlay2 | grep total
1.1G    total
```
That's a 15% reduction :smile:. I'll still have to do a production test. Will post back when done.

**Comment by muhlemmer** [comment]
Everything seems to work just fine. Ready from my point of view.

**Pull request merged**
