### PR TITLE
Changelog for release 1.6

### PR DESCRIPTION
**Pull request by hoellen**
I went through the issues and PRs since 2017-11-21 and wrote a first changelog for the `1.6` release.
From now on we should extend the changelog when we have new features/changes.

*No guarantee of correctness and completeness :P*

### CODE REVIEW

**Comment by hoellen** [comment]
#758

**Comment by muhlemmer** [comment]
O my, nice job! I wouldn't blame you if there was a missing entry ;)

**Comment by tobias992** [comment]
Hello,
there are any plans for final 1.6?

**Comment by tobias992** [comment]
Cool,
thank you for the quick answer.
I an looking for an alternative for Mailcow.
Then i found your Mailserver but with last update in 2017. This was the reason for my question.
I tested a little bit with the demo server. Do you have a function for set a rate limit per mail address?


~ Tobias Fronk

⁣BlueMail for Android herunterladen ​

**Comment by hoellen** [comment]
There is a rate limit per source IP address:
https://github.com/Mailu/Mailu/blob/356012a672335a291366a79c363cc47c24ef0930/docs/compose/.env#L42-L43

**Comment by tobias992** [comment]
Okay,
does i understand right that this set the  limit per domain?

⁣BlueMail for Android herunterladen ​

**Comment by hoellen** [comment]
It sets the limit per Client IP address.

**Comment by tobias992** [comment]
I dont understand, sorry for my bad english.
I have an example. I have a shared hosting Webserver with domain1.com (ip: 1.2.3.4) and domain2.com (ip: 1.2.3.4). The Mailserver is setup with Mailu on ip: 5.6.7.8. Limit is set 1000/h.
How the limit is working? All Domains from 1.2.3.4 has the limit 1000/h or both...

In Mailcow i can set a limit per Domain/E-Mail Address... thats why i am ask.

**Comment by hoellen** [comment]
`User A` (client IP) can connect 1000/h to your Mailu setup (doesn't matter which domain: domain1.com or domain2.com)
A second `user B` can also connect 1000/h to your mailu instance for domain1.com and domain2.com in the same time.
And so on... Is this more clear?

**Pull request merged**
